package seedmodels

import (
	"github.com/timmaaaz/ichor/business/domain/core/pagebus"
)

// =============================================================================
// PAGE CONFIGS
// Array order is the single source of truth for SortOrder.
// SortOrder is derived from index (i+1) at seed time — do not add it here.
// =============================================================================
var AllPages = []pagebus.NewPage{
	// DASHBOARD MODULE
	{
		Path:       "/dashboard",
		Name:       "Main Dashboard",
		Module:     "dashboard",
		Icon:       "material-symbols:space-dashboard",
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/dashboard/analytics",
		Name:       "Analytics Dashboard",
		Module:     "dashboard",
		Icon:       "material-symbols:analytics",
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/alerts",
		Name:       "Notification Center",
		Module:     "dashboard",
		Icon:       "material-symbols:notifications",
		IsActive:   true,
		ShowInMenu: true,
	},

	// SALES MODULE
	{
		Path:       "/sales",
		Name:       "Sales Dashboard",
		Module:     "sales",
		Icon:       "material-symbols:point-of-sale",
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/sales/orders",
		Name:       "Order Management",
		Module:     "sales",
		Icon:       "material-symbols:receipt-long",
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/sales/customers",
		Name:       "Customer Management",
		Module:     "sales",
		Icon:       "material-symbols:group",
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/sales/reports",
		Name:       "Sales Reports",
		Module:     "sales",
		Icon:       "material-symbols:assessment",
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/sales/orders/:id/invoice",
		Name:       "Invoice",
		Module:     "sales",
		Icon:       "material-symbols:receipt-long",
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/sales/orders/new",
		Name:       "New Order Form",
		Module:     "sales",
		Icon:       "material-symbols:add-shopping-cart",
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/sales/customers/new",
		Name:       "New Customer Form",
		Module:     "sales",
		Icon:       "material-symbols:person-add",
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/sales/customers/:id",
		Name:       "Customer Details",
		Module:     "sales",
		Icon:       "material-symbols:person",
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/sales/orders/:id",
		Name:       "Order Details",
		Module:     "sales",
		Icon:       "material-symbols:receipt",
		IsActive:   true,
		ShowInMenu: false,
	},

	// INVENTORY MODULE
	{
		Path:       "/inventory",
		Name:       "Inventory Dashboard",
		Module:     "inventory",
		Icon:       "material-symbols:inventory-2",
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/inventory/items",
		Name:       "Item Management",
		Module:     "inventory",
		Icon:       "material-symbols:category",
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/inventory/warehouses",
		Name:       "Warehouse Management",
		Module:     "inventory",
		Icon:       "material-symbols:warehouse",
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/inventory/transfers",
		Name:       "Transfer Orders",
		Module:     "inventory",
		Icon:       "material-symbols:sync-alt",
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/inventory/adjustments",
		Name:       "Stock Adjustments",
		Module:     "inventory",
		Icon:       "material-symbols:tune",
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/inventory/reports",
		Name:       "Inventory Reports",
		Module:     "inventory",
		Icon:       "material-symbols:summarize",
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/inventory/locations",
		Name:       "Location Management",
		Module:     "inventory",
		Icon:       "material-symbols:location-on",
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/inventory/zones",
		Name:       "Zone Management",
		Module:     "inventory",
		Icon:       "material-symbols:grid-view",
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/inventory/items/new",
		Name:       "New Inventory Item",
		Module:     "inventory",
		Icon:       "material-symbols:add-box",
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/inventory/items/:id",
		Name:       "Inventory Item Details",
		Module:     "inventory",
		Icon:       "material-symbols:inventory",
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/inventory/warehouses/new",
		Name:       "New Warehouse",
		Module:     "inventory",
		Icon:       "material-symbols:add-business",
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/inventory/warehouses/:id",
		Name:       "Warehouse Details",
		Module:     "inventory",
		Icon:       "material-symbols:domain",
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/inventory/transfers/new",
		Name:       "New Transfer Order",
		Module:     "inventory",
		Icon:       "material-symbols:add-circle",
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/inventory/transfers/:id",
		Name:       "Transfer Order Details",
		Module:     "inventory",
		Icon:       "material-symbols:compare-arrows",
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/inventory/adjustments/new",
		Name:       "New Stock Adjustment",
		Module:     "inventory",
		Icon:       "material-symbols:edit-note",
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/inventory/adjustments/:id",
		Name:       "Stock Adjustment Details",
		Module:     "inventory",
		Icon:       "material-symbols:analytics",
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/inventory/locations/new",
		Name:       "New Location",
		Module:     "inventory",
		Icon:       "material-symbols:add-location",
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/inventory/locations/:id",
		Name:       "Location Details",
		Module:     "inventory",
		Icon:       "material-symbols:location-pin",
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/inventory/zones/new",
		Name:       "New Zone",
		Module:     "inventory",
		Icon:       "material-symbols:add-circle",
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/inventory/zones/:id",
		Name:       "Zone Details",
		Module:     "inventory",
		Icon:       "material-symbols:area-chart",
		IsActive:   true,
		ShowInMenu: false,
	},

	// PROCUREMENT MODULE
	{
		Path:       "/procurement",
		Name:       "Procurement Dashboard",
		Module:     "procurement",
		Icon:       "material-symbols:shopping-cart",
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/procurement/suppliers",
		Name:       "Supplier Management",
		Module:     "procurement",
		Icon:       "material-symbols:local-shipping",
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/procurement/orders",
		Name:       "Purchase Orders",
		Module:     "procurement",
		Icon:       "material-symbols:shopping-bag",
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/procurement/approvals",
		Name:       "Approval Queue",
		Module:     "procurement",
		Icon:       "material-symbols:check-circle",
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/procurement/suppliers/new",
		Name:       "New Supplier",
		Module:     "procurement",
		Icon:       "material-symbols:add-business",
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/procurement/suppliers/:id",
		Name:       "Supplier Details",
		Module:     "procurement",
		Icon:       "material-symbols:business-center",
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/procurement/orders/new",
		Name:       "New Purchase Order",
		Module:     "procurement",
		Icon:       "material-symbols:note-add",
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/procurement/orders/:id",
		Name:       "Purchase Order Details",
		Module:     "procurement",
		Icon:       "material-symbols:description",
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/procurement/approvals/:id",
		Name:       "Procurement Approval Detail",
		Module:     "procurement",
		Icon:       "material-symbols:approval",
		IsActive:   true,
		ShowInMenu: false,
	},

	// PRODUCTS MODULE
	{
		Path:       "/products",
		Name:       "Products",
		Module:     "products",
		Icon:       "material-symbols:inventory",
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/products/new",
		Name:       "New Product",
		Module:     "products",
		Icon:       "material-symbols:add-box",
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/products/:id",
		Name:       "Product Details",
		Module:     "products",
		Icon:       "material-symbols:package-2",
		IsActive:   true,
		ShowInMenu: false,
	},

	// ASSETS MODULE
	{
		Path:       "/assets",
		Name:       "Asset Dashboard",
		Module:     "assets",
		Icon:       "material-symbols:apartment",
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/assets/list",
		Name:       "Asset List",
		Module:     "assets",
		Icon:       "material-symbols:list",
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/assets/requests",
		Name:       "Asset Requests",
		Module:     "assets",
		Icon:       "material-symbols:request-quote",
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/assets/maintenance",
		Name:       "Maintenance Schedule",
		Module:     "assets",
		Icon:       "material-symbols:build",
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/assets/list/new",
		Name:       "New Asset",
		Module:     "assets",
		Icon:       "material-symbols:add-circle",
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/assets/list/:id",
		Name:       "Asset Details",
		Module:     "assets",
		Icon:       "material-symbols:apartment",
		IsActive:   true,
		ShowInMenu: false,
	},

	// HR MODULE
	{
		Path:       "/hr",
		Name:       "HR Dashboard",
		Module:     "hr",
		Icon:       "material-symbols:badge",
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/hr/employees",
		Name:       "Employee Directory",
		Module:     "hr",
		Icon:       "material-symbols:groups",
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/hr/onboarding",
		Name:       "Onboarding",
		Module:     "hr",
		Icon:       "material-symbols:how-to-reg",
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/hr/offices",
		Name:       "Office Management",
		Module:     "hr",
		Icon:       "material-symbols:business",
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/hr/reports",
		Name:       "HR Reports",
		Module:     "hr",
		Icon:       "material-symbols:bar-chart",
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/hr/employees/new",
		Name:       "New Employee",
		Module:     "hr",
		Icon:       "material-symbols:person-add",
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/hr/employees/:id",
		Name:       "Employee Details",
		Module:     "hr",
		Icon:       "material-symbols:badge",
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/hr/offices/new",
		Name:       "New Office",
		Module:     "hr",
		Icon:       "material-symbols:add-business",
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/hr/offices/:id",
		Name:       "Office Details",
		Module:     "hr",
		Icon:       "material-symbols:domain",
		IsActive:   true,
		ShowInMenu: false,
	},

	// ADMIN MODULE
	{
		Path:       "/admin",
		Name:       "Admin Dashboard",
		Module:     "admin",
		Icon:       "material-symbols:admin-panel-settings",
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/admin/users",
		Name:       "User Management",
		Module:     "admin",
		Icon:       "material-symbols:manage-accounts",
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/admin/roles",
		Name:       "Role Management",
		Module:     "admin",
		Icon:       "material-symbols:security",
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/admin/config",
		Name:       "System Configuration",
		Module:     "admin",
		Icon:       "material-symbols:settings-applications",
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/admin/audit",
		Name:       "Audit Logs",
		Module:     "admin",
		Icon:       "material-symbols:history",
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/admin/config/pages",
		Name:       "Page Configs",
		Module:     "admin",
		Icon:       "material-symbols:page-info",
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/admin/config/tables",
		Name:       "Table Configs",
		Module:     "admin",
		Icon:       "material-symbols:table",
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/admin/config/forms",
		Name:       "Form Configs",
		Module:     "admin",
		Icon:       "material-symbols:edit-document",
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/admin/config/import-export",
		Name:       "Import/Export",
		Module:     "admin",
		Icon:       "material-symbols:import-export",
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/admin/users/new",
		Name:       "New User",
		Module:     "admin",
		Icon:       "material-symbols:person-add",
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/admin/users/:id",
		Name:       "User Details",
		Module:     "admin",
		Icon:       "material-symbols:account-circle",
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/admin/roles/new",
		Name:       "New Role",
		Module:     "admin",
		Icon:       "material-symbols:add-moderator",
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/admin/roles/:id",
		Name:       "Role Details",
		Module:     "admin",
		Icon:       "material-symbols:admin-panel-settings",
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/admin/config/page-configs/new",
		Name:       "New Page Config",
		Module:     "admin",
		Icon:       "material-symbols:add-circle",
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/admin/config/page-configs/:id",
		Name:       "Edit Page Config",
		Module:     "admin",
		Icon:       "material-symbols:edit",
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/admin/config/page-content/:id",
		Name:       "Page Content Editor",
		Module:     "admin",
		Icon:       "material-symbols:edit-note",
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/admin/config/page-actions/:page_config_id",
		Name:       "Page Actions Editor",
		Module:     "admin",
		Icon:       "material-symbols:touch-app",
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/admin/config/table-configs/new",
		Name:       "New Table Config",
		Module:     "admin",
		Icon:       "material-symbols:add-circle",
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/admin/config/table-configs/:id",
		Name:       "Edit Table Config",
		Module:     "admin",
		Icon:       "material-symbols:edit",
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/admin/config/forms/new",
		Name:       "New Form Config",
		Module:     "admin",
		Icon:       "material-symbols:add-circle",
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/admin/config/forms/:id",
		Name:       "Edit Form Config",
		Module:     "admin",
		Icon:       "material-symbols:edit",
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/admin/config/:id",
		Name:       "Edit Config",
		Module:     "admin",
		Icon:       "material-symbols:edit",
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/admin/config/simple-tables/:id",
		Name:       "Simple Table",
		Module:     "admin",
		Icon:       "material-symbols:edit",
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/admin/config/simple-tables/",
		Name:       "Simple Tables",
		Module:     "admin",
		Icon:       "material-symbols:edit",
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/admin/config/simple-charts/:id",
		Name:       "Simple Charts",
		Module:     "admin",
		Icon:       "material-symbols:edit",
		IsActive:   true,
		ShowInMenu: false,
	},

	// WORKFLOW MODULE
	{
		Path:       "/workflow",
		Name:       "Automation Rules",
		Module:     "workflow",
		Icon:       "material-symbols:account-tree",
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/workflow/executions",
		Name:       "Execution History",
		Module:     "workflow",
		Icon:       "material-symbols:history",
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/workflow/editor",
		Name:       "Workflow Editor",
		Module:     "workflow",
		Icon:       "material-symbols:history",
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/workflow/editor/:id",
		Name:       "Workflow Editor",
		Module:     "workflow",
		Icon:       "material-symbols:schema",
		IsActive:   true,
		ShowInMenu: false,
	},
}
