package seedmodels

import (
	"github.com/timmaaaz/ichor/business/domain/core/pagebus"
)

// =============================================================================
// PAGE CONFIGS
// =============================================================================
var AllPages = []pagebus.NewPage{
	// DASHBOARD MODULE
	{
		Path:       "/dashboard",
		Name:       "Main Dashboard",
		Module:     "dashboard",
		Icon:       "material-symbols:space-dashboard",
		SortOrder:  1,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/dashboard/analytics",
		Name:       "Analytics Dashboard",
		Module:     "dashboard",
		Icon:       "material-symbols:analytics",
		SortOrder:  2,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/alerts",
		Name:       "Notification Center",
		Module:     "dashboard",
		Icon:       "material-symbols:notifications",
		SortOrder:  3,
		IsActive:   true,
		ShowInMenu: true,
	},

	// SALES MODULE
	{
		Path:       "/sales",
		Name:       "Sales Dashboard",
		Module:     "sales",
		Icon:       "material-symbols:point-of-sale",
		SortOrder:  3,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/sales/orders",
		Name:       "Order Management",
		Module:     "sales",
		Icon:       "material-symbols:receipt-long",
		SortOrder:  4,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/sales/orders/new",
		Name:       "New Order Form",
		Module:     "sales",
		Icon:       "material-symbols:add-shopping-cart",
		SortOrder:  5,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/sales/customers",
		Name:       "Customer Management",
		Module:     "sales",
		Icon:       "material-symbols:group",
		SortOrder:  6,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/sales/customers/new",
		Name:       "New Customer Form",
		Module:     "sales",
		Icon:       "material-symbols:person-add",
		SortOrder:  7,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/sales/customers/:id",
		Name:       "Customer Details",
		Module:     "sales",
		Icon:       "material-symbols:person",
		SortOrder:  33,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/sales/orders/:id",
		Name:       "Order Details",
		Module:     "sales",
		Icon:       "material-symbols:receipt",
		SortOrder:  34,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/sales/reports",
		Name:       "Sales Reports",
		Module:     "sales",
		Icon:       "material-symbols:assessment",
		SortOrder:  8,
		IsActive:   true,
		ShowInMenu: true,
	},

	// INVENTORY MODULE
	{
		Path:       "/inventory",
		Name:       "Inventory Dashboard",
		Module:     "inventory",
		Icon:       "material-symbols:inventory-2",
		SortOrder:  9,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/inventory/items",
		Name:       "Item Management",
		Module:     "inventory",
		Icon:       "material-symbols:category",
		SortOrder:  10,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/inventory/items/new",
		Name:       "New Inventory Item",
		Module:     "inventory",
		Icon:       "material-symbols:add-box",
		SortOrder:  35,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/inventory/items/:id",
		Name:       "Inventory Item Details",
		Module:     "inventory",
		Icon:       "material-symbols:inventory",
		SortOrder:  36,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/inventory/warehouses",
		Name:       "Warehouse Management",
		Module:     "inventory",
		Icon:       "material-symbols:warehouse",
		SortOrder:  11,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/inventory/warehouses/new",
		Name:       "New Warehouse",
		Module:     "inventory",
		Icon:       "material-symbols:add-business",
		SortOrder:  37,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/inventory/warehouses/:id",
		Name:       "Warehouse Details",
		Module:     "inventory",
		Icon:       "material-symbols:domain",
		SortOrder:  38,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/inventory/transfers",
		Name:       "Transfer Orders",
		Module:     "inventory",
		Icon:       "material-symbols:sync-alt",
		SortOrder:  12,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/inventory/transfers/new",
		Name:       "New Transfer Order",
		Module:     "inventory",
		Icon:       "material-symbols:add-circle",
		SortOrder:  39,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/inventory/transfers/:id",
		Name:       "Transfer Order Details",
		Module:     "inventory",
		Icon:       "material-symbols:compare-arrows",
		SortOrder:  40,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/inventory/adjustments",
		Name:       "Stock Adjustments",
		Module:     "inventory",
		Icon:       "material-symbols:tune",
		SortOrder:  13,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/inventory/adjustments/new",
		Name:       "New Stock Adjustment",
		Module:     "inventory",
		Icon:       "material-symbols:edit-note",
		SortOrder:  41,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/inventory/adjustments/:id",
		Name:       "Stock Adjustment Details",
		Module:     "inventory",
		Icon:       "material-symbols:analytics",
		SortOrder:  42,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/inventory/reports",
		Name:       "Inventory Reports",
		Module:     "inventory",
		Icon:       "material-symbols:summarize",
		SortOrder:  14,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/inventory/locations",
		Name:       "Location Management",
		Module:     "inventory",
		Icon:       "material-symbols:location-on",
		SortOrder:  15,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/inventory/locations/new",
		Name:       "New Location",
		Module:     "inventory",
		Icon:       "material-symbols:add-location",
		SortOrder:  103,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/inventory/locations/:id",
		Name:       "Location Details",
		Module:     "inventory",
		Icon:       "material-symbols:location-pin",
		SortOrder:  104,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/inventory/zones",
		Name:       "Zone Management",
		Module:     "inventory",
		Icon:       "material-symbols:grid-view",
		SortOrder:  16,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/inventory/zones/new",
		Name:       "New Zone",
		Module:     "inventory",
		Icon:       "material-symbols:add-circle",
		SortOrder:  105,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/inventory/zones/:id",
		Name:       "Zone Details",
		Module:     "inventory",
		Icon:       "material-symbols:area-chart",
		SortOrder:  106,
		IsActive:   true,
		ShowInMenu: false,
	},

	// PROCUREMENT MODULE
	{
		Path:       "/procurement",
		Name:       "Procurement Dashboard",
		Module:     "procurement",
		Icon:       "material-symbols:shopping-cart",
		SortOrder:  15,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/procurement/suppliers",
		Name:       "Supplier Management",
		Module:     "procurement",
		Icon:       "material-symbols:local-shipping",
		SortOrder:  16,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/procurement/suppliers/new",
		Name:       "New Supplier",
		Module:     "procurement",
		Icon:       "material-symbols:add-business",
		SortOrder:  43,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/procurement/suppliers/:id",
		Name:       "Supplier Details",
		Module:     "procurement",
		Icon:       "material-symbols:business-center",
		SortOrder:  44,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/procurement/orders",
		Name:       "Purchase Orders",
		Module:     "procurement",
		Icon:       "material-symbols:shopping-bag",
		SortOrder:  17,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/procurement/orders/new",
		Name:       "New Purchase Order",
		Module:     "procurement",
		Icon:       "material-symbols:note-add",
		SortOrder:  45,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/procurement/orders/:id",
		Name:       "Purchase Order Details",
		Module:     "procurement",
		Icon:       "material-symbols:description",
		SortOrder:  46,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/procurement/approvals",
		Name:       "Approval Queue",
		Module:     "procurement",
		Icon:       "material-symbols:check-circle",
		SortOrder:  18,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/procurement/approvals/:id",
		Name:       "Procurement Approval Detail",
		Module:     "procurement",
		Icon:       "material-symbols:approval",
		SortOrder:  102,
		IsActive:   true,
		ShowInMenu: false,
	},

	// ASSETS MODULE
	{
		Path:       "/assets",
		Name:       "Asset Dashboard",
		Module:     "assets",
		Icon:       "material-symbols:apartment",
		SortOrder:  19,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/assets/list",
		Name:       "Asset List",
		Module:     "assets",
		Icon:       "material-symbols:list",
		SortOrder:  20,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/assets/list/new",
		Name:       "New Asset",
		Module:     "assets",
		Icon:       "material-symbols:add-circle",
		SortOrder:  47,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/assets/list/:id",
		Name:       "Asset Details",
		Module:     "assets",
		Icon:       "material-symbols:apartment",
		SortOrder:  48,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/assets/requests",
		Name:       "Asset Requests",
		Module:     "assets",
		Icon:       "material-symbols:request-quote",
		SortOrder:  21,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/assets/maintenance",
		Name:       "Maintenance Schedule",
		Module:     "assets",
		Icon:       "material-symbols:build",
		SortOrder:  22,
		IsActive:   true,
		ShowInMenu: true,
	},

	// HR MODULE
	{
		Path:       "/hr",
		Name:       "HR Dashboard",
		Module:     "hr",
		Icon:       "material-symbols:badge",
		SortOrder:  23,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/hr/employees",
		Name:       "Employee Directory",
		Module:     "hr",
		Icon:       "material-symbols:groups",
		SortOrder:  24,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/hr/employees/new",
		Name:       "New Employee",
		Module:     "hr",
		Icon:       "material-symbols:person-add",
		SortOrder:  49,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/hr/employees/:id",
		Name:       "Employee Details",
		Module:     "hr",
		Icon:       "material-symbols:badge",
		SortOrder:  50,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/hr/onboarding",
		Name:       "Onboarding",
		Module:     "hr",
		Icon:       "material-symbols:how-to-reg",
		SortOrder:  25,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/hr/offices",
		Name:       "Office Management",
		Module:     "hr",
		Icon:       "material-symbols:business",
		SortOrder:  26,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/hr/offices/new",
		Name:       "New Office",
		Module:     "hr",
		Icon:       "material-symbols:add-business",
		SortOrder:  51,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/hr/offices/:id",
		Name:       "Office Details",
		Module:     "hr",
		Icon:       "material-symbols:domain",
		SortOrder:  52,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/hr/reports",
		Name:       "HR Reports",
		Module:     "hr",
		Icon:       "material-symbols:bar-chart",
		SortOrder:  27,
		IsActive:   true,
		ShowInMenu: true,
	},

	// ADMIN MODULE
	{
		Path:       "/admin",
		Name:       "Admin Dashboard",
		Module:     "admin",
		Icon:       "material-symbols:admin-panel-settings",
		SortOrder:  28,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/admin/users",
		Name:       "User Management",
		Module:     "admin",
		Icon:       "material-symbols:manage-accounts",
		SortOrder:  29,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/admin/users/new",
		Name:       "New User",
		Module:     "admin",
		Icon:       "material-symbols:person-add",
		SortOrder:  53,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/admin/users/:id",
		Name:       "User Details",
		Module:     "admin",
		Icon:       "material-symbols:account-circle",
		SortOrder:  54,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/admin/roles",
		Name:       "Role Management",
		Module:     "admin",
		Icon:       "material-symbols:security",
		SortOrder:  30,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/admin/roles/new",
		Name:       "New Role",
		Module:     "admin",
		Icon:       "material-symbols:add-moderator",
		SortOrder:  55,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/admin/roles/:id",
		Name:       "Role Details",
		Module:     "admin",
		Icon:       "material-symbols:admin-panel-settings",
		SortOrder:  56,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/admin/config",
		Name:       "System Configuration",
		Module:     "admin",
		Icon:       "material-symbols:settings-applications",
		SortOrder:  31,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/admin/audit",
		Name:       "Audit Logs",
		Module:     "admin",
		Icon:       "material-symbols:history",
		SortOrder:  32,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/admin/config/pages",
		Name:       "Page Configs",
		Module:     "admin",
		Icon:       "material-symbols:page-info",
		SortOrder:  57,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/admin/config/tables",
		Name:       "Table Configs",
		Module:     "admin",
		Icon:       "material-symbols:table",
		SortOrder:  58,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/admin/config/forms",
		Name:       "Form Configs",
		Module:     "admin",
		Icon:       "material-symbols:edit-document",
		SortOrder:  59,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/admin/config/import-export",
		Name:       "Import/Export",
		Module:     "admin",
		Icon:       "material-symbols:import-export",
		SortOrder:  60,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/admin/config/page-configs/new",
		Name:       "New Page Config",
		Module:     "admin",
		Icon:       "material-symbols:add-circle",
		SortOrder:  61,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/admin/config/page-configs/:id",
		Name:       "Edit Page Config",
		Module:     "admin",
		Icon:       "material-symbols:edit",
		SortOrder:  62,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/admin/config/page-content/:id",
		Name:       "Page Content Editor",
		Module:     "admin",
		Icon:       "material-symbols:edit-note",
		SortOrder:  63,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/admin/config/page-actions/:page_config_id",
		Name:       "Page Actions Editor",
		Module:     "admin",
		Icon:       "material-symbols:touch-app",
		SortOrder:  64,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/admin/config/table-configs/new",
		Name:       "New Table Config",
		Module:     "admin",
		Icon:       "material-symbols:add-circle",
		SortOrder:  65,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/admin/config/table-configs/:id",
		Name:       "Edit Table Config",
		Module:     "admin",
		Icon:       "material-symbols:edit",
		SortOrder:  66,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/admin/config/forms/new",
		Name:       "New Form Config",
		Module:     "admin",
		Icon:       "material-symbols:add-circle",
		SortOrder:  67,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/admin/config/forms/:id",
		Name:       "Edit Form Config",
		Module:     "admin",
		Icon:       "material-symbols:edit",
		SortOrder:  68,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/admin/config/:id",
		Name:       "Edit Config",
		Module:     "admin",
		Icon:       "material-symbols:edit",
		SortOrder:  69,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/admin/config/simple-tables/:id",
		Name:       "Simple Table",
		Module:     "admin",
		Icon:       "material-symbols:edit",
		SortOrder:  70,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/admin/config/simple-tables/",
		Name:       "Simple Tables",
		Module:     "admin",
		Icon:       "material-symbols:edit",
		SortOrder:  71,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/admin/config/simple-charts/:id",
		Name:       "Simple Charts",
		Module:     "admin",
		Icon:       "material-symbols:edit",
		SortOrder:  72,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/sales/orders/:id/invoice",
		Name:       "Invoice",
		Module:     "sales",
		Icon:       "material-symbols:receipt-long",
		SortOrder:  73,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/workflow",
		Name:       "Automation Rules",
		Module:     "workflow",
		Icon:       "material-symbols:account-tree",
		SortOrder:  74,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/workflow/editor/:id",
		Name:       "Workflow Editor",
		Module:     "workflow",
		Icon:       "material-symbols:schema",
		SortOrder:  75,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/workflow/executions",
		Name:       "Execution History",
		Module:     "workflow",
		Icon:       "material-symbols:history",
		SortOrder:  76,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/workflow/editor",
		Name:       "Workflow Editor",
		Module:     "workflow",
		Icon:       "material-symbols:history",
		SortOrder:  77,
		IsActive:   true,
		ShowInMenu: true,
	},

	// PRODUCTS MODULE
	{
		Path:       "/products",
		Name:       "Products",
		Module:     "products",
		Icon:       "material-symbols:inventory",
		SortOrder:  78,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/products/new",
		Name:       "New Product",
		Module:     "products",
		Icon:       "material-symbols:add-box",
		SortOrder:  107,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/products/:id",
		Name:       "Product Details",
		Module:     "products",
		Icon:       "material-symbols:package-2",
		SortOrder:  108,
		IsActive:   true,
		ShowInMenu: false,
	},
}

