package seedmodels

import (
	"github.com/timmaaaz/ichor/business/sdk/tablebuilder"
)



// Suppliers Page Config
var SuppliersTableConfig = &tablebuilder.Config{
	Title:           "Suppliers Management",
	WidgetType:      "table",
	Visualization:   "table",
	PositionX:       0,
	PositionY:       0,
	Width:           12,
	Height:          8,
	RefreshInterval: 300,
	RefreshMode:     "polling",
	DataSource: []tablebuilder.DataSource{
		{
			Type:   "query",
			Source: "suppliers",
			Schema: "procurement",
			Select: tablebuilder.SelectConfig{
				Columns: []tablebuilder.ColumnDefinition{
					{Name: "id", Alias: "suppliers_id", TableColumn: "suppliers.id"},
					{Name: "name", Alias: "suppliers_name", TableColumn: "suppliers.name"},
					{Name: "lead_time_days", Alias: "suppliers_lead_time_days", TableColumn: "suppliers.lead_time_days"},
					{Name: "rating", Alias: "suppliers_rating", TableColumn: "suppliers.rating"},
					{Name: "is_active", Alias: "suppliers_is_active", TableColumn: "suppliers.is_active"},
					{Name: "contact_infos_id", Alias: "suppliers_contact_infos_id", TableColumn: "suppliers.contact_infos_id"},
					{Name: "created_date", Alias: "suppliers_created_date", TableColumn: "suppliers.created_date"},
					{Name: "updated_date", Alias: "suppliers_updated_date", TableColumn: "suppliers.updated_date"},
				},
				ForeignTables: []tablebuilder.ForeignTable{
					{
						Table:            "contact_infos",
						Schema:           "core",
						RelationshipFrom: "suppliers.contact_infos_id",
						RelationshipTo:   "contact_infos.id",
						JoinType:         "left",
						Columns: []tablebuilder.ColumnDefinition{
							{Name: "primary_phone_number", Alias: "primary_phone_number", TableColumn: "contact_infos.primary_phone_number"},
							{Name: "secondary_phone_number", Alias: "secondary_phone_number", TableColumn: "contact_infos.secondary_phone_number"},
							{Name: "email_address", Alias: "email_address", TableColumn: "contact_infos.email_address"},
						},
					},
					{
						Table:            "payment_terms",
						Schema:           "core",
						RelationshipFrom: "suppliers.payment_term_id",
						RelationshipTo:   "payment_terms.id",
						JoinType:         "left",
						Columns: []tablebuilder.ColumnDefinition{
							{Name: "name", Alias: "payment_terms", TableColumn: "payment_terms.name"},
						},
					},
				},
				ClientComputedColumns: []tablebuilder.ComputedColumn{
					{
						Name:       "rating_stars",
						Expression: "round(suppliers_rating * 2) / 2",
					},
					{
						Name:       "performance_level",
						Expression: "suppliers_rating >= 4.5 ? 'excellent' : suppliers_rating >= 3.5 ? 'good' : suppliers_rating >= 2.5 ? 'fair' : 'poor'",
					},
				},
			},
			Filters: []tablebuilder.Filter{
				{
					Column:   "suppliers.is_active",
					Operator: "eq",
					Value:    true,
				},
			},
			Sort: []tablebuilder.Sort{
				{
					Column:    "suppliers.rating",
					Direction: "desc",
				},
				{
					Column:    "suppliers.name",
					Direction: "asc",
				},
			},
			Rows: 50,
		},
	},
	VisualSettings: tablebuilder.VisualSettings{
		Columns: map[string]tablebuilder.ColumnConfig{
			"suppliers_name": {
				Name:       "suppliers_name",
				Header:     "Supplier Name",
				Width:      200,
				Type:       "string",
				Sortable:   true,
				Filterable: true,
				Link: &tablebuilder.LinkConfig{
					URL:         "/procurement/suppliers/{suppliers_id}",
					LabelColumn: "suppliers_name",
				},
			},
			"payment_terms": {
				Name:       "payment_terms",
				Header:     "Payment Terms",
				Width:      150,
				Type:       "string",
				Sortable:   true,
				Filterable: true,
			},
			"suppliers_lead_time_days": {
				Name:     "suppliers_lead_time_days",
				Header:   "Lead Time (days)",
				Width:    130,
				Align:    "center",
				Type:     "number",
				Sortable: true,
				Format: &tablebuilder.FormatConfig{
					Type:      "number",
					Precision: 0,
				},
			},
			"suppliers_rating": {
				Name:     "suppliers_rating",
				Header:   "Rating",
				Width:    100,
				Align:    "center",
				Type:     "number",
				Sortable: true,
				Format: &tablebuilder.FormatConfig{
					Type:      "number",
					Precision: 2,
				},
			},
			"performance_level": {
				Name:         "performance_level",
				Header:       "Performance",
				Width:        120,
				Align:        "center",
				Type:         "computed",
				CellTemplate: "badge",
			},
			"suppliers_is_active": {
				Name:   "suppliers_is_active",
				Header: "Active",
				Width:  80,
				Align:  "center",
				Type:   "boolean",
				Format: &tablebuilder.FormatConfig{
					Type: "boolean",
				},
				Editable: &tablebuilder.EditableConfig{
					Type: "boolean",
				},
			},
			"suppliers_id": {
				Name:   "suppliers_id",
				Header: "Supplier ID",
				Type:   "uuid",
				Hidden: true,
			},
			"suppliers_contact_infos_id": {
				Hidden: true,
			},
			"suppliers_created_date": {
				Name:   "suppliers_created_date",
				Header: "Created Date",
				Width:  120,
				Type:   "datetime",
				Format: &tablebuilder.FormatConfig{
					Type:   "date",
					Format: "MM-dd-yyyy",
				},
			},
			"suppliers_updated_date": {
				Name:   "suppliers_updated_date",
				Header: "Updated Date",
				Width:  120,
				Type:   "datetime",
				Format: &tablebuilder.FormatConfig{
					Type:   "date",
					Format: "MM-dd-yyyy",
				},
			},
			"primary_phone_number": {
				Name:   "primary_phone_number",
				Header: "Primary Phone",
				Width:  150,
				Type:   "string",
			},
			"secondary_phone_number": {
				Name:   "secondary_phone_number",
				Header: "Secondary Phone",
				Width:  150,
				Type:   "string",
			},
			"email_address": {
				Name:   "email_address",
				Header: "Email",
				Width:  200,
				Type:   "string",
			},
			"rating_stars": {
				Name:   "rating_stars",
				Header: "Rating Stars",
				Width:  100,
				Type:   "computed",
			},
		},
		ConditionalFormatting: []tablebuilder.ConditionalFormat{
			{
				Column:     "performance_level",
				Condition:  "eq",
				Value:      "excellent",
				Color:      "#1b5e20",
				Background: "#c8e6c9",
				Icon:       "star",
			},
			{
				Column:     "performance_level",
				Condition:  "eq",
				Value:      "good",
				Color:      "#2e7d32",
				Background: "#e8f5e9",
				Icon:       "check-circle",
			},
			{
				Column:     "performance_level",
				Condition:  "eq",
				Value:      "fair",
				Color:      "#f57c00",
				Background: "#fff3e0",
				Icon:       "alert-circle",
			},
			{
				Column:     "performance_level",
				Condition:  "eq",
				Value:      "poor",
				Color:      "#c62828",
				Background: "#ffebee",
				Icon:       "x-circle",
			},
			{
				Column:     "is_active",
				Condition:  "eq",
				Value:      false,
				Color:      "#757575",
				Background: "#f5f5f5",
			},
		},
		Pagination: &tablebuilder.PaginationConfig{
			Enabled:         true,
			PageSizes:       []int{10, 25, 50, 100},
			DefaultPageSize: 25,
		},
	},
	Permissions: tablebuilder.Permissions{
		Roles:   []string{"admin", "procurement", "inventory_manager"},
		Actions: []string{"view", "edit", "export"},
	},
}


// =============================================================================
// PROCUREMENT CONFIGS
// =============================================================================

var PurchaseOrderTableConfig = &tablebuilder.Config{
	Title:           "Purchase Orders",
	WidgetType:      "table",
	Visualization:   "table",
	PositionX:       0,
	PositionY:       0,
	Width:           12,
	Height:          8,
	RefreshInterval: 300,
	RefreshMode:     "polling",
	DataSource: []tablebuilder.DataSource{
		{
			Type:   "query",
			Source: "purchase_orders",
			Schema: "procurement",
			Select: tablebuilder.SelectConfig{
				Columns: []tablebuilder.ColumnDefinition{
					{Name: "id", TableColumn: "purchase_orders.id"},
					{Name: "order_number", TableColumn: "purchase_orders.order_number"},
					{Name: "supplier_id", TableColumn: "purchase_orders.supplier_id"},
					{Name: "purchase_order_status_id", TableColumn: "purchase_orders.purchase_order_status_id"},
					{Name: "delivery_warehouse_id", TableColumn: "purchase_orders.delivery_warehouse_id"},
					{Name: "order_date", TableColumn: "purchase_orders.order_date"},
					{Name: "expected_delivery_date", Alias: "expected_delivery_date", TableColumn: "purchase_orders.expected_delivery_date"},
					{Name: "actual_delivery_date", Alias: "actual_delivery_date", TableColumn: "purchase_orders.actual_delivery_date"},
					{Name: "subtotal", TableColumn: "purchase_orders.subtotal"},
					{Name: "tax_amount", TableColumn: "purchase_orders.tax_amount"},
					{Name: "shipping_cost", TableColumn: "purchase_orders.shipping_cost"},
					{Name: "total_amount", Alias: "total_amount", TableColumn: "purchase_orders.total_amount"},
					{Name: "requested_by", TableColumn: "purchase_orders.requested_by"},
					{Name: "approved_by", TableColumn: "purchase_orders.approved_by"},
					{Name: "approved_date", TableColumn: "purchase_orders.approved_date"},
					{Name: "notes", TableColumn: "purchase_orders.notes"},
					{Name: "created_date", TableColumn: "purchase_orders.created_date"},
					{Name: "updated_date", TableColumn: "purchase_orders.updated_date"},
				},
				ForeignTables: []tablebuilder.ForeignTable{
					{
						Table:            "suppliers",
						Schema:           "procurement",
						RelationshipFrom: "purchase_orders.supplier_id",
						RelationshipTo:   "suppliers.id",
						JoinType:         "left",
						Columns: []tablebuilder.ColumnDefinition{
							{Name: "name", Alias: "supplier_name", TableColumn: "suppliers.name"},
							{Name: "lead_time_days", Alias: "supplier_lead_time_days", TableColumn: "suppliers.lead_time_days"},
						},
						ForeignTables: []tablebuilder.ForeignTable{
							{
								Table:            "payment_terms",
								Schema:           "core",
								RelationshipFrom: "suppliers.payment_term_id",
								RelationshipTo:   "payment_terms.id",
								JoinType:         "left",
								Columns: []tablebuilder.ColumnDefinition{
									{Name: "name", Alias: "supplier_payment_terms", TableColumn: "payment_terms.name"},
								},
							},
						},
					},
					{
						Table:            "purchase_order_statuses",
						Schema:           "procurement",
						RelationshipFrom: "purchase_orders.purchase_order_status_id",
						RelationshipTo:   "purchase_order_statuses.id",
						JoinType:         "left",
						Columns: []tablebuilder.ColumnDefinition{
							{Name: "name", Alias: "status_name", TableColumn: "purchase_order_statuses.name"},
							{Name: "description", Alias: "status_description", TableColumn: "purchase_order_statuses.description"},
						},
					},
					{
						Table:            "warehouses",
						Schema:           "inventory",
						RelationshipFrom: "purchase_orders.delivery_warehouse_id",
						RelationshipTo:   "warehouses.id",
						JoinType:         "left",
						Columns: []tablebuilder.ColumnDefinition{
							{Name: "name", Alias: "warehouse_name", TableColumn: "warehouses.name"},
							{Name: "code", Alias: "warehouse_code", TableColumn: "warehouses.code"},
						},
					},
					{
						Table:            "users",
						Schema:           "core",
						RelationshipFrom: "purchase_orders.requested_by",
						RelationshipTo:   "users.id",
						JoinType:         "left",
						Columns: []tablebuilder.ColumnDefinition{
							{Name: "username", Alias: "requested_by_username", TableColumn: "users.username"},
							{Name: "first_name", Alias: "requested_by_first_name", TableColumn: "users.first_name"},
							{Name: "last_name", Alias: "requested_by_last_name", TableColumn: "users.last_name"},
						},
					},
					{
						Table:            "users",
						Schema:           "core",
						RelationshipFrom: "purchase_orders.approved_by",
						RelationshipTo:   "users.id",
						JoinType:         "left",
						Alias:            "approver",
						Columns: []tablebuilder.ColumnDefinition{
							{Name: "username", Alias: "approved_by_username", TableColumn: "approver.username"},
							{Name: "first_name", Alias: "approved_by_first_name", TableColumn: "approver.first_name"},
							{Name: "last_name", Alias: "approved_by_last_name", TableColumn: "approver.last_name"},
						},
					},
					{
						Table:            "currencies",
						Schema:           "core",
						RelationshipFrom: "purchase_orders.currency_id",
						RelationshipTo:   "currencies.id",
						JoinType:         "left",
						Columns: []tablebuilder.ColumnDefinition{
							{Name: "code", Alias: "currency_code", TableColumn: "currencies.code"},
							{Name: "symbol", Alias: "currency_symbol", TableColumn: "currencies.symbol"},
						},
					},
				},
				ClientComputedColumns: []tablebuilder.ComputedColumn{
					{
						Name:       "requested_by_full_name",
						Expression: "requested_by_first_name + ' ' + requested_by_last_name",
					},
					{
						Name:       "approved_by_full_name",
						Expression: "approved_by_first_name ? (approved_by_first_name + ' ' + approved_by_last_name) : 'N/A'",
					},
					{
						Name:       "formatted_total",
						Expression: "currency_code + ' ' + total_amount.toFixed(2)",
					},
					{
						Name:       "delivery_status",
						Expression: "hasValue(actual_delivery_date) ? 'delivered' : (isOverdue(expected_delivery_date) ? 'overdue' : 'pending')",
					},
				},
			},
			Sort: []tablebuilder.Sort{
				{
					Column:    "order_date",
					Direction: "desc",
				},
			},
			Rows: 50,
		},
	},
	VisualSettings: tablebuilder.VisualSettings{
		Columns: map[string]tablebuilder.ColumnConfig{
			"expected_delivery_date": {
				Name:   "expected_delivery_date",
				Header: "Expected Delivery",
				Width:  150,
				Type:   "datetime",
				Hidden: true,
				Format: &tablebuilder.FormatConfig{
					Type:   "datetime",
					Format: "yyyy-MM-dd",
				},
			},
			"actual_delivery_date": {
				Name:   "actual_delivery_date",
				Header: "Actual Delivery",
				Width:  150,
				Type:   "datetime",
				Hidden: true,
				Format: &tablebuilder.FormatConfig{
					Type:   "datetime",
					Format: "yyyy-MM-dd",
				},
			},
			"total_amount": {
				Name:   "total_amount",
				Header: "Total",
				Width:  100,
				Type:   "number",
				Hidden: true,
				Format: &tablebuilder.FormatConfig{
					Type:      "currency",
					Precision: 2,
				},
			},
			"purchase_orders.order_number": {
				Name:       "purchase_orders.order_number",
				Header:     "PO Number",
				Width:      150,
				Type:       "string",
				Sortable:   true,
				Filterable: true,
				Link: &tablebuilder.LinkConfig{
					URL:         "/procurement/purchase-orders/{purchase_orders.id}",
					LabelColumn: "purchase_orders.order_number",
				},
			},
			"supplier_name": {
				Name:       "supplier_name",
				Header:     "Supplier",
				Width:      200,
				Type:       "string",
				Sortable:   true,
				Filterable: true,
				Link: &tablebuilder.LinkConfig{
					URL:         "/procurement/suppliers/{purchase_orders.supplier_id}",
					LabelColumn: "supplier_name",
				},
			},
			"status_name": {
				Name:       "status_name",
				Header:     "Status",
				Width:      120,
				Type:       "status",
				Filterable: true,
			},
			"warehouse_name": {
				Name:       "warehouse_name",
				Header:     "Warehouse",
				Width:      200,
				Type:       "string",
				Sortable:   true,
				Filterable: true,
				Link: &tablebuilder.LinkConfig{
					URL:         "/inventory/warehouses/{purchase_orders.delivery_warehouse_id}",
					LabelColumn: "warehouse_name",
				},
			},
			"purchase_orders.order_date": {
				Name:     "purchase_orders.order_date",
				Header:   "Order Date",
				Width:    130,
				Type:     "datetime",
				Sortable: true,
				Format: &tablebuilder.FormatConfig{
					Type:   "datetime",
					Format: "yyyy-MM-dd",
				},
			},
			"purchase_orders.expected_delivery_date": {
				Name:     "purchase_orders.expected_delivery_date",
				Header:   "Expected Delivery",
				Width:    150,
				Type:     "datetime",
				Sortable: true,
				Format: &tablebuilder.FormatConfig{
					Type:   "datetime",
					Format: "yyyy-MM-dd",
				},
			},
			"formatted_total": {
				Name:   "formatted_total",
				Header: "Total Amount",
				Width:  130,
				Type:   "computed",
			},
			"delivery_status": {
				Name:         "delivery_status",
				Header:       "Delivery Status",
				Width:        130,
				Type:         "status",
				CellTemplate: "status",
				Filterable:   true,
			},
			"requested_by_full_name": {
				Name:       "requested_by_full_name",
				Header:     "Requested By",
				Width:      150,
				Type:       "computed",
				Filterable: true,
				Link: &tablebuilder.LinkConfig{
					URL:         "/core/users/{purchase_orders.requested_by}",
					LabelColumn: "requested_by_full_name",
				},
			},
			"purchase_orders.id": {
				Name:   "purchase_orders.id",
				Header: "PO ID",
				Type:   "uuid",
				Hidden: true,
			},
			"purchase_orders.supplier_id": {
				Name:   "purchase_orders.supplier_id",
				Header: "Supplier ID",
				Type:   "uuid",
				Hidden: true,
			},
			"purchase_orders.purchase_order_status_id": {
				Name:       "purchase_orders.purchase_order_status_id",
				Header:     "Status",
				Type:       "lookup",
				Hidden:     true,
				Filterable: true,
				Lookup: &tablebuilder.LookupConfig{
					Entity:      "procurement.purchase_order_statuses",
					LabelColumn: "purchase_order_statuses.name",
					ValueColumn: "purchase_order_statuses.id",
				},
			},
			"purchase_orders.delivery_warehouse_id": {
				Name:   "purchase_orders.delivery_warehouse_id",
				Header: "Warehouse ID",
				Type:   "uuid",
				Hidden: true,
			},
			"purchase_orders.actual_delivery_date": {
				Name:   "purchase_orders.actual_delivery_date",
				Header: "Actual Delivery",
				Width:  150,
				Type:   "datetime",
				Format: &tablebuilder.FormatConfig{
					Type:   "date",
					Format: "MM-dd-yyyy",
				},
			},
			"purchase_orders.subtotal": {
				Name:   "purchase_orders.subtotal",
				Header: "Subtotal",
				Width:  100,
				Type:   "number",
			},
			"purchase_orders.tax_amount": {
				Name:   "purchase_orders.tax_amount",
				Header: "Tax Amount",
				Width:  100,
				Type:   "number",
			},
			"purchase_orders.shipping_cost": {
				Name:   "purchase_orders.shipping_cost",
				Header: "Shipping Cost",
				Width:  100,
				Type:   "number",
			},
			"purchase_orders.total_amount": {
				Name:   "purchase_orders.total_amount",
				Header: "Total Amount",
				Width:  100,
				Type:   "number",
			},
			"currency_code": {
				Name:   "currency_code",
				Header: "Currency",
				Width:  80,
				Type:   "string",
			},
			"currency_symbol": {
				Name:   "currency_symbol",
				Header: "Symbol",
				Width:  60,
				Type:   "string",
			},
			"purchase_orders.requested_by": {
				Name:   "purchase_orders.requested_by",
				Header: "Requested By ID",
				Type:   "uuid",
				Hidden: true,
			},
			"purchase_orders.approved_by": {
				Name:   "purchase_orders.approved_by",
				Header: "Approved By",
				Type:   "uuid",
				Hidden: true,
			},
			"purchase_orders.approved_date": {
				Name:   "purchase_orders.approved_date",
				Header: "Approved Date",
				Width:  150,
				Type:   "datetime",
				Format: &tablebuilder.FormatConfig{
					Type:   "date",
					Format: "MM-dd-yyyy",
				},
			},
			"purchase_orders.notes": {
				Name:   "purchase_orders.notes",
				Header: "Notes",
				Width:  200,
				Type:   "string",
			},
			"purchase_orders.created_date": {
				Name:   "purchase_orders.created_date",
				Header: "Created Date",
				Width:  150,
				Type:   "datetime",
				Format: &tablebuilder.FormatConfig{
					Type:   "date",
					Format: "MM-dd-yyyy",
				},
			},
			"purchase_orders.updated_date": {
				Name:   "purchase_orders.updated_date",
				Header: "Updated Date",
				Width:  150,
				Type:   "datetime",
				Format: &tablebuilder.FormatConfig{
					Type:   "date",
					Format: "MM-dd-yyyy",
				},
			},
			"supplier_payment_terms": {
				Name:   "supplier_payment_terms",
				Header: "Payment Terms",
				Width:  120,
				Type:   "string",
			},
			"supplier_lead_time_days": {
				Name:   "supplier_lead_time_days",
				Header: "Lead Time Days",
				Width:  100,
				Type:   "number",
			},
			"status_description": {
				Name:   "status_description",
				Header: "Status Description",
				Width:  200,
				Type:   "string",
			},
			"warehouse_code": {
				Name:   "warehouse_code",
				Header: "Warehouse Code",
				Width:  100,
				Type:   "string",
			},
			"requested_by_username": {
				Name:   "requested_by_username",
				Header: "Requestor Username",
				Width:  150,
				Type:   "string",
			},
			"requested_by_first_name": {
				Name:   "requested_by_first_name",
				Header: "Requestor First Name",
				Width:  150,
				Type:   "string",
			},
			"requested_by_last_name": {
				Name:   "requested_by_last_name",
				Header: "Requestor Last Name",
				Width:  150,
				Type:   "string",
			},
			"approved_by_username": {
				Name:   "approved_by_username",
				Header: "Approver Username",
				Width:  150,
				Type:   "string",
			},
			"approved_by_first_name": {
				Name:   "approved_by_first_name",
				Header: "Approver First Name",
				Width:  150,
				Type:   "string",
			},
			"approved_by_last_name": {
				Name:   "approved_by_last_name",
				Header: "Approver Last Name",
				Width:  150,
				Type:   "string",
			},
			"approved_by_full_name": {
				Name:   "approved_by_full_name",
				Header: "Approved By",
				Width:  150,
				Type:   "computed",
			},
		},
		Pagination: &tablebuilder.PaginationConfig{
			Enabled:         true,
			PageSizes:       []int{10, 25, 50, 100},
			DefaultPageSize: 25,
		},
	},
	Permissions: tablebuilder.Permissions{
		Roles:   []string{"admin", "procurement"},
		Actions: []string{"view", "create", "edit", "export"},
	},
}


var PurchaseOrderLineItemTableConfig = &tablebuilder.Config{
	Title:           "Purchase Order Line Items",
	WidgetType:      "table",
	Visualization:   "table",
	PositionX:       0,
	PositionY:       0,
	Width:           12,
	Height:          8,
	RefreshInterval: 300,
	RefreshMode:     "polling",
	DataSource: []tablebuilder.DataSource{
		{
			Type:   "query",
			Source: "purchase_order_line_items",
			Schema: "procurement",
			Select: tablebuilder.SelectConfig{
				Columns: []tablebuilder.ColumnDefinition{
					{Name: "id", Alias: "line_item_id", TableColumn: "purchase_order_line_items.id"},
					{Name: "purchase_order_id", Alias: "line_item_purchase_order_id", TableColumn: "purchase_order_line_items.purchase_order_id"},
					{Name: "supplier_product_id", Alias: "line_item_supplier_product_id", TableColumn: "purchase_order_line_items.supplier_product_id"},
					{Name: "quantity_ordered", Alias: "line_item_quantity_ordered", TableColumn: "purchase_order_line_items.quantity_ordered"},
					{Name: "quantity_received", Alias: "line_item_quantity_received", TableColumn: "purchase_order_line_items.quantity_received"},
					{Name: "quantity_cancelled", Alias: "line_item_quantity_cancelled", TableColumn: "purchase_order_line_items.quantity_cancelled"},
					{Name: "unit_cost", Alias: "line_item_unit_cost", TableColumn: "purchase_order_line_items.unit_cost"},
					{Name: "discount", Alias: "line_item_discount", TableColumn: "purchase_order_line_items.discount"},
					{Name: "line_total", Alias: "line_item_line_total", TableColumn: "purchase_order_line_items.line_total"},
					{Name: "line_item_status_id", Alias: "line_item_line_item_status_id", TableColumn: "purchase_order_line_items.line_item_status_id"},
					{Name: "expected_delivery_date", Alias: "line_item_expected_delivery_date", TableColumn: "purchase_order_line_items.expected_delivery_date"},
					{Name: "actual_delivery_date", Alias: "line_item_actual_delivery_date", TableColumn: "purchase_order_line_items.actual_delivery_date"},
					{Name: "notes", Alias: "line_item_notes", TableColumn: "purchase_order_line_items.notes"},
					{Name: "created_by", Alias: "line_item_created_by", TableColumn: "purchase_order_line_items.created_by"},
					{Name: "created_date", Alias: "line_item_created_date", TableColumn: "purchase_order_line_items.created_date"},
					{Name: "updated_by", Alias: "line_item_updated_by", TableColumn: "purchase_order_line_items.updated_by"},
					{Name: "updated_date", Alias: "line_item_updated_date", TableColumn: "purchase_order_line_items.updated_date"},
				},
				ForeignTables: []tablebuilder.ForeignTable{
					{
						Table:            "purchase_orders",
						Schema:           "procurement",
						RelationshipFrom: "purchase_order_line_items.purchase_order_id",
						RelationshipTo:   "purchase_orders.id",
						JoinType:         "left",
						Columns: []tablebuilder.ColumnDefinition{
							{Name: "order_number", Alias: "po_number", TableColumn: "purchase_orders.order_number"},
							{Name: "supplier_id", Alias: "po_supplier_id", TableColumn: "purchase_orders.supplier_id"},
							{Name: "order_date", Alias: "po_order_date", TableColumn: "purchase_orders.order_date"},
						},
						ForeignTables: []tablebuilder.ForeignTable{
							{
								Table:            "suppliers",
								Schema:           "procurement",
								RelationshipFrom: "purchase_orders.supplier_id",
								RelationshipTo:   "suppliers.id",
								JoinType:         "left",
								Columns: []tablebuilder.ColumnDefinition{
									{Name: "name", Alias: "supplier_name", TableColumn: "suppliers.name"},
								},
							},
						},
					},
					{
						Table:            "supplier_products",
						Schema:           "procurement",
						RelationshipFrom: "purchase_order_line_items.supplier_product_id",
						RelationshipTo:   "supplier_products.id",
						JoinType:         "left",
						Columns: []tablebuilder.ColumnDefinition{
							{Name: "supplier_part_number", Alias: "supplier_part_number", TableColumn: "supplier_products.supplier_part_number"},
							{Name: "product_id", Alias: "product_id", TableColumn: "supplier_products.product_id"},
						},
						ForeignTables: []tablebuilder.ForeignTable{
							{
								Table:            "products",
								Schema:           "products",
								RelationshipFrom: "supplier_products.product_id",
								RelationshipTo:   "products.id",
								JoinType:         "left",
								Columns: []tablebuilder.ColumnDefinition{
									{Name: "name", Alias: "product_name", TableColumn: "products.name"},
									{Name: "sku", Alias: "product_sku", TableColumn: "products.sku"},
								},
							},
						},
					},
					{
						Table:            "purchase_order_line_item_statuses",
						Schema:           "procurement",
						RelationshipFrom: "purchase_order_line_items.line_item_status_id",
						RelationshipTo:   "purchase_order_line_item_statuses.id",
						JoinType:         "left",
						Columns: []tablebuilder.ColumnDefinition{
							{Name: "name", Alias: "line_item_status_name", TableColumn: "purchase_order_line_item_statuses.name"},
						},
					},
					{
						Table:            "users",
						Schema:           "core",
						RelationshipFrom: "purchase_order_line_items.created_by",
						RelationshipTo:   "users.id",
						JoinType:         "left",
						Columns: []tablebuilder.ColumnDefinition{
							{Name: "username", Alias: "created_by_username", TableColumn: "users.username"},
						},
					},
					{
						Table:            "users",
						Schema:           "core",
						Alias:            "updated_by_user",
						RelationshipFrom: "purchase_order_line_items.updated_by",
						RelationshipTo:   "updated_by_user.id",
						JoinType:         "left",
						Columns: []tablebuilder.ColumnDefinition{
							{Name: "username", Alias: "updated_by_username", TableColumn: "updated_by_user.username"},
						},
					},
				},
				ClientComputedColumns: []tablebuilder.ComputedColumn{
					{
						Name:       "quantity_pending",
						Expression: "line_item_quantity_ordered - line_item_quantity_received - line_item_quantity_cancelled",
					},
					{
						Name:       "fulfillment_percentage",
						Expression: "line_item_quantity_ordered > 0 ? ((line_item_quantity_received / line_item_quantity_ordered) * 100).toFixed(1) : '0.0'",
					},
					{
						Name:       "line_status",
						Expression: "line_item_quantity_received >= line_item_quantity_ordered ? 'complete' : line_item_quantity_cancelled > 0 ? 'partial' : 'pending'",
					},
				},
			},
			Sort: []tablebuilder.Sort{
				{
					Column:    "line_item_created_date",
					Direction: "desc",
				},
			},
			Rows: 50,
		},
	},
	VisualSettings: tablebuilder.VisualSettings{
		Columns: map[string]tablebuilder.ColumnConfig{
			"po_number": {
				Name:       "po_number",
				Header:     "PO Number",
				Width:      150,
				Type:       "string",
				Sortable:   true,
				Filterable: true,
				Link: &tablebuilder.LinkConfig{
					URL:         "/procurement/purchase-order-line-items/{line_item_id}",
					LabelColumn: "po_number",
				},
			},
			"supplier_name": {
				Name:       "supplier_name",
				Header:     "Supplier",
				Width:      180,
				Type:       "string",
				Filterable: true,
				Link: &tablebuilder.LinkConfig{
					URL:         "/procurement/suppliers/{po_supplier_id}",
					LabelColumn: "supplier_name",
				},
			},
			"product_name": {
				Name:       "product_name",
				Header:     "Product",
				Width:      200,
				Type:       "string",
				Filterable: true,
				Link: &tablebuilder.LinkConfig{
					URL:         "/products/products/{product_id}",
					LabelColumn: "product_name",
				},
			},
			"product_sku": {
				Name:       "product_sku",
				Header:     "SKU",
				Width:      120,
				Type:       "string",
				Filterable: true,
			},
			"supplier_part_number": {
				Name:       "supplier_part_number",
				Header:     "Supplier Part #",
				Width:      150,
				Type:       "string",
				Filterable: true,
			},
			"line_item_quantity_ordered": {
				Name:       "line_item_quantity_ordered",
				Header:     "Qty Ordered",
				Width:      110,
				Type:       "number",
				Sortable:   true,
				Filterable: true,
			},
			"line_item_quantity_received": {
				Name:       "line_item_quantity_received",
				Header:     "Qty Received",
				Width:      120,
				Type:       "number",
				Sortable:   true,
				Filterable: true,
			},
			"quantity_pending": {
				Name:   "quantity_pending",
				Header: "Qty Pending",
				Width:  110,
				Type:   "computed",
			},
			"fulfillment_percentage": {
				Name:   "fulfillment_percentage",
				Header: "Fulfillment %",
				Width:  120,
				Type:   "computed",
			},
			"line_item_unit_cost": {
				Name:     "line_item_unit_cost",
				Header:   "Unit Cost",
				Width:    100,
				Type:     "number",
				Sortable: true,
				Format: &tablebuilder.FormatConfig{
					Type:   "currency",
					Format: "USD",
				},
			},
			"line_item_line_total": {
				Name:     "line_item_line_total",
				Header:   "Line Total",
				Width:    110,
				Type:     "number",
				Sortable: true,
				Format: &tablebuilder.FormatConfig{
					Type:   "currency",
					Format: "USD",
				},
			},
			"line_item_status_name": {
				Name:       "line_item_status_name",
				Header:     "Status",
				Width:      120,
				Type:       "status",
				Filterable: true,
			},
			"line_item_expected_delivery_date": {
				Name:     "line_item_expected_delivery_date",
				Header:   "Expected Delivery",
				Width:    150,
				Type:     "datetime",
				Sortable: true,
				Format: &tablebuilder.FormatConfig{
					Type:   "datetime",
					Format: "yyyy-MM-dd",
				},
			},
			"created_by_username": {
				Name:       "created_by_username",
				Header:     "Created By",
				Width:      130,
				Type:       "string",
				Filterable: true,
				Link: &tablebuilder.LinkConfig{
					URL:         "/core/users/{line_item_created_by}",
					LabelColumn: "created_by_username",
				},
			},
			"line_item_id": {
				Name:   "line_item_id",
				Header: "Line Item ID",
				Type:   "uuid",
				Hidden: true,
			},
			"line_item_purchase_order_id": {
				Name:       "line_item_purchase_order_id",
				Header:     "Purchase Order",
				Type:       "lookup",
				Hidden:     true,
				Filterable: true,
				Lookup: &tablebuilder.LookupConfig{
					Entity:      "procurement.purchase_orders",
					LabelColumn: "purchase_orders.order_number",
					ValueColumn: "purchase_orders.id",
				},
			},
			"line_item_supplier_product_id": {
				Name:       "line_item_supplier_product_id",
				Header:     "Supplier Product",
				Type:       "lookup",
				Hidden:     true,
				Filterable: true,
				Lookup: &tablebuilder.LookupConfig{
					Entity:      "procurement.supplier_products",
					LabelColumn: "supplier_products.supplier_part_number",
					ValueColumn: "supplier_products.id",
				},
			},
			"line_item_quantity_cancelled": {
				Name:   "line_item_quantity_cancelled",
				Header: "Qty Cancelled",
				Width:  110,
				Type:   "number",
			},
			"line_item_discount": {
				Name:   "line_item_discount",
				Header: "Discount",
				Width:  100,
				Type:   "number",
			},
			"line_item_line_item_status_id": {
				Name:       "line_item_line_item_status_id",
				Header:     "Status",
				Type:       "lookup",
				Hidden:     true,
				Filterable: true,
				Lookup: &tablebuilder.LookupConfig{
					Entity:      "procurement.purchase_order_line_item_statuses",
					LabelColumn: "purchase_order_line_item_statuses.name",
					ValueColumn: "purchase_order_line_item_statuses.id",
				},
			},
			"line_item_actual_delivery_date": {
				Name:   "line_item_actual_delivery_date",
				Header: "Actual Delivery",
				Width:  150,
				Type:   "datetime",
				Format: &tablebuilder.FormatConfig{
					Type:   "date",
					Format: "MM-dd-yyyy",
				},
			},
			"line_item_notes": {
				Name:   "line_item_notes",
				Header: "Notes",
				Width:  200,
				Type:   "string",
			},
			"line_item_created_by": {
				Name:   "line_item_created_by",
				Header: "Created By",
				Type:   "uuid",
				Hidden: true,
			},
			"line_item_created_date": {
				Name:   "line_item_created_date",
				Header: "Created Date",
				Width:  150,
				Type:   "datetime",
				Format: &tablebuilder.FormatConfig{
					Type:   "date",
					Format: "MM-dd-yyyy",
				},
			},
			"line_item_updated_by": {
				Name:   "line_item_updated_by",
				Header: "Updated By",
				Type:   "uuid",
				Hidden: true,
			},
			"updated_by_username": {
				Name:       "updated_by_username",
				Header:     "Updated By",
				Width:      130,
				Type:       "string",
				Filterable: true,
				Link: &tablebuilder.LinkConfig{
					URL:         "/core/users/{line_item_updated_by}",
					LabelColumn: "updated_by_username",
				},
			},
			"line_item_updated_date": {
				Name:   "line_item_updated_date",
				Header: "Updated Date",
				Width:  150,
				Type:   "datetime",
				Format: &tablebuilder.FormatConfig{
					Type:   "date",
					Format: "MM-dd-yyyy",
				},
			},
			"po_supplier_id": {
				Name:       "po_supplier_id",
				Header:     "Supplier",
				Type:       "lookup",
				Hidden:     true,
				Filterable: true,
				Lookup: &tablebuilder.LookupConfig{
					Entity:      "procurement.suppliers",
					LabelColumn: "suppliers.name",
					ValueColumn: "suppliers.id",
				},
			},
			"po_order_date": {
				Name:   "po_order_date",
				Header: "PO Order Date",
				Width:  150,
				Type:   "datetime",
				Format: &tablebuilder.FormatConfig{
					Type:   "date",
					Format: "MM-dd-yyyy",
				},
			},
			"product_id": {
				Name:       "product_id",
				Header:     "Product",
				Type:       "lookup",
				Hidden:     true,
				Filterable: true,
				Lookup: &tablebuilder.LookupConfig{
					Entity:      "products.products",
					LabelColumn: "products.name",
					ValueColumn: "products.id",
				},
			},
			"line_status": {
				Name:   "line_status",
				Header: "Line Status",
				Width:  100,
				Type:   "computed",
			},
		},
		Pagination: &tablebuilder.PaginationConfig{
			Enabled:         true,
			PageSizes:       []int{10, 25, 50, 100},
			DefaultPageSize: 25,
		},
	},
	Permissions: tablebuilder.Permissions{
		Roles:   []string{"admin", "procurement"},
		Actions: []string{"view", "edit", "export"},
	},
}


// Open Approvals - Purchase orders awaiting approval
var ProcurementOpenApprovalsTableConfig = &tablebuilder.Config{
	Title:           "Open Approvals",
	WidgetType:      "table",
	Visualization:   "table",
	PositionX:       0,
	PositionY:       0,
	Width:           12,
	Height:          8,
	RefreshInterval: 300,
	RefreshMode:     "polling",
	DataSource: []tablebuilder.DataSource{
		{
			Type:   "query",
			Source: "purchase_orders",
			Schema: "procurement",
			Select: tablebuilder.SelectConfig{
				Columns: []tablebuilder.ColumnDefinition{
					{Name: "id", TableColumn: "purchase_orders.id"},
					{Name: "order_number", TableColumn: "purchase_orders.order_number"},
					{Name: "supplier_id", TableColumn: "purchase_orders.supplier_id"},
					{Name: "purchase_order_status_id", TableColumn: "purchase_orders.purchase_order_status_id"},
					{Name: "delivery_warehouse_id", TableColumn: "purchase_orders.delivery_warehouse_id"},
					{Name: "order_date", Alias: "order_date", TableColumn: "purchase_orders.order_date"},
					{Name: "expected_delivery_date", TableColumn: "purchase_orders.expected_delivery_date"},
					{Name: "subtotal", TableColumn: "purchase_orders.subtotal"},
					{Name: "tax_amount", TableColumn: "purchase_orders.tax_amount"},
					{Name: "shipping_cost", TableColumn: "purchase_orders.shipping_cost"},
					{Name: "total_amount", Alias: "total_amount", TableColumn: "purchase_orders.total_amount"},
					{Name: "requested_by", TableColumn: "purchase_orders.requested_by"},
					{Name: "notes", TableColumn: "purchase_orders.notes"},
					{Name: "created_date", TableColumn: "purchase_orders.created_date"},
				},
				ForeignTables: []tablebuilder.ForeignTable{
					{
						Table:            "suppliers",
						Schema:           "procurement",
						RelationshipFrom: "purchase_orders.supplier_id",
						RelationshipTo:   "suppliers.id",
						JoinType:         "left",
						Columns: []tablebuilder.ColumnDefinition{
							{Name: "name", Alias: "supplier_name", TableColumn: "suppliers.name"},
							{Name: "lead_time_days", Alias: "supplier_lead_time_days", TableColumn: "suppliers.lead_time_days"},
						},
						ForeignTables: []tablebuilder.ForeignTable{
							{
								Table:            "payment_terms",
								Schema:           "core",
								RelationshipFrom: "suppliers.payment_term_id",
								RelationshipTo:   "payment_terms.id",
								JoinType:         "left",
								Columns: []tablebuilder.ColumnDefinition{
									{Name: "name", Alias: "supplier_payment_terms", TableColumn: "payment_terms.name"},
								},
							},
						},
					},
					{
						Table:            "purchase_order_statuses",
						Schema:           "procurement",
						RelationshipFrom: "purchase_orders.purchase_order_status_id",
						RelationshipTo:   "purchase_order_statuses.id",
						JoinType:         "left",
						Columns: []tablebuilder.ColumnDefinition{
							{Name: "name", Alias: "status_name", TableColumn: "purchase_order_statuses.name"},
							{Name: "description", Alias: "status_description", TableColumn: "purchase_order_statuses.description"},
						},
					},
					{
						Table:            "warehouses",
						Schema:           "inventory",
						RelationshipFrom: "purchase_orders.delivery_warehouse_id",
						RelationshipTo:   "warehouses.id",
						JoinType:         "left",
						Columns: []tablebuilder.ColumnDefinition{
							{Name: "name", Alias: "warehouse_name", TableColumn: "warehouses.name"},
							{Name: "code", Alias: "warehouse_code", TableColumn: "warehouses.code"},
						},
					},
					{
						Table:            "users",
						Schema:           "core",
						RelationshipFrom: "purchase_orders.requested_by",
						RelationshipTo:   "users.id",
						JoinType:         "left",
						Columns: []tablebuilder.ColumnDefinition{
							{Name: "username", Alias: "requested_by_username", TableColumn: "users.username"},
							{Name: "first_name", Alias: "requested_by_first_name", TableColumn: "users.first_name"},
							{Name: "last_name", Alias: "requested_by_last_name", TableColumn: "users.last_name"},
						},
					},
					{
						Table:            "currencies",
						Schema:           "core",
						RelationshipFrom: "purchase_orders.currency_id",
						RelationshipTo:   "currencies.id",
						JoinType:         "left",
						Columns: []tablebuilder.ColumnDefinition{
							{Name: "code", Alias: "currency_code", TableColumn: "currencies.code"},
							{Name: "symbol", Alias: "currency_symbol", TableColumn: "currencies.symbol"},
						},
					},
				},
				ClientComputedColumns: []tablebuilder.ComputedColumn{
					{
						Name:       "requested_by_full_name",
						Expression: "requested_by_first_name + ' ' + requested_by_last_name",
					},
					{
						Name:       "formatted_total",
						Expression: "currency_code + ' ' + total_amount.toFixed(2)",
					},
					{
						Name:       "days_pending",
						Expression: "daysSince(order_date)",
					},
				},
			},
			Filters: []tablebuilder.Filter{
				{
					Column:   "approved_by",
					Operator: "is_null",
					Value:    nil,
				},
			},
			Sort: []tablebuilder.Sort{
				{
					Column:    "order_date",
					Direction: "desc",
				},
			},
			Rows: 50,
		},
	},
	VisualSettings: tablebuilder.VisualSettings{
		Columns: map[string]tablebuilder.ColumnConfig{
			"order_date": {
				Name:   "order_date",
				Header: "Order Date",
				Width:  130,
				Type:   "datetime",
				Hidden: true,
				Format: &tablebuilder.FormatConfig{
					Type:   "datetime",
					Format: "yyyy-MM-dd",
				},
			},
			"total_amount": {
				Name:   "total_amount",
				Header: "Total",
				Width:  100,
				Type:   "number",
				Hidden: true,
				Format: &tablebuilder.FormatConfig{
					Type:      "currency",
					Precision: 2,
				},
			},
			"purchase_orders.order_number": {
				Name:       "purchase_orders.order_number",
				Header:     "PO Number",
				Width:      150,
				Type:       "string",
				Sortable:   true,
				Filterable: true,
				Link: &tablebuilder.LinkConfig{
					URL:         "/procurement/purchase-orders/{purchase_orders.id}/approve",
					LabelColumn: "purchase_orders.order_number",
				},
			},
			"supplier_name": {
				Name:       "supplier_name",
				Header:     "Supplier",
				Width:      200,
				Type:       "string",
				Sortable:   true,
				Filterable: true,
			},
			"status_name": {
				Name:       "status_name",
				Header:     "Status",
				Width:      120,
				Type:       "status",
				Filterable: true,
			},
			"warehouse_name": {
				Name:       "warehouse_name",
				Header:     "Delivery Warehouse",
				Width:      180,
				Type:       "string",
				Filterable: true,
			},
			"purchase_orders.order_date": {
				Name:     "purchase_orders.order_date",
				Header:   "Order Date",
				Width:    130,
				Type:     "datetime",
				Sortable: true,
				Format: &tablebuilder.FormatConfig{
					Type:   "datetime",
					Format: "yyyy-MM-dd",
				},
			},
			"purchase_orders.expected_delivery_date": {
				Name:     "purchase_orders.expected_delivery_date",
				Header:   "Expected Delivery",
				Width:    150,
				Type:     "datetime",
				Sortable: true,
				Format: &tablebuilder.FormatConfig{
					Type:   "datetime",
					Format: "yyyy-MM-dd",
				},
			},
			"formatted_total": {
				Name:   "formatted_total",
				Header: "Total Amount",
				Width:  130,
				Type:   "computed",
			},
			"days_pending": {
				Name:   "days_pending",
				Header: "Days Pending",
				Width:  120,
				Type:   "computed",
			},
			"requested_by_full_name": {
				Name:       "requested_by_full_name",
				Header:     "Requested By",
				Width:      150,
				Type:       "computed",
				Filterable: true,
				Link: &tablebuilder.LinkConfig{
					URL:         "/core/users/{purchase_orders.requested_by}",
					LabelColumn: "requested_by_full_name",
				},
			},
			"purchase_orders.id": {
				Name:   "purchase_orders.id",
				Header: "PO ID",
				Type:   "uuid",
				Hidden: true,
			},
			"purchase_orders.supplier_id": {
				Name:       "purchase_orders.supplier_id",
				Header:     "Supplier",
				Type:       "lookup",
				Hidden:     true,
				Filterable: true,
				Lookup: &tablebuilder.LookupConfig{
					Entity:      "procurement.suppliers",
					LabelColumn: "suppliers.name",
					ValueColumn: "suppliers.id",
				},
			},
			"purchase_orders.purchase_order_status_id": {
				Name:       "purchase_orders.purchase_order_status_id",
				Header:     "Status",
				Type:       "lookup",
				Hidden:     true,
				Filterable: true,
				Lookup: &tablebuilder.LookupConfig{
					Entity:      "procurement.purchase_order_statuses",
					LabelColumn: "purchase_order_statuses.name",
					ValueColumn: "purchase_order_statuses.id",
				},
			},
			"purchase_orders.delivery_warehouse_id": {
				Name:       "purchase_orders.delivery_warehouse_id",
				Header:     "Warehouse",
				Type:       "lookup",
				Hidden:     true,
				Filterable: true,
				Lookup: &tablebuilder.LookupConfig{
					Entity:      "inventory.warehouses",
					LabelColumn: "warehouses.name",
					ValueColumn: "warehouses.id",
				},
			},
			"purchase_orders.subtotal": {
				Name:   "purchase_orders.subtotal",
				Header: "Subtotal",
				Width:  100,
				Type:   "number",
			},
			"purchase_orders.tax_amount": {
				Name:   "purchase_orders.tax_amount",
				Header: "Tax Amount",
				Width:  100,
				Type:   "number",
			},
			"purchase_orders.shipping_cost": {
				Name:   "purchase_orders.shipping_cost",
				Header: "Shipping Cost",
				Width:  100,
				Type:   "number",
			},
			"purchase_orders.total_amount": {
				Name:   "purchase_orders.total_amount",
				Header: "Total Amount",
				Width:  100,
				Type:   "number",
			},
			"currency_code": {
				Name:   "currency_code",
				Header: "Currency",
				Width:  80,
				Type:   "string",
			},
			"currency_symbol": {
				Name:   "currency_symbol",
				Header: "Symbol",
				Width:  60,
				Type:   "string",
			},
			"purchase_orders.requested_by": {
				Name:   "purchase_orders.requested_by",
				Header: "Requested By",
				Type:   "uuid",
				Hidden: true,
			},
			"purchase_orders.notes": {
				Name:   "purchase_orders.notes",
				Header: "Notes",
				Width:  200,
				Type:   "string",
			},
			"purchase_orders.created_date": {
				Name:   "purchase_orders.created_date",
				Header: "Created Date",
				Width:  150,
				Type:   "datetime",
				Format: &tablebuilder.FormatConfig{
					Type:   "date",
					Format: "MM-dd-yyyy",
				},
			},
			"supplier_payment_terms": {
				Name:   "supplier_payment_terms",
				Header: "Payment Terms",
				Width:  120,
				Type:   "string",
			},
			"supplier_lead_time_days": {
				Name:   "supplier_lead_time_days",
				Header: "Lead Time Days",
				Width:  100,
				Type:   "number",
			},
			"status_description": {
				Name:   "status_description",
				Header: "Status Description",
				Width:  200,
				Type:   "string",
			},
			"warehouse_code": {
				Name:   "warehouse_code",
				Header: "Warehouse Code",
				Width:  100,
				Type:   "string",
			},
			"requested_by_username": {
				Name:   "requested_by_username",
				Header: "Requestor Username",
				Width:  150,
				Type:   "string",
			},
			"requested_by_first_name": {
				Name:   "requested_by_first_name",
				Header: "Requestor First Name",
				Width:  150,
				Type:   "string",
			},
			"requested_by_last_name": {
				Name:   "requested_by_last_name",
				Header: "Requestor Last Name",
				Width:  150,
				Type:   "string",
			},
		},
		Pagination: &tablebuilder.PaginationConfig{
			Enabled:         true,
			PageSizes:       []int{10, 25, 50, 100},
			DefaultPageSize: 25,
		},
	},
	Permissions: tablebuilder.Permissions{
		Roles:   []string{"admin", "procurement", "manager"},
		Actions: []string{"view", "approve", "reject"},
	},
}


// Closed Approvals - Purchase orders that have been approved
var ProcurementClosedApprovalsTableConfig = &tablebuilder.Config{
	Title:           "Closed Approvals",
	WidgetType:      "table",
	Visualization:   "table",
	PositionX:       0,
	PositionY:       0,
	Width:           12,
	Height:          8,
	RefreshInterval: 300,
	RefreshMode:     "polling",
	DataSource: []tablebuilder.DataSource{
		{
			Type:   "query",
			Source: "purchase_orders",
			Schema: "procurement",
			Select: tablebuilder.SelectConfig{
				Columns: []tablebuilder.ColumnDefinition{
					{Name: "id", TableColumn: "purchase_orders.id"},
					{Name: "order_number", TableColumn: "purchase_orders.order_number"},
					{Name: "supplier_id", TableColumn: "purchase_orders.supplier_id"},
					{Name: "purchase_order_status_id", TableColumn: "purchase_orders.purchase_order_status_id"},
					{Name: "delivery_warehouse_id", TableColumn: "purchase_orders.delivery_warehouse_id"},
					{Name: "order_date", TableColumn: "purchase_orders.order_date"},
					{Name: "expected_delivery_date", Alias: "expected_delivery_date", TableColumn: "purchase_orders.expected_delivery_date"},
					{Name: "actual_delivery_date", Alias: "actual_delivery_date", TableColumn: "purchase_orders.actual_delivery_date"},
					{Name: "subtotal", TableColumn: "purchase_orders.subtotal"},
					{Name: "tax_amount", TableColumn: "purchase_orders.tax_amount"},
					{Name: "shipping_cost", TableColumn: "purchase_orders.shipping_cost"},
					{Name: "total_amount", Alias: "total_amount", TableColumn: "purchase_orders.total_amount"},
					{Name: "requested_by", TableColumn: "purchase_orders.requested_by"},
					{Name: "approved_by", TableColumn: "purchase_orders.approved_by"},
					{Name: "approved_date", TableColumn: "purchase_orders.approved_date"},
					{Name: "notes", TableColumn: "purchase_orders.notes"},
					{Name: "created_date", TableColumn: "purchase_orders.created_date"},
				},
				ForeignTables: []tablebuilder.ForeignTable{
					{
						Table:            "suppliers",
						Schema:           "procurement",
						RelationshipFrom: "purchase_orders.supplier_id",
						RelationshipTo:   "suppliers.id",
						JoinType:         "left",
						Columns: []tablebuilder.ColumnDefinition{
							{Name: "name", Alias: "supplier_name", TableColumn: "suppliers.name"},
							{Name: "lead_time_days", Alias: "supplier_lead_time_days", TableColumn: "suppliers.lead_time_days"},
						},
						ForeignTables: []tablebuilder.ForeignTable{
							{
								Table:            "payment_terms",
								Schema:           "core",
								RelationshipFrom: "suppliers.payment_term_id",
								RelationshipTo:   "payment_terms.id",
								JoinType:         "left",
								Columns: []tablebuilder.ColumnDefinition{
									{Name: "name", Alias: "supplier_payment_terms", TableColumn: "payment_terms.name"},
								},
							},
						},
					},
					{
						Table:            "purchase_order_statuses",
						Schema:           "procurement",
						RelationshipFrom: "purchase_orders.purchase_order_status_id",
						RelationshipTo:   "purchase_order_statuses.id",
						JoinType:         "left",
						Columns: []tablebuilder.ColumnDefinition{
							{Name: "name", Alias: "status_name", TableColumn: "purchase_order_statuses.name"},
							{Name: "description", Alias: "status_description", TableColumn: "purchase_order_statuses.description"},
						},
					},
					{
						Table:            "warehouses",
						Schema:           "inventory",
						RelationshipFrom: "purchase_orders.delivery_warehouse_id",
						RelationshipTo:   "warehouses.id",
						JoinType:         "left",
						Columns: []tablebuilder.ColumnDefinition{
							{Name: "name", Alias: "warehouse_name", TableColumn: "warehouses.name"},
							{Name: "code", Alias: "warehouse_code", TableColumn: "warehouses.code"},
						},
					},
					{
						Table:            "users",
						Schema:           "core",
						RelationshipFrom: "purchase_orders.requested_by",
						RelationshipTo:   "users.id",
						JoinType:         "left",
						Columns: []tablebuilder.ColumnDefinition{
							{Name: "username", Alias: "requested_by_username", TableColumn: "users.username"},
							{Name: "first_name", Alias: "requested_by_first_name", TableColumn: "users.first_name"},
							{Name: "last_name", Alias: "requested_by_last_name", TableColumn: "users.last_name"},
						},
					},
					{
						Table:            "users",
						Schema:           "core",
						RelationshipFrom: "purchase_orders.approved_by",
						RelationshipTo:   "users.id",
						JoinType:         "left",
						Alias:            "approver",
						Columns: []tablebuilder.ColumnDefinition{
							{Name: "username", Alias: "approved_by_username", TableColumn: "approver.username"},
							{Name: "first_name", Alias: "approved_by_first_name", TableColumn: "approver.first_name"},
							{Name: "last_name", Alias: "approved_by_last_name", TableColumn: "approver.last_name"},
						},
					},
					{
						Table:            "currencies",
						Schema:           "core",
						RelationshipFrom: "purchase_orders.currency_id",
						RelationshipTo:   "currencies.id",
						JoinType:         "left",
						Columns: []tablebuilder.ColumnDefinition{
							{Name: "code", Alias: "currency_code", TableColumn: "currencies.code"},
							{Name: "symbol", Alias: "currency_symbol", TableColumn: "currencies.symbol"},
						},
					},
				},
				ClientComputedColumns: []tablebuilder.ComputedColumn{
					{
						Name:       "requested_by_full_name",
						Expression: "requested_by_first_name + ' ' + requested_by_last_name",
					},
					{
						Name:       "approved_by_full_name",
						Expression: "approved_by_first_name + ' ' + approved_by_last_name",
					},
					{
						Name:       "formatted_total",
						Expression: "currency_code + ' ' + total_amount.toFixed(2)",
					},
					{
						Name:       "delivery_status",
						Expression: "hasValue(actual_delivery_date) ? 'delivered' : (isOverdue(expected_delivery_date) ? 'overdue' : 'pending')",
					},
				},
			},
			Filters: []tablebuilder.Filter{
				{
					Column:   "approved_by",
					Operator: "is_not_null",
					Value:    nil,
				},
			},
			Sort: []tablebuilder.Sort{
				{
					Column:    "approved_date",
					Direction: "desc",
				},
			},
			Rows: 50,
		},
	},
	VisualSettings: tablebuilder.VisualSettings{
		Columns: map[string]tablebuilder.ColumnConfig{
			"expected_delivery_date": {
				Name:   "expected_delivery_date",
				Header: "Expected Delivery",
				Width:  150,
				Type:   "datetime",
				Hidden: true,
				Format: &tablebuilder.FormatConfig{
					Type:   "datetime",
					Format: "yyyy-MM-dd",
				},
			},
			"actual_delivery_date": {
				Name:   "actual_delivery_date",
				Header: "Actual Delivery",
				Width:  150,
				Type:   "datetime",
				Hidden: true,
				Format: &tablebuilder.FormatConfig{
					Type:   "datetime",
					Format: "yyyy-MM-dd",
				},
			},
			"total_amount": {
				Name:   "total_amount",
				Header: "Total",
				Width:  100,
				Type:   "number",
				Hidden: true,
				Format: &tablebuilder.FormatConfig{
					Type:      "currency",
					Precision: 2,
				},
			},
			"purchase_orders.order_number": {
				Name:       "purchase_orders.order_number",
				Header:     "PO Number",
				Width:      150,
				Type:       "string",
				Sortable:   true,
				Filterable: true,
				Link: &tablebuilder.LinkConfig{
					URL:         "/procurement/purchase-orders/{purchase_orders.id}",
					LabelColumn: "purchase_orders.order_number",
				},
			},
			"supplier_name": {
				Name:       "supplier_name",
				Header:     "Supplier",
				Width:      200,
				Type:       "string",
				Sortable:   true,
				Filterable: true,
			},
			"status_name": {
				Name:       "status_name",
				Header:     "Status",
				Width:      120,
				Type:       "status",
				Filterable: true,
			},
			"warehouse_name": {
				Name:       "warehouse_name",
				Header:     "Delivery Warehouse",
				Width:      180,
				Type:       "string",
				Filterable: true,
			},
			"purchase_orders.order_date": {
				Name:     "purchase_orders.order_date",
				Header:   "Order Date",
				Width:    130,
				Type:     "datetime",
				Sortable: true,
				Format: &tablebuilder.FormatConfig{
					Type:   "datetime",
					Format: "yyyy-MM-dd",
				},
			},
			"purchase_orders.approved_date": {
				Name:     "purchase_orders.approved_date",
				Header:   "Approved Date",
				Width:    130,
				Type:     "datetime",
				Sortable: true,
				Format: &tablebuilder.FormatConfig{
					Type:   "datetime",
					Format: "yyyy-MM-dd",
				},
			},
			"purchase_orders.expected_delivery_date": {
				Name:     "purchase_orders.expected_delivery_date",
				Header:   "Expected Delivery",
				Width:    150,
				Type:     "datetime",
				Sortable: true,
				Format: &tablebuilder.FormatConfig{
					Type:   "datetime",
					Format: "yyyy-MM-dd",
				},
			},
			"formatted_total": {
				Name:   "formatted_total",
				Header: "Total Amount",
				Width:  130,
				Type:   "computed",
			},
			"delivery_status": {
				Name:       "delivery_status",
				Header:     "Delivery Status",
				Width:      130,
				Type:       "computed",
				Filterable: true,
			},
			"requested_by_full_name": {
				Name:       "requested_by_full_name",
				Header:     "Requested By",
				Width:      150,
				Type:       "computed",
				Filterable: true,
				Link: &tablebuilder.LinkConfig{
					URL:         "/core/users/{purchase_orders.requested_by}",
					LabelColumn: "requested_by_full_name",
				},
			},
			"approved_by_full_name": {
				Name:       "approved_by_full_name",
				Header:     "Approved By",
				Width:      150,
				Type:       "computed",
				Filterable: true,
				Link: &tablebuilder.LinkConfig{
					URL:         "/core/users/{purchase_orders.approved_by}",
					LabelColumn: "approved_by_full_name",
				},
			},
			"purchase_orders.id": {
				Name:   "purchase_orders.id",
				Header: "PO ID",
				Type:   "uuid",
				Hidden: true,
			},
			"purchase_orders.supplier_id": {
				Name:       "purchase_orders.supplier_id",
				Header:     "Supplier",
				Type:       "lookup",
				Hidden:     true,
				Filterable: true,
				Lookup: &tablebuilder.LookupConfig{
					Entity:      "procurement.suppliers",
					LabelColumn: "suppliers.name",
					ValueColumn: "suppliers.id",
				},
			},
			"purchase_orders.purchase_order_status_id": {
				Name:       "purchase_orders.purchase_order_status_id",
				Header:     "Status",
				Type:       "lookup",
				Hidden:     true,
				Filterable: true,
				Lookup: &tablebuilder.LookupConfig{
					Entity:      "procurement.purchase_order_statuses",
					LabelColumn: "purchase_order_statuses.name",
					ValueColumn: "purchase_order_statuses.id",
				},
			},
			"purchase_orders.delivery_warehouse_id": {
				Name:       "purchase_orders.delivery_warehouse_id",
				Header:     "Warehouse",
				Type:       "lookup",
				Hidden:     true,
				Filterable: true,
				Lookup: &tablebuilder.LookupConfig{
					Entity:      "inventory.warehouses",
					LabelColumn: "warehouses.name",
					ValueColumn: "warehouses.id",
				},
			},
			"purchase_orders.actual_delivery_date": {
				Name:   "purchase_orders.actual_delivery_date",
				Header: "Actual Delivery",
				Width:  150,
				Type:   "datetime",
				Format: &tablebuilder.FormatConfig{
					Type:   "date",
					Format: "MM-dd-yyyy",
				},
			},
			"purchase_orders.subtotal": {
				Name:   "purchase_orders.subtotal",
				Header: "Subtotal",
				Width:  100,
				Type:   "number",
			},
			"purchase_orders.tax_amount": {
				Name:   "purchase_orders.tax_amount",
				Header: "Tax Amount",
				Width:  100,
				Type:   "number",
			},
			"purchase_orders.shipping_cost": {
				Name:   "purchase_orders.shipping_cost",
				Header: "Shipping Cost",
				Width:  100,
				Type:   "number",
			},
			"purchase_orders.total_amount": {
				Name:   "purchase_orders.total_amount",
				Header: "Total Amount",
				Width:  100,
				Type:   "number",
			},
			"currency_code": {
				Name:   "currency_code",
				Header: "Currency",
				Width:  80,
				Type:   "string",
			},
			"currency_symbol": {
				Name:   "currency_symbol",
				Header: "Symbol",
				Width:  60,
				Type:   "string",
			},
			"purchase_orders.requested_by": {
				Name:   "purchase_orders.requested_by",
				Header: "Requested By",
				Type:   "uuid",
				Hidden: true,
			},
			"purchase_orders.approved_by": {
				Name:   "purchase_orders.approved_by",
				Header: "Approved By",
				Type:   "uuid",
				Hidden: true,
			},
			"purchase_orders.notes": {
				Name:   "purchase_orders.notes",
				Header: "Notes",
				Width:  200,
				Type:   "string",
			},
			"purchase_orders.created_date": {
				Name:   "purchase_orders.created_date",
				Header: "Created Date",
				Width:  150,
				Type:   "datetime",
				Format: &tablebuilder.FormatConfig{
					Type:   "date",
					Format: "MM-dd-yyyy",
				},
			},
			"supplier_payment_terms": {
				Name:   "supplier_payment_terms",
				Header: "Payment Terms",
				Width:  120,
				Type:   "string",
			},
			"supplier_lead_time_days": {
				Name:   "supplier_lead_time_days",
				Header: "Lead Time Days",
				Width:  100,
				Type:   "number",
			},
			"status_description": {
				Name:   "status_description",
				Header: "Status Description",
				Width:  200,
				Type:   "string",
			},
			"warehouse_code": {
				Name:   "warehouse_code",
				Header: "Warehouse Code",
				Width:  100,
				Type:   "string",
			},
			"requested_by_username": {
				Name:   "requested_by_username",
				Header: "Requestor Username",
				Width:  150,
				Type:   "string",
			},
			"requested_by_first_name": {
				Name:   "requested_by_first_name",
				Header: "Requestor First Name",
				Width:  150,
				Type:   "string",
			},
			"requested_by_last_name": {
				Name:   "requested_by_last_name",
				Header: "Requestor Last Name",
				Width:  150,
				Type:   "string",
			},
			"approved_by_username": {
				Name:   "approved_by_username",
				Header: "Approver Username",
				Width:  150,
				Type:   "string",
			},
			"approved_by_first_name": {
				Name:   "approved_by_first_name",
				Header: "Approver First Name",
				Width:  150,
				Type:   "string",
			},
			"approved_by_last_name": {
				Name:   "approved_by_last_name",
				Header: "Approver Last Name",
				Width:  150,
				Type:   "string",
			},
		},
		Pagination: &tablebuilder.PaginationConfig{
			Enabled:         true,
			PageSizes:       []int{10, 25, 50, 100},
			DefaultPageSize: 25,
		},
	},
	Permissions: tablebuilder.Permissions{
		Roles:   []string{"admin", "procurement", "manager"},
		Actions: []string{"view", "export"},
	},
}
