package dbtest

import (
	"github.com/timmaaaz/ichor/business/domain/core/pagebus"
	"github.com/timmaaaz/ichor/business/sdk/tablebuilder"
)

// =============================================================================
// PAGE CONFIGS
// =============================================================================
const sortOrder = iota

var allPages = []pagebus.NewPage{
	// DASHBOARD MODULE
	{
		Path:       "/dashboard",
		Name:       "Main Dashboard",
		Module:     "dashboard",
		Icon:       "material-symbols:space-dashboard",
		SortOrder:  1,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/dashboard/analytics",
		Name:       "Analytics Dashboard",
		Module:     "dashboard",
		Icon:       "material-symbols:analytics",
		SortOrder:  2,
		IsActive:   true,
		ShowInMenu: true,
	},

	// SALES MODULE
	{
		Path:       "/sales",
		Name:       "Sales Dashboard",
		Module:     "sales",
		Icon:       "material-symbols:point-of-sale",
		SortOrder:  3,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/sales/orders",
		Name:       "Order Management",
		Module:     "sales",
		Icon:       "material-symbols:receipt-long",
		SortOrder:  4,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/sales/orders/new",
		Name:       "New Order Form",
		Module:     "sales",
		Icon:       "material-symbols:add-shopping-cart",
		SortOrder:  5,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/sales/customers",
		Name:       "Customer Management",
		Module:     "sales",
		Icon:       "material-symbols:group",
		SortOrder:  6,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/sales/customers/new",
		Name:       "New Customer Form",
		Module:     "sales",
		Icon:       "material-symbols:person-add",
		SortOrder:  7,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/sales/customers/:id",
		Name:       "Customer Details",
		Module:     "sales",
		Icon:       "material-symbols:person",
		SortOrder:  33,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/sales/orders/:id",
		Name:       "Order Details",
		Module:     "sales",
		Icon:       "material-symbols:receipt",
		SortOrder:  34,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/sales/reports",
		Name:       "Sales Reports",
		Module:     "sales",
		Icon:       "material-symbols:assessment",
		SortOrder:  8,
		IsActive:   true,
		ShowInMenu: true,
	},

	// INVENTORY MODULE
	{
		Path:       "/inventory",
		Name:       "Inventory Dashboard",
		Module:     "inventory",
		Icon:       "material-symbols:inventory-2",
		SortOrder:  9,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/inventory/items",
		Name:       "Item Management",
		Module:     "inventory",
		Icon:       "material-symbols:category",
		SortOrder:  10,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/inventory/items/new",
		Name:       "New Inventory Item",
		Module:     "inventory",
		Icon:       "material-symbols:add-box",
		SortOrder:  35,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/inventory/items/:id",
		Name:       "Inventory Item Details",
		Module:     "inventory",
		Icon:       "material-symbols:inventory",
		SortOrder:  36,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/inventory/warehouses",
		Name:       "Warehouse Management",
		Module:     "inventory",
		Icon:       "material-symbols:warehouse",
		SortOrder:  11,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/inventory/warehouses/new",
		Name:       "New Warehouse",
		Module:     "inventory",
		Icon:       "material-symbols:add-business",
		SortOrder:  37,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/inventory/warehouses/:id",
		Name:       "Warehouse Details",
		Module:     "inventory",
		Icon:       "material-symbols:domain",
		SortOrder:  38,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/inventory/transfers",
		Name:       "Transfer Orders",
		Module:     "inventory",
		Icon:       "material-symbols:sync-alt",
		SortOrder:  12,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/inventory/transfers/new",
		Name:       "New Transfer Order",
		Module:     "inventory",
		Icon:       "material-symbols:add-circle",
		SortOrder:  39,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/inventory/transfers/:id",
		Name:       "Transfer Order Details",
		Module:     "inventory",
		Icon:       "material-symbols:compare-arrows",
		SortOrder:  40,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/inventory/adjustments",
		Name:       "Stock Adjustments",
		Module:     "inventory",
		Icon:       "material-symbols:tune",
		SortOrder:  13,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/inventory/adjustments/new",
		Name:       "New Stock Adjustment",
		Module:     "inventory",
		Icon:       "material-symbols:edit-note",
		SortOrder:  41,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/inventory/adjustments/:id",
		Name:       "Stock Adjustment Details",
		Module:     "inventory",
		Icon:       "material-symbols:analytics",
		SortOrder:  42,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/inventory/reports",
		Name:       "Inventory Reports",
		Module:     "inventory",
		Icon:       "material-symbols:summarize",
		SortOrder:  14,
		IsActive:   true,
		ShowInMenu: true,
	},

	// PROCUREMENT MODULE
	{
		Path:       "/procurement",
		Name:       "Procurement Dashboard",
		Module:     "procurement",
		Icon:       "material-symbols:shopping-cart",
		SortOrder:  15,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/procurement/suppliers",
		Name:       "Supplier Management",
		Module:     "procurement",
		Icon:       "material-symbols:local-shipping",
		SortOrder:  16,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/procurement/suppliers/new",
		Name:       "New Supplier",
		Module:     "procurement",
		Icon:       "material-symbols:add-business",
		SortOrder:  43,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/procurement/suppliers/:id",
		Name:       "Supplier Details",
		Module:     "procurement",
		Icon:       "material-symbols:business-center",
		SortOrder:  44,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/procurement/orders",
		Name:       "Purchase Orders",
		Module:     "procurement",
		Icon:       "material-symbols:shopping-bag",
		SortOrder:  17,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/procurement/orders/new",
		Name:       "New Purchase Order",
		Module:     "procurement",
		Icon:       "material-symbols:note-add",
		SortOrder:  45,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/procurement/orders/:id",
		Name:       "Purchase Order Details",
		Module:     "procurement",
		Icon:       "material-symbols:description",
		SortOrder:  46,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/procurement/approvals",
		Name:       "Approval Queue",
		Module:     "procurement",
		Icon:       "material-symbols:check-circle",
		SortOrder:  18,
		IsActive:   true,
		ShowInMenu: true,
	},

	// ASSETS MODULE
	{
		Path:       "/assets",
		Name:       "Asset Dashboard",
		Module:     "assets",
		Icon:       "material-symbols:apartment",
		SortOrder:  19,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/assets/list",
		Name:       "Asset List",
		Module:     "assets",
		Icon:       "material-symbols:list",
		SortOrder:  20,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/assets/list/new",
		Name:       "New Asset",
		Module:     "assets",
		Icon:       "material-symbols:add-circle",
		SortOrder:  47,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/assets/list/:id",
		Name:       "Asset Details",
		Module:     "assets",
		Icon:       "material-symbols:apartment",
		SortOrder:  48,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/assets/requests",
		Name:       "Asset Requests",
		Module:     "assets",
		Icon:       "material-symbols:request-quote",
		SortOrder:  21,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/assets/maintenance",
		Name:       "Maintenance Schedule",
		Module:     "assets",
		Icon:       "material-symbols:build",
		SortOrder:  22,
		IsActive:   true,
		ShowInMenu: true,
	},

	// HR MODULE
	{
		Path:       "/hr",
		Name:       "HR Dashboard",
		Module:     "hr",
		Icon:       "material-symbols:badge",
		SortOrder:  23,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/hr/employees",
		Name:       "Employee Directory",
		Module:     "hr",
		Icon:       "material-symbols:groups",
		SortOrder:  24,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/hr/employees/new",
		Name:       "New Employee",
		Module:     "hr",
		Icon:       "material-symbols:person-add",
		SortOrder:  49,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/hr/employees/:id",
		Name:       "Employee Details",
		Module:     "hr",
		Icon:       "material-symbols:badge",
		SortOrder:  50,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/hr/onboarding",
		Name:       "Onboarding",
		Module:     "hr",
		Icon:       "material-symbols:how-to-reg",
		SortOrder:  25,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/hr/offices",
		Name:       "Office Management",
		Module:     "hr",
		Icon:       "material-symbols:business",
		SortOrder:  26,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/hr/offices/new",
		Name:       "New Office",
		Module:     "hr",
		Icon:       "material-symbols:add-business",
		SortOrder:  51,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/hr/offices/:id",
		Name:       "Office Details",
		Module:     "hr",
		Icon:       "material-symbols:domain",
		SortOrder:  52,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/hr/reports",
		Name:       "HR Reports",
		Module:     "hr",
		Icon:       "material-symbols:bar-chart",
		SortOrder:  27,
		IsActive:   true,
		ShowInMenu: true,
	},

	// ADMIN MODULE
	{
		Path:       "/admin",
		Name:       "Admin Dashboard",
		Module:     "admin",
		Icon:       "material-symbols:admin-panel-settings",
		SortOrder:  28,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/admin/users",
		Name:       "User Management",
		Module:     "admin",
		Icon:       "material-symbols:manage-accounts",
		SortOrder:  29,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/admin/users/new",
		Name:       "New User",
		Module:     "admin",
		Icon:       "material-symbols:person-add",
		SortOrder:  53,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/admin/users/:id",
		Name:       "User Details",
		Module:     "admin",
		Icon:       "material-symbols:account-circle",
		SortOrder:  54,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/admin/roles",
		Name:       "Role Management",
		Module:     "admin",
		Icon:       "material-symbols:security",
		SortOrder:  30,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/admin/roles/new",
		Name:       "New Role",
		Module:     "admin",
		Icon:       "material-symbols:add-moderator",
		SortOrder:  55,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/admin/roles/:id",
		Name:       "Role Details",
		Module:     "admin",
		Icon:       "material-symbols:admin-panel-settings",
		SortOrder:  56,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/admin/config",
		Name:       "System Configuration",
		Module:     "admin",
		Icon:       "material-symbols:settings-applications",
		SortOrder:  31,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/admin/audit",
		Name:       "Audit Logs",
		Module:     "admin",
		Icon:       "material-symbols:history",
		SortOrder:  32,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/admin/config/pages",
		Name:       "Page Configs",
		Module:     "admin",
		Icon:       "material-symbols:page-info",
		SortOrder:  57,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/admin/config/tables",
		Name:       "Table Configs",
		Module:     "admin",
		Icon:       "material-symbols:table",
		SortOrder:  58,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/admin/config/forms",
		Name:       "Form Configs",
		Module:     "admin",
		Icon:       "material-symbols:edit-document",
		SortOrder:  59,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/admin/config/import-export",
		Name:       "Import/Export",
		Module:     "admin",
		Icon:       "material-symbols:import-export",
		SortOrder:  60,
		IsActive:   true,
		ShowInMenu: true,
	},
	{
		Path:       "/admin/config/page-configs/new",
		Name:       "New Page Config",
		Module:     "admin",
		Icon:       "material-symbols:add-circle",
		SortOrder:  61,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/admin/config/page-configs/:id",
		Name:       "Edit Page Config",
		Module:     "admin",
		Icon:       "material-symbols:edit",
		SortOrder:  62,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/admin/config/page-content/:id",
		Name:       "Page Content Editor",
		Module:     "admin",
		Icon:       "material-symbols:edit-note",
		SortOrder:  63,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/admin/config/page-actions/:page_config_id",
		Name:       "Page Actions Editor",
		Module:     "admin",
		Icon:       "material-symbols:touch-app",
		SortOrder:  64,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/admin/config/table-configs/new",
		Name:       "New Table Config",
		Module:     "admin",
		Icon:       "material-symbols:add-circle",
		SortOrder:  65,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/admin/config/table-configs/:id",
		Name:       "Edit Table Config",
		Module:     "admin",
		Icon:       "material-symbols:edit",
		SortOrder:  66,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/admin/config/forms/new",
		Name:       "New Form Config",
		Module:     "admin",
		Icon:       "material-symbols:add-circle",
		SortOrder:  67,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/admin/config/forms/:id",
		Name:       "Edit Form Config",
		Module:     "admin",
		Icon:       "material-symbols:edit",
		SortOrder:  68,
		IsActive:   true,
		ShowInMenu: false,
	},
	{
		Path:       "/admin/config/:id",
		Name:       "Edit Config",
		Module:     "admin",
		Icon:       "material-symbols:edit",
		SortOrder:  69,
		IsActive:   true,
		ShowInMenu: false,
	},
}

// =============================================================================
// ADMIN MODULE CONFIGS
// =============================================================================

// Users Management Page Config
var adminUsersPageConfig = &tablebuilder.Config{
	Title:           "User Management",
	WidgetType:      "table",
	Visualization:   "table",
	PositionX:       0,
	PositionY:       0,
	Width:           12,
	Height:          8,
	RefreshInterval: 300,
	RefreshMode:     "polling",
	DataSource: []tablebuilder.DataSource{
		{
			Type:   "query",
			Source: "users",
			Schema: "core",
			Select: tablebuilder.SelectConfig{
				Columns: []tablebuilder.ColumnDefinition{
					{Name: "id", TableColumn: "users.id"},
					{Name: "username", TableColumn: "users.username"},
					{Name: "first_name", TableColumn: "users.first_name"},
					{Name: "last_name", TableColumn: "users.last_name"},
					{Name: "email", TableColumn: "users.email"},
					{Name: "enabled", TableColumn: "users.enabled"},
					{Name: "date_hired", TableColumn: "users.date_hired"},
					{Name: "created_date", TableColumn: "users.created_date"},
				},
				ForeignTables: []tablebuilder.ForeignTable{
					{
						Table:            "titles",
						Schema:           "hr",
						RelationshipFrom: "users.title_id",
						RelationshipTo:   "titles.id",
						JoinType:         "left",
						Columns: []tablebuilder.ColumnDefinition{
							{Name: "name", Alias: "title_name", TableColumn: "titles.name"},
						},
					},
					{
						Table:            "offices",
						Schema:           "hr",
						RelationshipFrom: "users.office_id",
						RelationshipTo:   "offices.id",
						JoinType:         "left",
						Columns: []tablebuilder.ColumnDefinition{
							{Name: "name", Alias: "office_name", TableColumn: "offices.name"},
						},
					},
					{
						Table:            "user_approval_status",
						Schema:           "hr",
						RelationshipFrom: "users.user_approval_status_id",
						RelationshipTo:   "user_approval_status.id",
						JoinType:         "left",
						Columns: []tablebuilder.ColumnDefinition{
							{Name: "name", Alias: "approval_status_name", TableColumn: "user_approval_status.name"},
						},
					},
				},
				ClientComputedColumns: []tablebuilder.ComputedColumn{
					{
						Name:       "full_name",
						Expression: "first_name + ' ' + last_name",
					},
					{
						Name:       "days_employed",
						Expression: "date_hired ? Math.floor((new Date() - new Date(date_hired)) / (1000 * 60 * 60 * 24)) : null",
					},
				},
			},
			Sort: []tablebuilder.Sort{
				{
					Column:    "last_name",
					Direction: "asc",
				},
				{
					Column:    "first_name",
					Direction: "asc",
				},
			},
			Rows: 50,
		},
	},
	VisualSettings: tablebuilder.VisualSettings{
		Columns: map[string]tablebuilder.ColumnConfig{
			"full_name": {
				Name:       "full_name",
				Header:     "Name",
				Width:      200,
				Sortable:   true,
				Filterable: true,
			},
			"username": {
				Name:       "username",
				Header:     "Username",
				Width:      150,
				Sortable:   true,
				Filterable: true,
			},
			"email": {
				Name:       "email",
				Header:     "Email",
				Width:      250,
				Filterable: true,
			},
			"title_name": {
				Name:       "title_name",
				Header:     "Title",
				Width:      150,
				Sortable:   true,
				Filterable: true,
			},
			"office_name": {
				Name:       "office_name",
				Header:     "Office",
				Width:      150,
				Sortable:   true,
				Filterable: true,
			},
			"approval_status_name": {
				Name:       "approval_status_name",
				Header:     "Status",
				Width:      120,
				Sortable:   true,
				Filterable: true,
			},
			"enabled": {
				Name:   "enabled",
				Header: "Active",
				Width:  80,
				Align:  "center",
				Format: &tablebuilder.FormatConfig{
					Type: "boolean",
				},
			},
			"date_hired": {
				Name:     "date_hired",
				Header:   "Date Hired",
				Width:    120,
				Sortable: true,
				Format: &tablebuilder.FormatConfig{
					Type:   "date",
					Format: "2006-01-02",
				},
			},
			"days_employed": {
				Name:   "days_employed",
				Header: "Days Employed",
				Width:  120,
				Align:  "right",
				Format: &tablebuilder.FormatConfig{
					Type:      "number",
					Precision: 0,
				},
			},
			"id": {
				Name:   "id",
				Header: "Actions",
				Width:  100,
				Link: &tablebuilder.LinkConfig{
					URL:   "/admin/users/{id}",
					Label: "View",
				},
			},
		},
		ConditionalFormatting: []tablebuilder.ConditionalFormat{
			{
				Column:     "enabled",
				Condition:  "eq",
				Value:      false,
				Color:      "#757575",
				Background: "#f5f5f5",
			},
			{
				Column:     "approval_status_name",
				Condition:  "eq",
				Value:      "Pending",
				Color:      "#f57c00",
				Background: "#fff3e0",
				Icon:       "clock",
			},
		},
		Pagination: &tablebuilder.PaginationConfig{
			Enabled:         true,
			PageSizes:       []int{10, 25, 50, 100},
			DefaultPageSize: 25,
		},
	},
	Permissions: tablebuilder.Permissions{
		Roles:   []string{"admin"},
		Actions: []string{"view", "edit", "export"},
	},
}

// Roles Management Page Config
var adminRolesPageConfig = &tablebuilder.Config{
	Title:           "Role Management",
	WidgetType:      "table",
	Visualization:   "table",
	PositionX:       0,
	PositionY:       0,
	Width:           12,
	Height:          8,
	RefreshInterval: 300,
	RefreshMode:     "polling",
	DataSource: []tablebuilder.DataSource{
		{
			Type:   "query",
			Source: "roles",
			Schema: "core",
			Select: tablebuilder.SelectConfig{
				Columns: []tablebuilder.ColumnDefinition{
					{Name: "id", TableColumn: "roles.id"},
					{Name: "name", TableColumn: "roles.name"},
					{Name: "description", TableColumn: "roles.description"},
				},
			},
			Sort: []tablebuilder.Sort{
				{
					Column:    "name",
					Direction: "asc",
				},
			},
			Rows: 50,
		},
	},
	VisualSettings: tablebuilder.VisualSettings{
		Columns: map[string]tablebuilder.ColumnConfig{
			"name": {
				Name:       "name",
				Header:     "Role Name",
				Width:      200,
				Sortable:   true,
				Filterable: true,
			},
			"description": {
				Name:       "description",
				Header:     "Description",
				Width:      400,
				Filterable: true,
			},
			"id": {
				Name:   "id",
				Header: "Actions",
				Width:  100,
				Link: &tablebuilder.LinkConfig{
					URL:   "/admin/roles/{id}",
					Label: "View",
				},
			},
		},
		Pagination: &tablebuilder.PaginationConfig{
			Enabled:         true,
			PageSizes:       []int{10, 25, 50, 100},
			DefaultPageSize: 25,
		},
	},
	Permissions: tablebuilder.Permissions{
		Roles:   []string{"admin"},
		Actions: []string{"view", "edit", "delete", "export"},
	},
}

// Table Access (Permissions) Config
var adminTableAccessPageConfig = &tablebuilder.Config{
	Title:           "Table Permissions",
	WidgetType:      "table",
	Visualization:   "table",
	PositionX:       0,
	PositionY:       0,
	Width:           12,
	Height:          8,
	RefreshInterval: 300,
	RefreshMode:     "polling",
	DataSource: []tablebuilder.DataSource{
		{
			Type:   "query",
			Source: "table_access",
			Schema: "core",
			Select: tablebuilder.SelectConfig{
				Columns: []tablebuilder.ColumnDefinition{
					{Name: "id", TableColumn: "table_access.id"},
					{Name: "table_name", TableColumn: "table_access.table_name"},
					{Name: "can_create", TableColumn: "table_access.can_create"},
					{Name: "can_read", TableColumn: "table_access.can_read"},
					{Name: "can_update", TableColumn: "table_access.can_update"},
					{Name: "can_delete", TableColumn: "table_access.can_delete"},
				},
				ForeignTables: []tablebuilder.ForeignTable{
					{
						Table:            "roles",
						Schema:           "core",
						RelationshipFrom: "table_access.role_id",
						RelationshipTo:   "roles.id",
						JoinType:         "left",
						Columns: []tablebuilder.ColumnDefinition{
							{Name: "name", Alias: "role_name", TableColumn: "roles.name"},
						},
					},
				},
			},
			Sort: []tablebuilder.Sort{
				{
					Column:    "table_name",
					Direction: "asc",
				},
			},
			Rows: 100,
		},
	},
	VisualSettings: tablebuilder.VisualSettings{
		Columns: map[string]tablebuilder.ColumnConfig{
			"role_name": {
				Name:       "role_name",
				Header:     "Role",
				Width:      150,
				Sortable:   true,
				Filterable: true,
			},
			"table_name": {
				Name:       "table_name",
				Header:     "Table",
				Width:      200,
				Sortable:   true,
				Filterable: true,
			},
			"can_create": {
				Name:   "can_create",
				Header: "Create",
				Width:  80,
				Align:  "center",
				Format: &tablebuilder.FormatConfig{
					Type: "boolean",
				},
			},
			"can_read": {
				Name:   "can_read",
				Header: "Read",
				Width:  80,
				Align:  "center",
				Format: &tablebuilder.FormatConfig{
					Type: "boolean",
				},
			},
			"can_update": {
				Name:   "can_update",
				Header: "Update",
				Width:  80,
				Align:  "center",
				Format: &tablebuilder.FormatConfig{
					Type: "boolean",
				},
			},
			"can_delete": {
				Name:   "can_delete",
				Header: "Delete",
				Width:  80,
				Align:  "center",
				Format: &tablebuilder.FormatConfig{
					Type: "boolean",
				},
			},
		},
		ConditionalFormatting: []tablebuilder.ConditionalFormat{
			{
				Column:     "can_create",
				Condition:  "eq",
				Value:      true,
				Color:      "#2e7d32",
				Background: "#e8f5e9",
				Icon:       "check",
			},
			{
				Column:     "can_read",
				Condition:  "eq",
				Value:      true,
				Color:      "#2e7d32",
				Background: "#e8f5e9",
				Icon:       "check",
			},
			{
				Column:     "can_update",
				Condition:  "eq",
				Value:      true,
				Color:      "#2e7d32",
				Background: "#e8f5e9",
				Icon:       "check",
			},
			{
				Column:     "can_delete",
				Condition:  "eq",
				Value:      true,
				Color:      "#2e7d32",
				Background: "#e8f5e9",
				Icon:       "check",
			},
		},
		Pagination: &tablebuilder.PaginationConfig{
			Enabled:         true,
			PageSizes:       []int{25, 50, 100, 200},
			DefaultPageSize: 50,
		},
	},
	Permissions: tablebuilder.Permissions{
		Roles:   []string{"admin"},
		Actions: []string{"view", "edit"},
	},
}

// Audit Logs Page Config
var adminAuditPageConfig = &tablebuilder.Config{
	Title:           "Audit Logs",
	WidgetType:      "table",
	Visualization:   "table",
	PositionX:       0,
	PositionY:       0,
	Width:           12,
	Height:          8,
	RefreshInterval: 60,
	RefreshMode:     "polling",
	DataSource: []tablebuilder.DataSource{
		{
			Type:   "query",
			Source: "automation_executions",
			Schema: "workflow",
			Select: tablebuilder.SelectConfig{
				Columns: []tablebuilder.ColumnDefinition{
					{Name: "id", TableColumn: "automation_executions.id"},
					{Name: "entity_type", TableColumn: "automation_executions.entity_type"},
					{Name: "status", TableColumn: "automation_executions.status"},
					{Name: "error_message", TableColumn: "automation_executions.error_message"},
					{Name: "execution_time_ms", TableColumn: "automation_executions.execution_time_ms"},
					{Name: "executed_at", TableColumn: "automation_executions.executed_at"},
				},
				ForeignTables: []tablebuilder.ForeignTable{
					{
						Table:            "automation_rules",
						Schema:           "workflow",
						RelationshipFrom: "automation_executions.automation_rules_id",
						RelationshipTo:   "automation_rules.id",
						JoinType:         "left",
						Columns: []tablebuilder.ColumnDefinition{
							{Name: "name", Alias: "rule_name", TableColumn: "automation_rules.name"},
						},
					},
				},
			},
			Sort: []tablebuilder.Sort{
				{
					Column:    "executed_at",
					Direction: "desc",
				},
			},
			Rows: 100,
		},
	},
	VisualSettings: tablebuilder.VisualSettings{
		Columns: map[string]tablebuilder.ColumnConfig{
			"executed_at": {
				Name:     "executed_at",
				Header:   "Execution Time",
				Width:    180,
				Sortable: true,
				Format: &tablebuilder.FormatConfig{
					Type:   "datetime",
					Format: "2006-01-02 15:04:05",
				},
			},
			"rule_name": {
				Name:       "rule_name",
				Header:     "Rule",
				Width:      200,
				Sortable:   true,
				Filterable: true,
			},
			"entity_type": {
				Name:       "entity_type",
				Header:     "Entity Type",
				Width:      150,
				Sortable:   true,
				Filterable: true,
			},
			"status": {
				Name:         "status",
				Header:       "Status",
				Width:        120,
				Sortable:     true,
				Filterable:   true,
				CellTemplate: "status",
			},
			"execution_time_ms": {
				Name:     "execution_time_ms",
				Header:   "Duration (ms)",
				Width:    120,
				Align:    "right",
				Sortable: true,
				Format: &tablebuilder.FormatConfig{
					Type:      "number",
					Precision: 0,
				},
			},
			"error_message": {
				Name:   "error_message",
				Header: "Error",
				Width:  300,
			},
			"id": {
				Name:   "id",
				Header: "Details",
				Width:  100,
				Link: &tablebuilder.LinkConfig{
					URL:   "/admin/audit/{id}",
					Label: "View",
				},
			},
		},
		ConditionalFormatting: []tablebuilder.ConditionalFormat{
			{
				Column:     "status",
				Condition:  "eq",
				Value:      "success",
				Color:      "#2e7d32",
				Background: "#e8f5e9",
				Icon:       "check-circle",
			},
			{
				Column:     "status",
				Condition:  "eq",
				Value:      "failed",
				Color:      "#c62828",
				Background: "#ffebee",
				Icon:       "x-circle",
			},
			{
				Column:     "status",
				Condition:  "eq",
				Value:      "partial",
				Color:      "#f57c00",
				Background: "#fff3e0",
				Icon:       "alert-circle",
			},
		},
		Pagination: &tablebuilder.PaginationConfig{
			Enabled:         true,
			PageSizes:       []int{25, 50, 100, 200},
			DefaultPageSize: 50,
		},
	},
	Permissions: tablebuilder.Permissions{
		Roles:   []string{"admin"},
		Actions: []string{"view", "export"},
	},
}

// Table Configs Management Page Config
var adminConfigPageConfig = &tablebuilder.Config{
	Title:           "Table Configurations",
	WidgetType:      "table",
	Visualization:   "table",
	PositionX:       0,
	PositionY:       0,
	Width:           12,
	Height:          8,
	RefreshInterval: 300,
	RefreshMode:     "polling",
	DataSource: []tablebuilder.DataSource{
		{
			Type:   "query",
			Source: "table_configs",
			Schema: "config",
			Select: tablebuilder.SelectConfig{
				Columns: []tablebuilder.ColumnDefinition{
					{Name: "id", TableColumn: "table_configs.id"},
					{Name: "name", TableColumn: "table_configs.name"},
					{Name: "description", TableColumn: "table_configs.description"},
					{Name: "created_date", TableColumn: "table_configs.created_date"},
					{Name: "updated_date", TableColumn: "table_configs.updated_date"},
				},
				ForeignTables: []tablebuilder.ForeignTable{
					{
						Table:            "users",
						Alias:            "created_by_user",
						Schema:           "core",
						RelationshipFrom: "table_configs.created_by",
						RelationshipTo:   "created_by_user.id",
						JoinType:         "left",
						Columns: []tablebuilder.ColumnDefinition{
							{Name: "username", Alias: "created_by_username", TableColumn: "created_by_user.username"},
						},
					},
					{
						Table:            "users",
						Alias:            "updated_by_user",
						Schema:           "core",
						RelationshipFrom: "table_configs.updated_by",
						RelationshipTo:   "updated_by_user.id",
						JoinType:         "left",
						Columns: []tablebuilder.ColumnDefinition{
							{Name: "username", Alias: "updated_by_username", TableColumn: "updated_by_user.username"},
						},
					},
				},
			},
			Sort: []tablebuilder.Sort{
				{
					Column:    "updated_date",
					Direction: "desc",
				},
			},
			Rows: 50,
		},
	},
	VisualSettings: tablebuilder.VisualSettings{
		Columns: map[string]tablebuilder.ColumnConfig{
			"name": {
				Name:       "name",
				Header:     "Config Name",
				Width:      250,
				Sortable:   true,
				Filterable: true,
			},
			"description": {
				Name:       "description",
				Header:     "Description",
				Width:      400,
				Filterable: true,
			},
			"created_by_username": {
				Name:       "created_by_username",
				Header:     "Created By",
				Width:      150,
				Filterable: true,
			},
			"updated_by_username": {
				Name:       "updated_by_username",
				Header:     "Updated By",
				Width:      150,
				Filterable: true,
			},
			"updated_date": {
				Name:     "updated_date",
				Header:   "Last Updated",
				Width:    180,
				Sortable: true,
				Format: &tablebuilder.FormatConfig{
					Type:   "datetime",
					Format: "2006-01-02 15:04",
				},
			},
			"id": {
				Name:   "id",
				Header: "Actions",
				Width:  100,
				Link: &tablebuilder.LinkConfig{
					URL:   "/admin/config/{id}",
					Label: "View",
				},
			},
		},
		Pagination: &tablebuilder.PaginationConfig{
			Enabled:         true,
			PageSizes:       []int{10, 25, 50, 100},
			DefaultPageSize: 25,
		},
	},
	Permissions: tablebuilder.Permissions{
		Roles:   []string{"admin"},
		Actions: []string{"view", "edit", "delete", "export"},
	},
}

// =============================================================================
// FORM CONFIGS
// =============================================================================
