#!/usr/bin/env python3
"""
Manitowoc seed data generator.

Reads YAML data files + config, outputs numbered SQL files (20_*-27_*)
to the seed/ directory. All UUIDs are deterministic — same input = same output.

Usage: python3 generate.py
"""

import uuid
import yaml
import random
import os
from datetime import datetime, timedelta
from pathlib import Path
from faker import Faker

# === Constants ===
BASE_DIR = Path(__file__).parent
DATA_DIR = BASE_DIR / "data"
SEED_DIR = BASE_DIR / "seed"

# UUID namespace for deterministic generation
NAMESPACE = uuid.UUID("deadbeef-dead-beef-dead-beefdeadbeef")


def load_yaml(filename: str) -> dict:
    """Load a YAML file from the data/ directory."""
    with open(DATA_DIR / filename) as f:
        return yaml.safe_load(f)


def det_uuid(key: str) -> str:
    """Generate a deterministic UUID v5 from a string key."""
    return str(uuid.uuid5(NAMESPACE, key))


def sql_str(value) -> str:
    """Escape a value for SQL insertion."""
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    escaped = str(value).replace("'", "''")
    return f"'{escaped}'"


def sql_timestamp(dt) -> str:
    """Format a datetime for SQL insertion."""
    if isinstance(dt, str):
        return f"'{dt}'"
    return f"'{dt.isoformat()}'"


def write_sql_file(filename: str, header: str, statements: list[str]):
    """Write a SQL file with BEGIN/COMMIT wrapping."""
    path = SEED_DIR / filename
    with open(path, "w") as f:
        f.write(f"-- {header}\n")
        f.write(f"-- Generated by generate.py\n")
        f.write("BEGIN;\n\n")
        for stmt in statements:
            f.write(stmt)
            if not stmt.endswith("\n"):
                f.write("\n")
        f.write("\nCOMMIT;\n")
    print(f"  Wrote {path.name} ({len(statements)} statements)")


# === Generators (one per output file) — stubs for now ===

def generate_org(config, warehouses, known_ids):
    """Generate 20_manitowoc_org.sql — geography prereqs, warehouses, zones, locations.

    Schema notes:
    - warehouses requires street_id FK (geography.streets -> cities -> regions)
    - zones has NO code column (name + description + stage only)
    - locations use aisle/rack/shelf/bin coordinates, NOT name/code
    """
    stmts = []
    admin_id = known_ids["users"]["admin_gopher"]
    seed_date = config["seed_date"]
    geo = warehouses["geography"]

    # --- Geography prerequisites ---
    city_id = det_uuid("city:Manitowoc")
    street_id = det_uuid("street:MTW-MFG")

    stmts.append(
        f"INSERT INTO geography.cities (id, region_id, name) VALUES (\n"
        f"  '{city_id}',\n"
        f"  (SELECT id FROM geography.regions WHERE code = '{geo['region']}'),\n"
        f"  {sql_str(geo['city'])}\n"
        f");\n"
    )

    stmts.append(
        f"INSERT INTO geography.streets (id, city_id, line_1, line_2, postal_code) VALUES (\n"
        f"  '{street_id}',\n"
        f"  '{city_id}',\n"
        f"  {sql_str(geo['street']['line_1'])},\n"
        f"  NULL,\n"
        f"  {sql_str(geo['street']['postal_code'])}\n"
        f");\n"
    )

    # --- Warehouses, Zones, Locations ---
    for wh in warehouses["warehouses"]:
        wh_code = wh["code"]
        wh_id = det_uuid(f"warehouse:{wh_code}")

        stmts.append(
            f"INSERT INTO inventory.warehouses (id, code, name, street_id, is_active, created_date, updated_date, created_by, updated_by) VALUES (\n"
            f"  '{wh_id}',\n"
            f"  {sql_str(wh_code)},\n"
            f"  {sql_str(wh['name'])},\n"
            f"  '{street_id}',\n"
            f"  true,\n"
            f"  '{seed_date}', '{seed_date}',\n"
            f"  '{admin_id}', '{admin_id}'\n"
            f");\n"
        )

        for zone in wh.get("zones", []):
            zone_key = f"zone:{wh_code}:{zone['name']}"
            zone_id = det_uuid(zone_key)

            stmts.append(
                f"INSERT INTO inventory.zones (id, warehouse_id, name, description, stage, created_date, updated_date) VALUES (\n"
                f"  '{zone_id}',\n"
                f"  '{wh_id}',\n"
                f"  {sql_str(zone['name'])},\n"
                f"  {sql_str(zone.get('description'))},\n"
                f"  {sql_str(zone.get('stage'))},\n"
                f"  '{seed_date}', '{seed_date}'\n"
                f");\n"
            )

            for loc in zone.get("locations", []):
                loc_key = f"location:{wh_code}:{loc['aisle']}:{loc['rack']}:{loc['shelf']}:{loc['bin']}"
                loc_id = det_uuid(loc_key)

                stmts.append(
                    f"INSERT INTO inventory.inventory_locations (id, zone_id, warehouse_id, aisle, rack, shelf, bin, is_pick_location, is_reserve_location, max_capacity, current_utilization, created_date, updated_date) VALUES (\n"
                    f"  '{loc_id}',\n"
                    f"  '{zone_id}',\n"
                    f"  '{wh_id}',\n"
                    f"  {sql_str(loc['aisle'])},\n"
                    f"  {sql_str(loc['rack'])},\n"
                    f"  {sql_str(loc['shelf'])},\n"
                    f"  {sql_str(loc['bin'])},\n"
                    f"  {sql_str(loc.get('is_pick', False))},\n"
                    f"  {sql_str(loc.get('is_reserve', False))},\n"
                    f"  {loc.get('max_capacity', 100)},\n"
                    f"  0.0000,\n"
                    f"  '{seed_date}', '{seed_date}'\n"
                    f");\n"
                )

    write_sql_file("20_manitowoc_org.sql",
                   "Manitowoc org: geography, warehouses, zones, locations",
                   stmts)


def generate_products(config, products_data, known_ids):
    """Generate 21_manitowoc_products.sql — contact_info, brands, categories, products, UOMs, costs.

    Schema notes:
    - brands requires contact_infos_id FK (core.contact_infos)
    - products requires: description, upc_code, status, is_active, is_perishable,
      units_per_case, tracking_type (all NOT NULL)
    """
    stmts = []
    seed_date = config["seed_date"]
    street_id = det_uuid("street:MTW-MFG")

    # --- Cost parameters by inventory_type ---
    cost_ranges = {
        "raw_material":  (1, 50),
        "component":     (5, 100),
        "consumable":    (2, 20),
        "wip":           (20, 200),
        "finished_good": (100, 500),
    }
    abc_map = {
        "finished_good": "A",
        "wip":           "B",
        "component":     "B",
        "raw_material":  "C",
        "consumable":    "C",
    }

    # --- 1. Contact info for brand ---
    for brand in products_data["brands"]:
        contact_id = det_uuid(f"contact:{brand['code']}")
        stmts.append(
            f"INSERT INTO core.contact_infos (id, first_name, last_name, primary_phone_number, secondary_phone_number, email_address, street_id, delivery_address_id, available_hours_start, available_hours_end, timezone_id, preferred_contact_type, notes) VALUES (\n"
            f"  '{contact_id}',\n"
            f"  'Manitowoc', 'Relay Division',\n"
            f"  '920-555-0100', NULL,\n"
            f"  'relays@manitowoc-mfg.example.com',\n"
            f"  '{street_id}', NULL,\n"
            f"  '08:00:00', '17:00:00',\n"
            f"  (SELECT id FROM geography.timezones WHERE name = 'America/Chicago'),\n"
            f"  'email',\n"
            f"  NULL\n"
            f");\n"
        )

    # --- 2. Brands ---
    for brand in products_data["brands"]:
        brand_id = det_uuid(f"brand:{brand['code']}")
        contact_id = det_uuid(f"contact:{brand['code']}")
        stmts.append(
            f"INSERT INTO products.brands (id, name, contact_infos_id, created_date, updated_date) VALUES (\n"
            f"  '{brand_id}',\n"
            f"  {sql_str(brand['name'])},\n"
            f"  '{contact_id}',\n"
            f"  '{seed_date}', '{seed_date}'\n"
            f");\n"
        )

    # --- 3. Categories ---
    category_ids = {}
    for cat_name in products_data["categories"]:
        cat_id = det_uuid(f"category:{cat_name}")
        category_ids[cat_name] = cat_id
        stmts.append(
            f"INSERT INTO products.product_categories (id, name, description, created_date, updated_date) VALUES (\n"
            f"  '{cat_id}',\n"
            f"  {sql_str(cat_name)},\n"
            f"  {sql_str(cat_name)},\n"
            f"  '{seed_date}', '{seed_date}'\n"
            f");\n"
        )

    # Use the first brand for all products
    brand_id = det_uuid(f"brand:{products_data['brands'][0]['code']}")

    # --- 4. Products ---
    for prod in products_data["products"]:
        sku = prod["sku"]
        prod_id = det_uuid(f"product:{sku}")
        cat_id = category_ids[prod["category"]]
        inv_type = prod["inventory_type"]
        tracking_type = prod.get("tracking_type", "none")

        # units_per_case: first non-base UOM factor, or 1
        units_per_case = 1
        for uom in prod.get("uoms", []):
            if not uom.get("is_base", False):
                units_per_case = uom["factor"]
                break

        stmts.append(
            f"INSERT INTO products.products (id, sku, brand_id, category_id, name, description, model_number, upc_code, status, is_active, is_perishable, handling_instructions, units_per_case, tracking_type, inventory_type, created_date, updated_date) VALUES (\n"
            f"  '{prod_id}',\n"
            f"  {sql_str(sku)},\n"
            f"  '{brand_id}',\n"
            f"  '{cat_id}',\n"
            f"  {sql_str(prod['name'])},\n"
            f"  {sql_str('Manitowoc relay component: ' + prod['name'])},\n"
            f"  NULL,\n"
            f"  {sql_str(f'MTW-{sku}-UPC')},\n"
            f"  'active',\n"
            f"  true,\n"
            f"  false,\n"
            f"  NULL,\n"
            f"  {units_per_case},\n"
            f"  {sql_str(tracking_type)},\n"
            f"  {sql_str(inv_type)},\n"
            f"  '{seed_date}', '{seed_date}'\n"
            f");\n"
        )

    # --- 5. Product UOMs ---
    for prod in products_data["products"]:
        sku = prod["sku"]
        prod_id = det_uuid(f"product:{sku}")
        for uom in prod.get("uoms", []):
            uom_id = det_uuid(f"uom:{sku}:{uom['name']}")
            is_base = uom.get("is_base", False)
            is_approx = uom.get("is_approximate", False)
            stmts.append(
                f"INSERT INTO products.product_uoms (id, product_id, name, abbreviation, conversion_factor, is_base, is_approximate, notes, created_date, updated_date) VALUES (\n"
                f"  '{uom_id}',\n"
                f"  '{prod_id}',\n"
                f"  {sql_str(uom['name'])},\n"
                f"  {sql_str(uom['name'][:3])},\n"
                f"  {uom['factor']},\n"
                f"  {sql_str(is_base)},\n"
                f"  {sql_str(is_approx)},\n"
                f"  NULL,\n"
                f"  '{seed_date}', '{seed_date}'\n"
                f");\n"
            )

    # --- 6. Product Costs ---
    for prod in products_data["products"]:
        sku = prod["sku"]
        prod_id = det_uuid(f"product:{sku}")
        cost_id = det_uuid(f"cost:{sku}")
        inv_type = prod["inventory_type"]

        # Deterministic cost based on sku hash
        low, high = cost_ranges.get(inv_type, (5, 100))
        # Use det_uuid to derive a stable number
        cost_seed = int(det_uuid(f"cost-seed:{sku}").replace("-", ""), 16) % 10000
        purchase_cost = round(low + (high - low) * (cost_seed / 10000), 2)
        selling_price = round(purchase_cost * 1.3, 2)
        msrp = round(selling_price * 1.1, 2)
        landed_cost = round(purchase_cost * 1.05, 2)
        carrying_cost = round(purchase_cost * 0.02, 2)
        insurance_value = round(purchase_cost * 0.01, 2)
        abc = abc_map.get(inv_type, "C")

        stmts.append(
            f"INSERT INTO products.product_costs (id, product_id, purchase_cost, selling_price, currency_id, msrp, markup_percentage, landed_cost, carrying_cost, abc_classification, depreciation_value, insurance_value, effective_date, created_date, updated_date) VALUES (\n"
            f"  '{cost_id}',\n"
            f"  '{prod_id}',\n"
            f"  {purchase_cost},\n"
            f"  {selling_price},\n"
            f"  (SELECT id FROM core.currencies WHERE code = 'USD'),\n"
            f"  {msrp},\n"
            f"  0.3,\n"
            f"  {landed_cost},\n"
            f"  {carrying_cost},\n"
            f"  {sql_str(abc)},\n"
            f"  0.10,\n"
            f"  {insurance_value},\n"
            f"  '{seed_date}',\n"
            f"  '{seed_date}', '{seed_date}'\n"
            f");\n"
        )

    write_sql_file("21_manitowoc_products.sql",
                   "Manitowoc products: contact_infos, brands, categories, products, UOMs, costs",
                   stmts)


def generate_employees(config, known_ids):
    """Generate 22_manitowoc_employees.sql — placeholder users."""
    stmts = []
    seed_date = config["seed_date"]
    seed_dt = datetime.fromisoformat(seed_date)
    employee_count = config["employee_count"]
    approved_status_id = known_ids["hr_user_approval_status"]["approved"]
    password_hash = "$2a$10$1ggfMVZV6Js0ybvJufLRUOWHS5f6KneuP0XwwHpJ8L8ipdry9f2/a"

    fake = Faker()
    Faker.seed(config["random_seed"])

    for i in range(employee_count):
        emp_id = det_uuid(f"employee:{i}")
        first_name = fake.first_name()
        last_name = fake.last_name()
        username = f"{first_name.lower()}_{last_name.lower()}"
        email = f"{username}@manitowoc-mfg.example.com"

        # 10% ADMIN, 90% no role
        roles = "'{ADMIN}'" if i < (employee_count // 10) else "'{}'"""

        # date_hired: spread over 2 years before seed_date, weighted toward earlier
        # Use exponential distribution: most hires are older (tenured workforce)
        rand_val = int(det_uuid(f"hire-seed:{i}").replace("-", ""), 16) % 10000
        # Exponential weighting: earlier hires more likely
        # Map 0..1 to 0..730 days, with bias toward higher values (further in past)
        fraction = rand_val / 10000
        days_before = int(730 * (1 - fraction ** 2))  # quadratic bias toward earlier
        date_hired = (seed_dt - timedelta(days=days_before)).strftime("%Y-%m-%d")

        stmts.append(
            f"INSERT INTO core.users (id, requested_by, approved_by, user_approval_status_id, "
            f"title_id, office_id, work_phone_id, cell_phone_id, "
            f"username, first_name, last_name, email, birthday, "
            f"roles, system_roles, password_hash, enabled, "
            f"date_hired, date_requested, date_approved, "
            f"created_date, updated_date) VALUES (\n"
            f"  '{emp_id}',\n"
            f"  NULL, NULL,\n"
            f"  '{approved_status_id}',\n"
            f"  NULL, NULL, NULL, NULL,\n"
            f"  {sql_str(username)},\n"
            f"  {sql_str(first_name)},\n"
            f"  {sql_str(last_name)},\n"
            f"  {sql_str(email)},\n"
            f"  NULL,\n"
            f"  {roles}, '{{}}',\n"
            f"  {sql_str(password_hash)},\n"
            f"  true,\n"
            f"  '{date_hired}',\n"
            f"  NULL, NULL,\n"
            f"  '{seed_date}', '{seed_date}'\n"
            f");\n"
        )

    write_sql_file("22_manitowoc_employees.sql",
                   "Manitowoc employees: placeholder users",
                   stmts)


def generate_inventory(config, products_data, warehouses, known_ids):
    """Generate 23_manitowoc_inventory.sql — items, transactions, transfers, adjustments."""
    stmts = []
    seed_date = config["seed_date"]
    seed_dt = datetime.fromisoformat(seed_date)
    history_months = config["history_months"]
    transfer_count = config["transfer_count"]
    adjustment_count = config["adjustment_count"]
    admin_id = known_ids["users"]["admin_gopher"]
    employee_count = config["employee_count"]

    # --- Build location mapping by inventory_type ---
    # Map inventory_type to a zone's first location key
    wh = warehouses["warehouses"][0]
    wh_code = wh["code"]

    # Build zone-to-locations mapping
    zone_locations = {}  # zone_name -> list of location keys
    for zone in wh.get("zones", []):
        locs = []
        for loc in zone.get("locations", []):
            loc_key = f"location:{wh_code}:{loc['aisle']}:{loc['rack']}:{loc['shelf']}:{loc['bin']}"
            locs.append(loc_key)
        zone_locations[zone["name"]] = locs

    # Map inventory_type to appropriate zone locations
    type_to_zone = {
        "raw_material":  "Raw Material Storage",
        "component":     "Plastics Storage",
        "wip":           "Coil Winding Floor",
        "finished_good": "Finished Goods",
        "consumable":    "Coil Winding Floor",
    }

    def get_location_id(inv_type, sku):
        """Get a deterministic location for a product based on type."""
        zone_name = type_to_zone.get(inv_type, "Raw Material Storage")
        locs = zone_locations.get(zone_name, [])
        if not locs:
            # Fallback to first location in first zone
            first_zone = list(zone_locations.values())[0]
            locs = first_zone
        # Pick location deterministically based on sku
        idx = int(det_uuid(f"loc-pick:{sku}").replace("-", ""), 16) % len(locs)
        return det_uuid(locs[idx])

    def get_employee_id(index):
        """Get a deterministic employee UUID."""
        return det_uuid(f"employee:{index % employee_count}")

    # --- 1. Inventory Items (one per product) ---
    all_products = products_data["products"]
    for prod in all_products:
        sku = prod["sku"]
        prod_id = det_uuid(f"product:{sku}")
        inv_type = prod["inventory_type"]
        loc_id = get_location_id(inv_type, sku)
        item_id = det_uuid(f"inv-item:{sku}")
        qty = prod["initial_qty"]

        # Stock management fields
        minimum_stock = max(1, int(qty * 0.1))
        maximum_stock = max(10, int(qty * 2.0))
        reorder_point = max(1, int(qty * 0.2))
        eoq = max(1, int(qty * 0.5))
        safety_stock = max(1, int(qty * 0.15))
        avg_daily_usage = int(max(1, qty // 180))  # ~6 months, INT column

        stmts.append(
            f"INSERT INTO inventory.inventory_items (id, product_id, location_id, "
            f"quantity, reserved_quantity, allocated_quantity, "
            f"minimum_stock, maximum_stock, reorder_point, economic_order_quantity, "
            f"safety_stock, avg_daily_usage, created_date, updated_date) VALUES (\n"
            f"  '{item_id}',\n"
            f"  '{prod_id}',\n"
            f"  '{loc_id}',\n"
            f"  {qty}, 0, 0,\n"
            f"  {minimum_stock}, {maximum_stock}, {reorder_point}, {eoq},\n"
            f"  {safety_stock}, {avg_daily_usage},\n"
            f"  '{seed_date}', '{seed_date}'\n"
            f");\n"
        )

    # --- 2. Inventory Transactions (historical) ---
    txn_types = ["received", "shipped", "transferred", "adjusted"]
    history_start = seed_dt - timedelta(days=history_months * 30)

    for i in range(transfer_count):
        txn_id = det_uuid(f"inv-txn:{i}")
        # Exponential distribution: more recent = more activity
        rand_val = int(det_uuid(f"txn-time:{i}").replace("-", ""), 16) % 10000
        fraction = rand_val / 10000
        # Exponential: square the fraction so more cluster near seed_date
        days_offset = int((history_months * 30) * (1 - fraction ** 2))
        txn_date = (seed_dt - timedelta(days=days_offset))

        # Pick product deterministically
        prod_idx = int(det_uuid(f"txn-prod:{i}").replace("-", ""), 16) % len(all_products)
        prod = all_products[prod_idx]
        prod_id = det_uuid(f"product:{prod['sku']}")
        loc_id = get_location_id(prod["inventory_type"], prod["sku"])
        user_id = get_employee_id(i)

        # Pick txn type
        type_idx = int(det_uuid(f"txn-type:{i}").replace("-", ""), 16) % len(txn_types)
        txn_type = txn_types[type_idx]

        # Quantity: positive for received, variable for others
        qty_seed = int(det_uuid(f"txn-qty:{i}").replace("-", ""), 16) % 200 + 1
        if txn_type == "shipped":
            qty_seed = -qty_seed
        elif txn_type == "adjusted":
            qty_seed = qty_seed if (i % 3 == 0) else -qty_seed

        ref_num = f"TXN-{i:06d}"

        stmts.append(
            f"INSERT INTO inventory.inventory_transactions (id, product_id, location_id, "
            f"user_id, transaction_type, quantity, reference_number, transaction_date, "
            f"lot_id, created_date, updated_date) VALUES (\n"
            f"  '{txn_id}',\n"
            f"  '{prod_id}',\n"
            f"  '{loc_id}',\n"
            f"  '{user_id}',\n"
            f"  {sql_str(txn_type)},\n"
            f"  {qty_seed},\n"
            f"  {sql_str(ref_num)},\n"
            f"  {sql_timestamp(txn_date)},\n"
            f"  NULL,\n"
            f"  '{seed_date}', '{seed_date}'\n"
            f");\n"
        )

    # --- 3. Transfer Orders (manufacturing flow) ---
    # Flow zones for transfers
    flow_stages = [
        ("Receiving Dock", "Plastics Storage"),
        ("Receiving Dock", "Raw Material Storage"),
        ("Raw Material Storage", "Coil Winding Floor"),
        ("Plastics Storage", "Coil Winding Floor"),
        ("Coil Winding Floor", "Coil Riveting"),
        ("Coil Riveting", "Contact Riveting"),
        ("Contact Riveting", "Assembly Floor"),
        ("Assembly Floor", "Calibration Bench"),
        ("Calibration Bench", "QA Hold"),
        ("QA Hold", "Finished Goods"),
    ]

    for i in range(transfer_count):
        xfer_id = det_uuid(f"xfer:{i}")
        # Pick flow stage
        stage_idx = int(det_uuid(f"xfer-stage:{i}").replace("-", ""), 16) % len(flow_stages)
        from_zone, to_zone = flow_stages[stage_idx]

        from_locs = zone_locations.get(from_zone, [])
        to_locs = zone_locations.get(to_zone, [])
        if not from_locs or not to_locs:
            continue

        from_loc_id = det_uuid(from_locs[0])
        to_loc_id = det_uuid(to_locs[0])

        # Pick product
        prod_idx = int(det_uuid(f"xfer-prod:{i}").replace("-", ""), 16) % len(all_products)
        prod = all_products[prod_idx]
        prod_id = det_uuid(f"product:{prod['sku']}")

        requested_by = get_employee_id(i)
        approved_by = get_employee_id(i + 1)

        qty = int(det_uuid(f"xfer-qty:{i}").replace("-", ""), 16) % 500 + 10

        # Date with exponential distribution
        rand_val = int(det_uuid(f"xfer-time:{i}").replace("-", ""), 16) % 10000
        fraction = rand_val / 10000
        days_offset = int((history_months * 30) * (1 - fraction ** 2))
        xfer_date = seed_dt - timedelta(days=days_offset)

        # Status: recent transfers in_transit, older ones completed
        status = "in_transit" if days_offset < 7 else "completed"

        stmts.append(
            f"INSERT INTO inventory.transfer_orders (id, product_id, from_location_id, "
            f"to_location_id, requested_by, approved_by, quantity, status, "
            f"transfer_date, created_date, updated_date) VALUES (\n"
            f"  '{xfer_id}',\n"
            f"  '{prod_id}',\n"
            f"  '{from_loc_id}',\n"
            f"  '{to_loc_id}',\n"
            f"  '{requested_by}',\n"
            f"  '{approved_by}',\n"
            f"  {qty},\n"
            f"  {sql_str(status)},\n"
            f"  {sql_timestamp(xfer_date)},\n"
            f"  '{seed_date}', '{seed_date}'\n"
            f");\n"
        )

    # --- 4. Inventory Adjustments ---
    # Valid reason_codes per CHECK constraint (v2.15):
    # damaged, theft, data_entry_error, receiving_error, picking_error, found_stock, other
    reason_codes = ["damaged", "data_entry_error", "receiving_error", "found_stock"]
    reason_notes = {
        "damaged":          "Units damaged during handling, scrapped per SOP",
        "data_entry_error": "Data entry correction to align physical and system counts",
        "receiving_error":  "Receiving discrepancy identified during reconciliation",
        "found_stock":      "Previously unaccounted stock found during cycle count",
    }

    for i in range(adjustment_count):
        adj_id = det_uuid(f"adj:{i}")

        # Pick product
        prod_idx = int(det_uuid(f"adj-prod:{i}").replace("-", ""), 16) % len(all_products)
        prod = all_products[prod_idx]
        prod_id = det_uuid(f"product:{prod['sku']}")
        loc_id = get_location_id(prod["inventory_type"], prod["sku"])

        adjusted_by = get_employee_id(i)
        approved_by = get_employee_id(i + 1)

        # Reason code
        rc_idx = int(det_uuid(f"adj-rc:{i}").replace("-", ""), 16) % len(reason_codes)
        reason_code = reason_codes[rc_idx]
        notes = reason_notes[reason_code]

        # Quantity change: small, mostly negative (-50 to +50)
        qty_seed = int(det_uuid(f"adj-qty:{i}").replace("-", ""), 16) % 100 - 50
        if qty_seed == 0:
            qty_seed = -1  # avoid zero adjustments

        # Date with clustering
        rand_val = int(det_uuid(f"adj-time:{i}").replace("-", ""), 16) % 10000
        fraction = rand_val / 10000
        days_offset = int((history_months * 30) * (1 - fraction ** 2))
        adj_date = seed_dt - timedelta(days=days_offset)

        stmts.append(
            f"INSERT INTO inventory.inventory_adjustments (id, product_id, location_id, "
            f"adjusted_by, approved_by, quantity_change, reason_code, notes, "
            f"adjustment_date, created_date, updated_date, "
            f"approval_status, approval_reason, rejected_by, rejection_reason) VALUES (\n"
            f"  '{adj_id}',\n"
            f"  '{prod_id}',\n"
            f"  '{loc_id}',\n"
            f"  '{adjusted_by}',\n"
            f"  '{approved_by}',\n"
            f"  {qty_seed},\n"
            f"  {sql_str(reason_code)},\n"
            f"  {sql_str(notes)},\n"
            f"  {sql_timestamp(adj_date)},\n"
            f"  '{seed_date}', '{seed_date}',\n"
            f"  'approved', 'Approved during seed', NULL, NULL\n"
            f");\n"
        )

    write_sql_file("23_manitowoc_inventory.sql",
                   "Manitowoc inventory: items, transactions, transfers, adjustments",
                   stmts)


def generate_sales(config, products_data, known_ids):
    """Generate 24_manitowoc_sales.sql — fulfillment statuses, customers, orders, line items."""
    stmts = []
    seed_date = config["seed_date"]
    seed_dt = datetime.fromisoformat(seed_date)
    admin_id = known_ids["users"]["admin_gopher"]
    customer_count = config["customer_count"]
    order_count = config["order_count"]
    history_months = config["history_months"]
    employee_count = config["employee_count"]
    net30_id = known_ids["payment_terms"]["net_30"]
    city_id = det_uuid("city:Manitowoc")
    street_id = det_uuid("street:MTW-MFG")

    fake = Faker()
    Faker.seed(config["random_seed"] + 100)  # offset to avoid collision with employees

    # --- 1. Order fulfillment statuses ---
    order_statuses = [
        ("PENDING",       "Order received, awaiting processing",   "#FFA500", "#FFF3E0", "clock"),
        ("PROCESSING",    "Order is being prepared",               "#2196F3", "#E3F2FD", "cog"),
        ("PICKING",       "Items being picked from warehouse",     "#9C27B0", "#F3E5F5", "hand-pointer"),
        ("PACKING",       "Items being packed for shipment",       "#795548", "#EFEBE9", "box"),
        ("READY_TO_SHIP", "Order packed and ready for carrier",    "#00BCD4", "#E0F7FA", "truck-loading"),
        ("SHIPPED",       "Order shipped to customer",             "#4CAF50", "#E8F5E9", "shipping-fast"),
        ("DELIVERED",     "Order delivered to customer",           "#388E3C", "#E8F5E9", "check-circle"),
        ("CANCELLED",     "Order cancelled",                       "#F44336", "#FFEBEE", "times-circle"),
    ]
    for name, desc, pc, sc, icon in order_statuses:
        sid = det_uuid(f"order-fulfillment-status:{name}")
        stmts.append(
            f"INSERT INTO sales.order_fulfillment_statuses (id, name, description, primary_color, secondary_color, icon) VALUES (\n"
            f"  '{sid}', {sql_str(name)}, {sql_str(desc)}, {sql_str(pc)}, {sql_str(sc)}, {sql_str(icon)}\n"
            f") ON CONFLICT (name) DO NOTHING;\n"
        )

    # --- 2. Line item fulfillment statuses ---
    li_statuses = [
        ("PENDING",           "Line item awaiting processing",       "#FFA500", "#FFF3E0", "clock"),
        ("PROCESSING",        "Line item being processed",           "#2196F3", "#E3F2FD", "cog"),
        ("PICKED",            "All units picked",                    "#9C27B0", "#F3E5F5", "check"),
        ("PARTIALLY_PICKED",  "Some units picked",                   "#FF9800", "#FFF3E0", "tasks"),
        ("PACKED",            "Line item packed",                    "#795548", "#EFEBE9", "box"),
        ("SHIPPED",           "Line item shipped",                   "#4CAF50", "#E8F5E9", "shipping-fast"),
        ("DELIVERED",         "Line item delivered",                 "#388E3C", "#E8F5E9", "check-circle"),
        ("CANCELLED",         "Line item cancelled",                 "#F44336", "#FFEBEE", "times-circle"),
        ("BACKORDERED",       "Line item backordered",               "#FF5722", "#FBE9E7", "exclamation-triangle"),
    ]
    for name, desc, pc, sc, icon in li_statuses:
        sid = det_uuid(f"li-fulfillment-status:{name}")
        stmts.append(
            f"INSERT INTO sales.line_item_fulfillment_statuses (id, name, description, primary_color, secondary_color, icon) VALUES (\n"
            f"  '{sid}', {sql_str(name)}, {sql_str(desc)}, {sql_str(pc)}, {sql_str(sc)}, {sql_str(icon)}\n"
            f") ON CONFLICT (name) DO NOTHING;\n"
        )

    # --- 3. Customers (with contact_infos + streets) ---
    customer_ids = []
    for i in range(customer_count):
        cust_id = det_uuid(f"customer:{i}")
        contact_id = det_uuid(f"customer-contact:{i}")
        addr_id = det_uuid(f"customer-street:{i}")
        customer_ids.append(cust_id)

        company = fake.company()
        first = fake.first_name()
        last = fake.last_name()
        phone = fake.phone_number()[:20]
        email = fake.company_email()
        line1 = fake.street_address()

        # Contact info
        stmts.append(
            f"INSERT INTO core.contact_infos (id, first_name, last_name, primary_phone_number, secondary_phone_number, email_address, street_id, delivery_address_id, available_hours_start, available_hours_end, timezone_id, preferred_contact_type, notes) VALUES (\n"
            f"  '{contact_id}',\n"
            f"  {sql_str(first)}, {sql_str(last)},\n"
            f"  {sql_str(phone)}, NULL,\n"
            f"  {sql_str(email)},\n"
            f"  '{street_id}', NULL,\n"
            f"  '08:00:00', '17:00:00',\n"
            f"  (SELECT id FROM geography.timezones WHERE name = 'America/Chicago'),\n"
            f"  'email', NULL\n"
            f");\n"
        )

        # Delivery street address
        stmts.append(
            f"INSERT INTO geography.streets (id, city_id, line_1, line_2, postal_code) VALUES (\n"
            f"  '{addr_id}', '{city_id}',\n"
            f"  {sql_str(line1)}, NULL, {sql_str(fake.zipcode())}\n"
            f");\n"
        )

        # Customer
        user_id = det_uuid(f"employee:{i % employee_count}")
        stmts.append(
            f"INSERT INTO sales.customers (id, name, contact_id, delivery_address_id, notes, created_by, updated_by, created_date, updated_date) VALUES (\n"
            f"  '{cust_id}',\n"
            f"  {sql_str(company)},\n"
            f"  '{contact_id}',\n"
            f"  '{addr_id}',\n"
            f"  NULL,\n"
            f"  '{user_id}', '{user_id}',\n"
            f"  '{seed_date}', '{seed_date}'\n"
            f");\n"
        )

    # --- 4. Orders ---
    # Collect finished goods + finished bases for line items
    finished_products = [p for p in products_data["products"]
                         if p["inventory_type"] in ("finished_good", "wip")
                         and p["sku"].startswith(("RELAY-FIN", "BASE-FIN"))]
    # Also include RELAY-FIN as primary
    relay_fin = [p for p in products_data["products"] if p["sku"] == "RELAY-FIN"]

    # Status distribution thresholds (cumulative): CANCELLED 5%, PENDING 15%, PROCESSING 40%, SHIPPED 70%, DELIVERED 100%
    status_thresholds = [
        (0.05,  "CANCELLED"),
        (0.15,  "PENDING"),
        (0.40,  "PROCESSING"),
        (0.70,  "SHIPPED"),
        (1.00,  "DELIVERED"),
    ]

    history_start = seed_dt - timedelta(days=history_months * 30)

    for i in range(order_count):
        order_id = det_uuid(f"order:{i}")
        order_number = f"ORD-{i:06d}"

        # Pick customer
        cust_idx = int(det_uuid(f"order-cust:{i}").replace("-", ""), 16) % customer_count
        cust_id = customer_ids[cust_idx]

        # Date with exponential distribution
        rand_val = int(det_uuid(f"order-time:{i}").replace("-", ""), 16) % 10000
        fraction = rand_val / 10000
        days_offset = int((history_months * 30) * (1 - fraction ** 2))
        order_date = seed_dt - timedelta(days=days_offset)
        due_date = order_date + timedelta(days=14)

        # Status
        status_seed = int(det_uuid(f"order-status:{i}").replace("-", ""), 16) % 10000 / 10000
        order_status = "DELIVERED"
        for threshold, sname in status_thresholds:
            if status_seed < threshold:
                order_status = sname
                break

        order_status_id = det_uuid(f"order-fulfillment-status:{order_status}")
        user_id = det_uuid(f"employee:{i % employee_count}")

        # Line items: 1-5 per order
        num_items = int(det_uuid(f"order-items:{i}").replace("-", ""), 16) % 5 + 1

        subtotal = 0.0
        line_stmts = []

        for j in range(num_items):
            li_id = det_uuid(f"order-li:{i}:{j}")

            # 80% RELAY-FIN, 20% finished bases
            prod_seed = int(det_uuid(f"order-li-prod:{i}:{j}").replace("-", ""), 16) % 100
            if prod_seed < 80 and relay_fin:
                prod = relay_fin[0]
            else:
                pidx = int(det_uuid(f"order-li-pidx:{i}:{j}").replace("-", ""), 16) % len(finished_products)
                prod = finished_products[pidx]

            prod_id = det_uuid(f"product:{prod['sku']}")

            # Quantity: 10-500 relays per line
            qty = int(det_uuid(f"order-li-qty:{i}:{j}").replace("-", ""), 16) % 491 + 10

            # Unit price from product cost (deterministic)
            cost_seed = int(det_uuid(f"cost-seed:{prod['sku']}").replace("-", ""), 16) % 10000
            inv_type = prod["inventory_type"]
            cost_ranges = {"finished_good": (100, 500), "wip": (20, 200)}
            low, high = cost_ranges.get(inv_type, (20, 200))
            purchase_cost = round(low + (high - low) * (cost_seed / 10000), 2)
            unit_price = round(purchase_cost * 1.3, 2)  # selling price

            line_total = round(qty * unit_price, 2)
            subtotal += line_total

            # Line item status matches order status
            if order_status in ("DELIVERED", "SHIPPED"):
                li_status = order_status
                picked_qty = qty
            elif order_status == "CANCELLED":
                li_status = "CANCELLED"
                picked_qty = 0
            elif order_status == "PROCESSING":
                li_status = "PROCESSING"
                picked_qty = 0
            else:
                li_status = "PENDING"
                picked_qty = 0

            li_status_id = det_uuid(f"li-fulfillment-status:{li_status}")

            line_stmts.append(
                f"INSERT INTO sales.order_line_items (id, order_id, product_id, description, quantity, unit_price, discount, discount_type, line_total, line_item_fulfillment_statuses_id, picked_quantity, backordered_quantity, short_pick_reason, created_by, created_date, updated_by, updated_date) VALUES (\n"
                f"  '{li_id}',\n"
                f"  '{order_id}',\n"
                f"  '{prod_id}',\n"
                f"  NULL,\n"
                f"  {qty}, {unit_price}, 0, 'flat',\n"
                f"  {line_total},\n"
                f"  '{li_status_id}',\n"
                f"  {picked_qty}, 0, NULL,\n"
                f"  '{user_id}', '{seed_date}',\n"
                f"  '{user_id}', '{seed_date}'\n"
                f");\n"
            )

        # Financial totals
        tax_rate = 7.50
        tax_amount = round(subtotal * tax_rate / 100, 2)
        shipping_cost = round(25 + (int(det_uuid(f"order-ship:{i}").replace("-", ""), 16) % 200), 2)
        total_amount = round(subtotal + tax_amount + shipping_cost, 2)

        stmts.append(
            f"INSERT INTO sales.orders (id, number, customer_id, due_date, order_fulfillment_status_id, billing_address_id, shipping_address_id, order_date, payment_term_id, notes, subtotal, tax_rate, tax_amount, shipping_cost, total_amount, currency_id, created_by, updated_by, created_date, updated_date) VALUES (\n"
            f"  '{order_id}',\n"
            f"  {sql_str(order_number)},\n"
            f"  '{cust_id}',\n"
            f"  {sql_timestamp(due_date)},\n"
            f"  '{order_status_id}',\n"
            f"  NULL, NULL,\n"
            f"  {sql_timestamp(order_date)},\n"
            f"  '{net30_id}',\n"
            f"  NULL,\n"
            f"  {subtotal}, {tax_rate}, {tax_amount}, {shipping_cost}, {total_amount},\n"
            f"  (SELECT id FROM core.currencies WHERE code = 'USD'),\n"
            f"  '{user_id}', '{user_id}',\n"
            f"  '{seed_date}', '{seed_date}'\n"
            f");\n"
        )

        stmts.extend(line_stmts)

    write_sql_file("24_manitowoc_sales.sql",
                   "Manitowoc sales: fulfillment statuses, customers, orders, line items",
                   stmts)


def generate_procurement(config, products_data, suppliers_data, warehouses, known_ids):
    """Generate 25_manitowoc_procurement.sql — suppliers, POs, lot trackings, line items."""
    stmts = []
    seed_date = config["seed_date"]
    seed_dt = datetime.fromisoformat(seed_date)
    admin_id = known_ids["users"]["admin_gopher"]
    employee_count = config["employee_count"]
    po_count = config["po_count"]
    history_months = config["history_months"]
    net30_id = known_ids["payment_terms"]["net_30"]
    street_id = det_uuid("street:MTW-MFG")
    wh_id = det_uuid(f"warehouse:{warehouses['warehouses'][0]['code']}")

    # --- 1. Suppliers (from suppliers.yaml) ---
    supplier_ids = []
    all_supplier_products = []  # (supplier_product_id, supplier_id, product_sku, unit_cost)

    for sup in suppliers_data["suppliers"]:
        sup_code = sup["code"]
        sup_id = det_uuid(f"supplier:{sup_code}")
        contact_id = det_uuid(f"supplier-contact:{sup_code}")
        supplier_ids.append(sup_id)

        contact = sup.get("contact", {})

        # Contact info for supplier
        stmts.append(
            f"INSERT INTO core.contact_infos (id, first_name, last_name, primary_phone_number, secondary_phone_number, email_address, street_id, delivery_address_id, available_hours_start, available_hours_end, timezone_id, preferred_contact_type, notes) VALUES (\n"
            f"  '{contact_id}',\n"
            f"  {sql_str(sup['name'])}, 'Procurement',\n"
            f"  {sql_str(contact.get('phone', '555-0000'))}, NULL,\n"
            f"  {sql_str(contact.get('email', 'sales@example.com'))},\n"
            f"  '{street_id}', NULL,\n"
            f"  '08:00:00', '17:00:00',\n"
            f"  (SELECT id FROM geography.timezones WHERE name = 'America/Chicago'),\n"
            f"  'email', NULL\n"
            f");\n"
        )

        # Lead time: domestic=14, international=45
        lead_time = 14 if sup_code in ("MRP", "MTC") else 45
        rating = 4.5 if sup_code == "MRP" else 4.0

        stmts.append(
            f"INSERT INTO procurement.suppliers (id, contact_infos_id, name, payment_term_id, lead_time_days, rating, is_active, created_date, updated_date) VALUES (\n"
            f"  '{sup_id}',\n"
            f"  '{contact_id}',\n"
            f"  {sql_str(sup['name'])},\n"
            f"  '{net30_id}',\n"
            f"  {lead_time}, {rating}, true,\n"
            f"  '{seed_date}', '{seed_date}'\n"
            f");\n"
        )

        # Supplier products
        is_primary = (sup_code == "MRP")  # MR&P is primary for most
        for sp in sup.get("products", []):
            sp_id = det_uuid(f"supplier-product:{sup_code}:{sp['supplier_part']}")
            prod_id = det_uuid(f"product:{sp['product_sku']}")

            # Derive unit cost from product cost
            cost_seed = int(det_uuid(f"cost-seed:{sp['product_sku']}").replace("-", ""), 16) % 10000
            unit_cost = round(1 + 99 * (cost_seed / 10000), 2)

            all_supplier_products.append((sp_id, sup_id, sp["product_sku"], unit_cost, sp["supplier_part"]))

            stmts.append(
                f"INSERT INTO procurement.supplier_products (id, supplier_id, product_id, supplier_part_number, min_order_quantity, max_order_quantity, lead_time_days, unit_cost, is_primary_supplier, created_date, updated_date) VALUES (\n"
                f"  '{sp_id}',\n"
                f"  '{sup_id}',\n"
                f"  '{prod_id}',\n"
                f"  {sql_str(sp['supplier_part'])},\n"
                f"  100, 50000,\n"
                f"  {lead_time}, {unit_cost},\n"
                f"  {sql_str(is_primary)},\n"
                f"  '{seed_date}', '{seed_date}'\n"
                f");\n"
            )

    # --- 2. Lot trackings (for dual-sourced products with tracking_type: lot) ---
    lot_products = [p for p in products_data["products"] if p.get("tracking_type") == "lot"]
    lot_idx = 0
    for prod in lot_products:
        sku = prod["sku"]
        # Find supplier_products for this sku
        matching_sps = [(sp_id, sup_id, unit_cost, part_num) for sp_id, sup_id, psku, unit_cost, part_num in all_supplier_products if psku == sku]

        for sp_id, sup_id, unit_cost, part_num in matching_sps:
            lot_id = det_uuid(f"lot:{sku}:{lot_idx}")
            lot_number = f"LOT-{sku}-{lot_idx:04d}"
            lot_idx += 1

            # manufacture 90 days before seed, expiration 2 years out, received 60 days before seed
            mfg_date = seed_dt - timedelta(days=90)
            exp_date = seed_dt + timedelta(days=730)
            recv_date = seed_dt - timedelta(days=60)

            # Distribute initial qty across suppliers
            qty = max(100, prod["initial_qty"] // max(1, len(matching_sps)))

            stmts.append(
                f"INSERT INTO inventory.lot_trackings (id, supplier_product_id, lot_number, manufacture_date, expiration_date, received_date, quantity, quality_status, created_date, updated_date) VALUES (\n"
                f"  '{lot_id}',\n"
                f"  '{sp_id}',\n"
                f"  {sql_str(lot_number)},\n"
                f"  {sql_timestamp(mfg_date)},\n"
                f"  {sql_timestamp(exp_date)},\n"
                f"  {sql_timestamp(recv_date)},\n"
                f"  {qty},\n"
                f"  'released',\n"
                f"  '{seed_date}', '{seed_date}'\n"
                f");\n"
            )

    # --- 3. Purchase order statuses ---
    po_statuses = [
        ("DRAFT",              "Purchase order drafted",           10),
        ("SUBMITTED",          "Submitted to supplier",           20),
        ("APPROVED",           "Approved for ordering",           30),
        ("ORDERED",            "Order placed with supplier",      40),
        ("PARTIALLY_RECEIVED", "Some items received",             50),
        ("RECEIVED",           "All items received",              60),
        ("CLOSED",             "PO closed and reconciled",        70),
        ("CANCELLED",          "PO cancelled",                    80),
    ]
    for name, desc, sort in po_statuses:
        sid = det_uuid(f"po-status:{name}")
        stmts.append(
            f"INSERT INTO procurement.purchase_order_statuses (id, name, description, sort_order) VALUES (\n"
            f"  '{sid}', {sql_str(name)}, {sql_str(desc)}, {sort}\n"
            f") ON CONFLICT (name) DO NOTHING;\n"
        )

    # --- 4. PO line item statuses ---
    poli_statuses = [
        ("PENDING",            "Awaiting order placement",        10),
        ("ORDERED",            "Ordered from supplier",           20),
        ("PARTIALLY_RECEIVED", "Some units received",             30),
        ("RECEIVED",           "All units received",              40),
        ("CANCELLED",          "Line item cancelled",             50),
    ]
    for name, desc, sort in poli_statuses:
        sid = det_uuid(f"poli-status:{name}")
        stmts.append(
            f"INSERT INTO procurement.purchase_order_line_item_statuses (id, name, description, sort_order) VALUES (\n"
            f"  '{sid}', {sql_str(name)}, {sql_str(desc)}, {sort}\n"
            f") ON CONFLICT (name) DO NOTHING;\n"
        )

    # --- 5. Purchase orders ---
    # PO status distribution: ~5% CANCELLED, ~10% DRAFT, ~15% ORDERED, ~30% RECEIVED, ~40% CLOSED
    po_status_thresholds = [
        (0.05, "CANCELLED"),
        (0.15, "DRAFT"),
        (0.30, "ORDERED"),
        (0.60, "RECEIVED"),
        (1.00, "CLOSED"),
    ]

    for i in range(po_count):
        po_id = det_uuid(f"po:{i}")
        po_number = f"PO-{i:06d}"

        # Pick supplier
        sup_idx = int(det_uuid(f"po-sup:{i}").replace("-", ""), 16) % len(supplier_ids)
        sup_id = supplier_ids[sup_idx]

        # Find supplier products for this supplier
        sup_prods = [(sp_id, psku, uc, pn) for sp_id, sid, psku, uc, pn in all_supplier_products if sid == sup_id]
        if not sup_prods:
            continue

        # Date with exponential distribution
        rand_val = int(det_uuid(f"po-time:{i}").replace("-", ""), 16) % 10000
        fraction = rand_val / 10000
        days_offset = int((history_months * 30) * (1 - fraction ** 2))
        order_date = seed_dt - timedelta(days=days_offset)
        expected_delivery = order_date + timedelta(days=30)

        # Status
        status_seed = int(det_uuid(f"po-status-seed:{i}").replace("-", ""), 16) % 10000 / 10000
        po_status = "CLOSED"
        for threshold, sname in po_status_thresholds:
            if status_seed < threshold:
                po_status = sname
                break

        po_status_id = det_uuid(f"po-status:{po_status}")
        requested_by = det_uuid(f"employee:{i % employee_count}")
        approved_by = det_uuid(f"employee:{(i + 1) % employee_count}")

        actual_delivery = None
        approved_date = None
        if po_status in ("RECEIVED", "CLOSED"):
            actual_delivery = expected_delivery + timedelta(days=int(det_uuid(f"po-delay:{i}").replace("-", ""), 16) % 7)
            approved_date = order_date + timedelta(days=1)

        # Line items: 1-4 per PO
        num_items = int(det_uuid(f"po-items:{i}").replace("-", ""), 16) % 4 + 1
        subtotal = 0.0
        po_line_stmts = []

        for j in range(num_items):
            li_id = det_uuid(f"po-li:{i}:{j}")
            sp_idx = int(det_uuid(f"po-li-sp:{i}:{j}").replace("-", ""), 16) % len(sup_prods)
            sp_id, psku, unit_cost, part_num = sup_prods[sp_idx]

            qty_ordered = int(det_uuid(f"po-li-qty:{i}:{j}").replace("-", ""), 16) % 4901 + 100
            line_total = round(qty_ordered * unit_cost, 2)
            subtotal += line_total

            # Quantities based on PO status
            if po_status in ("RECEIVED", "CLOSED"):
                qty_received = qty_ordered
                qty_cancelled = 0
                li_status = "RECEIVED"
                li_actual = actual_delivery
            elif po_status == "CANCELLED":
                qty_received = 0
                qty_cancelled = qty_ordered
                li_status = "CANCELLED"
                li_actual = None
            elif po_status == "ORDERED":
                qty_received = 0
                qty_cancelled = 0
                li_status = "ORDERED"
                li_actual = None
            else:
                qty_received = 0
                qty_cancelled = 0
                li_status = "PENDING"
                li_actual = None

            li_status_id = det_uuid(f"poli-status:{li_status}")

            po_line_stmts.append(
                f"INSERT INTO procurement.purchase_order_line_items (id, purchase_order_id, supplier_product_id, quantity_ordered, quantity_received, quantity_cancelled, unit_cost, discount, line_total, line_item_status_id, expected_delivery_date, actual_delivery_date, notes, created_by, updated_by, created_date, updated_date) VALUES (\n"
                f"  '{li_id}',\n"
                f"  '{po_id}',\n"
                f"  '{sp_id}',\n"
                f"  {qty_ordered}, {qty_received}, {qty_cancelled},\n"
                f"  {unit_cost}, 0, {line_total},\n"
                f"  '{li_status_id}',\n"
                f"  {sql_timestamp(expected_delivery)},\n"
                f"  {sql_timestamp(li_actual) if li_actual else 'NULL'},\n"
                f"  NULL,\n"
                f"  '{requested_by}', '{requested_by}',\n"
                f"  '{seed_date}', '{seed_date}'\n"
                f");\n"
            )

        tax_amount = round(subtotal * 0.075, 2)
        shipping_cost = round(50 + (int(det_uuid(f"po-ship:{i}").replace("-", ""), 16) % 300), 2)
        total_amount = round(subtotal + tax_amount + shipping_cost, 2)

        quoted_approved_by = f"'{approved_by}'" if approved_date else "NULL"

        stmts.append(
            f"INSERT INTO procurement.purchase_orders (id, order_number, supplier_id, purchase_order_status_id, delivery_warehouse_id, delivery_location_id, delivery_street_id, order_date, expected_delivery_date, actual_delivery_date, subtotal, tax_amount, shipping_cost, total_amount, currency_id, requested_by, approved_by, approved_date, approval_reason, rejected_by, rejected_date, rejection_reason, notes, supplier_reference_number, created_by, updated_by, created_date, updated_date) VALUES (\n"
            f"  '{po_id}',\n"
            f"  {sql_str(po_number)},\n"
            f"  '{sup_id}',\n"
            f"  '{po_status_id}',\n"
            f"  '{wh_id}',\n"
            f"  NULL, NULL,\n"
            f"  {sql_timestamp(order_date)},\n"
            f"  {sql_timestamp(expected_delivery)},\n"
            f"  {sql_timestamp(actual_delivery) if actual_delivery else 'NULL'},\n"
            f"  {subtotal}, {tax_amount}, {shipping_cost}, {total_amount},\n"
            f"  (SELECT id FROM core.currencies WHERE code = 'USD'),\n"
            f"  '{requested_by}',\n"
            f"  {quoted_approved_by},\n"
            f"  {sql_timestamp(approved_date) if approved_date else 'NULL'},\n"
            f"  NULL, NULL, NULL, NULL, NULL, NULL,\n"
            f"  '{requested_by}', '{requested_by}',\n"
            f"  '{seed_date}', '{seed_date}'\n"
            f");\n"
        )

        stmts.extend(po_line_stmts)

    write_sql_file("25_manitowoc_procurement.sql",
                   "Manitowoc procurement: suppliers, supplier products, lot trackings, PO statuses, POs, line items",
                   stmts)


def generate_workflows(config, known_ids):
    """Generate 26_manitowoc_workflows.sql — platform defaults are sufficient."""
    stmts = []
    stmts.append("-- Workflow rules and templates are provided by the platform baseline.\n")
    stmts.append("-- No Manitowoc-specific workflow configuration needed at this time.\n")

    write_sql_file("26_manitowoc_workflows.sql",
                   "Manitowoc workflows: using platform defaults",
                   stmts)


def generate_permissions(config, known_ids):
    """Generate 27_manitowoc_permissions.sql — assign all employees to ZZZADMIN role."""
    stmts = []
    employee_count = config["employee_count"]
    zzzadmin_id = known_ids["roles"]["zzzadmin"]

    for i in range(employee_count):
        emp_id = det_uuid(f"employee:{i}")
        ur_id = det_uuid(f"user-role:{i}")
        stmts.append(
            f"INSERT INTO core.user_roles (id, user_id, role_id) VALUES (\n"
            f"  '{ur_id}', '{emp_id}', '{zzzadmin_id}'\n"
            f");\n"
        )

    write_sql_file("27_manitowoc_permissions.sql",
                   "Manitowoc permissions: employee role assignments",
                   stmts)


def main():
    print("Loading YAML data...")
    config = load_yaml("config.yaml")
    known_ids = load_yaml("known_ids.yaml")
    warehouses = load_yaml("warehouses.yaml")
    products = load_yaml("products.yaml")
    suppliers = load_yaml("suppliers.yaml")

    # Seed RNG for deterministic output
    random.seed(config["random_seed"])
    fake = Faker()
    Faker.seed(config["random_seed"])

    print(f"Config: {config['history_months']} months history, "
          f"{config['employee_count']} employees, {config['order_count']} orders")
    print(f"Products: {len(products['products'])} items loaded")
    print(f"Warehouses: {len(warehouses['warehouses'])} warehouses loaded")

    # Validate zone stages
    valid_stages = {"inbound", "received", "processing", "assembly",
                    "calibration", "qa", "outbound"}
    for wh in warehouses["warehouses"]:
        for zone in wh.get("zones", []):
            stage = zone.get("stage")
            if stage and stage not in valid_stages:
                raise ValueError(
                    f"Invalid zone stage '{stage}' in zone '{zone['name']}'. "
                    f"Valid: {valid_stages}")

    print("\nGenerating SQL files...")
    generate_org(config, warehouses, known_ids)
    generate_products(config, products, known_ids)
    generate_employees(config, known_ids)
    generate_inventory(config, products, warehouses, known_ids)
    generate_sales(config, products, known_ids)
    generate_procurement(config, products, suppliers, warehouses, known_ids)
    generate_workflows(config, known_ids)
    generate_permissions(config, known_ids)

    print("\nDone.")


if __name__ == "__main__":
    main()
