#!/usr/bin/env python3
"""
Manitowoc seed data generator.

Reads YAML data files + config, outputs numbered SQL files (20_*-27_*)
to the seed/ directory. All UUIDs are deterministic — same input = same output.

Usage: python3 generate.py
"""

import uuid
import yaml
import random
import os
from datetime import datetime, timedelta
from pathlib import Path
from faker import Faker

# === Constants ===
BASE_DIR = Path(__file__).parent
DATA_DIR = BASE_DIR / "data"
SEED_DIR = BASE_DIR / "seed"

# UUID namespace for deterministic generation
NAMESPACE = uuid.UUID("deadbeef-dead-beef-dead-beefdeadbeef")


def load_yaml(filename: str) -> dict:
    """Load a YAML file from the data/ directory."""
    with open(DATA_DIR / filename) as f:
        return yaml.safe_load(f)


def det_uuid(key: str) -> str:
    """Generate a deterministic UUID v5 from a string key."""
    return str(uuid.uuid5(NAMESPACE, key))


def sql_str(value) -> str:
    """Escape a value for SQL insertion."""
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    escaped = str(value).replace("'", "''")
    return f"'{escaped}'"


def sql_timestamp(dt) -> str:
    """Format a datetime for SQL insertion."""
    if isinstance(dt, str):
        return f"'{dt}'"
    return f"'{dt.isoformat()}'"


def write_sql_file(filename: str, header: str, statements: list[str]):
    """Write a SQL file with BEGIN/COMMIT wrapping."""
    path = SEED_DIR / filename
    with open(path, "w") as f:
        f.write(f"-- {header}\n")
        f.write(f"-- Generated by generate.py\n")
        f.write("BEGIN;\n\n")
        for stmt in statements:
            f.write(stmt)
            if not stmt.endswith("\n"):
                f.write("\n")
        f.write("\nCOMMIT;\n")
    print(f"  Wrote {path.name} ({len(statements)} statements)")


# === Generators (one per output file) — stubs for now ===

def generate_org(config, warehouses, known_ids):
    """Generate 20_manitowoc_org.sql — geography prereqs, warehouses, zones, locations.

    Schema notes:
    - warehouses requires street_id FK (geography.streets -> cities -> regions)
    - zones has NO code column (name + description + stage only)
    - locations use aisle/rack/shelf/bin coordinates, NOT name/code
    """
    stmts = []
    admin_id = known_ids["users"]["admin_gopher"]
    seed_date = config["seed_date"]
    geo = warehouses["geography"]

    # --- Geography prerequisites ---
    city_id = det_uuid("city:Manitowoc")
    street_id = det_uuid("street:MTW-MFG")

    stmts.append(
        f"INSERT INTO geography.cities (id, region_id, name) VALUES (\n"
        f"  '{city_id}',\n"
        f"  (SELECT id FROM geography.regions WHERE alpha_2 = '{geo['region']}'),\n"
        f"  {sql_str(geo['city'])}\n"
        f");\n"
    )

    stmts.append(
        f"INSERT INTO geography.streets (id, city_id, line_1, line_2, zip_code) VALUES (\n"
        f"  '{street_id}',\n"
        f"  '{city_id}',\n"
        f"  {sql_str(geo['street']['line_1'])},\n"
        f"  NULL,\n"
        f"  {sql_str(geo['street']['postal_code'])}\n"
        f");\n"
    )

    # --- Warehouses, Zones, Locations ---
    for wh in warehouses["warehouses"]:
        wh_code = wh["code"]
        wh_id = det_uuid(f"warehouse:{wh_code}")

        stmts.append(
            f"INSERT INTO inventory.warehouses (id, code, name, street_id, is_active, created_date, updated_date, created_by, updated_by) VALUES (\n"
            f"  '{wh_id}',\n"
            f"  {sql_str(wh_code)},\n"
            f"  {sql_str(wh['name'])},\n"
            f"  '{street_id}',\n"
            f"  true,\n"
            f"  '{seed_date}', '{seed_date}',\n"
            f"  '{admin_id}', '{admin_id}'\n"
            f");\n"
        )

        for zone in wh.get("zones", []):
            zone_key = f"zone:{wh_code}:{zone['name']}"
            zone_id = det_uuid(zone_key)

            stmts.append(
                f"INSERT INTO inventory.zones (id, warehouse_id, name, description, stage, created_date, updated_date) VALUES (\n"
                f"  '{zone_id}',\n"
                f"  '{wh_id}',\n"
                f"  {sql_str(zone['name'])},\n"
                f"  {sql_str(zone.get('description'))},\n"
                f"  {sql_str(zone.get('stage'))},\n"
                f"  '{seed_date}', '{seed_date}'\n"
                f");\n"
            )

            for loc in zone.get("locations", []):
                loc_key = f"location:{wh_code}:{loc['aisle']}:{loc['rack']}:{loc['shelf']}:{loc['bin']}"
                loc_id = det_uuid(loc_key)

                stmts.append(
                    f"INSERT INTO inventory.locations (id, zone_id, warehouse_id, aisle, rack, shelf, bin, is_pick_location, is_reserve_location, max_capacity, current_utilization, created_date, updated_date) VALUES (\n"
                    f"  '{loc_id}',\n"
                    f"  '{zone_id}',\n"
                    f"  '{wh_id}',\n"
                    f"  {sql_str(loc['aisle'])},\n"
                    f"  {sql_str(loc['rack'])},\n"
                    f"  {sql_str(loc['shelf'])},\n"
                    f"  {sql_str(loc['bin'])},\n"
                    f"  {sql_str(loc.get('is_pick', False))},\n"
                    f"  {sql_str(loc.get('is_reserve', False))},\n"
                    f"  {loc.get('max_capacity', 100)},\n"
                    f"  0.0000,\n"
                    f"  '{seed_date}', '{seed_date}'\n"
                    f");\n"
                )

    write_sql_file("20_manitowoc_org.sql",
                   "Manitowoc org: geography, warehouses, zones, locations",
                   stmts)


def generate_products(config, products_data, known_ids):
    """Generate 21_manitowoc_products.sql — contact_info, brands, categories, products, UOMs, costs.

    Schema notes:
    - brands requires contact_infos_id FK (core.contact_infos)
    - products requires: description, upc_code, status, is_active, is_perishable,
      units_per_case, tracking_type (all NOT NULL)
    """
    stmts = []
    seed_date = config["seed_date"]
    street_id = det_uuid("street:MTW-MFG")

    # --- Cost parameters by inventory_type ---
    cost_ranges = {
        "raw_material":  (1, 50),
        "component":     (5, 100),
        "consumable":    (2, 20),
        "wip":           (20, 200),
        "finished_good": (100, 500),
    }
    abc_map = {
        "finished_good": "A",
        "wip":           "B",
        "component":     "B",
        "raw_material":  "C",
        "consumable":    "C",
    }

    # --- 1. Contact info for brand ---
    for brand in products_data["brands"]:
        contact_id = det_uuid(f"contact:{brand['code']}")
        stmts.append(
            f"INSERT INTO core.contact_infos (id, first_name, last_name, primary_phone_number, secondary_phone_number, email_address, street_id, delivery_address_id, available_hours_start, available_hours_end, timezone_id, preferred_contact_type, notes) VALUES (\n"
            f"  '{contact_id}',\n"
            f"  'Manitowoc', 'Relay Division',\n"
            f"  '920-555-0100', NULL,\n"
            f"  'relays@manitowoc-mfg.example.com',\n"
            f"  '{street_id}', NULL,\n"
            f"  '08:00:00', '17:00:00',\n"
            f"  (SELECT id FROM geography.timezones WHERE name = 'America/Chicago'),\n"
            f"  'email',\n"
            f"  NULL\n"
            f");\n"
        )

    # --- 2. Brands ---
    for brand in products_data["brands"]:
        brand_id = det_uuid(f"brand:{brand['code']}")
        contact_id = det_uuid(f"contact:{brand['code']}")
        stmts.append(
            f"INSERT INTO products.brands (id, name, contact_infos_id, created_date, updated_date) VALUES (\n"
            f"  '{brand_id}',\n"
            f"  {sql_str(brand['name'])},\n"
            f"  '{contact_id}',\n"
            f"  '{seed_date}', '{seed_date}'\n"
            f");\n"
        )

    # --- 3. Categories ---
    category_ids = {}
    for cat_name in products_data["categories"]:
        cat_id = det_uuid(f"category:{cat_name}")
        category_ids[cat_name] = cat_id
        stmts.append(
            f"INSERT INTO products.product_categories (id, name, description, created_date, updated_date) VALUES (\n"
            f"  '{cat_id}',\n"
            f"  {sql_str(cat_name)},\n"
            f"  {sql_str(cat_name)},\n"
            f"  '{seed_date}', '{seed_date}'\n"
            f");\n"
        )

    # Use the first brand for all products
    brand_id = det_uuid(f"brand:{products_data['brands'][0]['code']}")

    # --- 4. Products ---
    for prod in products_data["products"]:
        sku = prod["sku"]
        prod_id = det_uuid(f"product:{sku}")
        cat_id = category_ids[prod["category"]]
        inv_type = prod["inventory_type"]
        tracking_type = prod.get("tracking_type", "none")

        # units_per_case: first non-base UOM factor, or 1
        units_per_case = 1
        for uom in prod.get("uoms", []):
            if not uom.get("is_base", False):
                units_per_case = uom["factor"]
                break

        stmts.append(
            f"INSERT INTO products.products (id, sku, brand_id, category_id, name, description, model_number, upc_code, status, is_active, is_perishable, handling_instructions, units_per_case, tracking_type, inventory_type, created_date, updated_date) VALUES (\n"
            f"  '{prod_id}',\n"
            f"  {sql_str(sku)},\n"
            f"  '{brand_id}',\n"
            f"  '{cat_id}',\n"
            f"  {sql_str(prod['name'])},\n"
            f"  {sql_str('Manitowoc relay component: ' + prod['name'])},\n"
            f"  NULL,\n"
            f"  {sql_str(f'MTW-{sku}-UPC')},\n"
            f"  'active',\n"
            f"  true,\n"
            f"  false,\n"
            f"  NULL,\n"
            f"  {units_per_case},\n"
            f"  {sql_str(tracking_type)},\n"
            f"  {sql_str(inv_type)},\n"
            f"  '{seed_date}', '{seed_date}'\n"
            f");\n"
        )

    # --- 5. Product UOMs ---
    for prod in products_data["products"]:
        sku = prod["sku"]
        prod_id = det_uuid(f"product:{sku}")
        for uom in prod.get("uoms", []):
            uom_id = det_uuid(f"uom:{sku}:{uom['name']}")
            is_base = uom.get("is_base", False)
            is_approx = uom.get("is_approximate", False)
            stmts.append(
                f"INSERT INTO products.product_uoms (id, product_id, name, abbreviation, conversion_factor, is_base, is_approximate, notes, created_date, updated_date) VALUES (\n"
                f"  '{uom_id}',\n"
                f"  '{prod_id}',\n"
                f"  {sql_str(uom['name'])},\n"
                f"  {sql_str(uom['name'][:3])},\n"
                f"  {uom['factor']},\n"
                f"  {sql_str(is_base)},\n"
                f"  {sql_str(is_approx)},\n"
                f"  NULL,\n"
                f"  '{seed_date}', '{seed_date}'\n"
                f");\n"
            )

    # --- 6. Product Costs ---
    for prod in products_data["products"]:
        sku = prod["sku"]
        prod_id = det_uuid(f"product:{sku}")
        cost_id = det_uuid(f"cost:{sku}")
        inv_type = prod["inventory_type"]

        # Deterministic cost based on sku hash
        low, high = cost_ranges.get(inv_type, (5, 100))
        # Use det_uuid to derive a stable number
        cost_seed = int(det_uuid(f"cost-seed:{sku}").replace("-", ""), 16) % 10000
        purchase_cost = round(low + (high - low) * (cost_seed / 10000), 2)
        selling_price = round(purchase_cost * 1.3, 2)
        msrp = round(selling_price * 1.1, 2)
        landed_cost = round(purchase_cost * 1.05, 2)
        carrying_cost = round(purchase_cost * 0.02, 2)
        insurance_value = round(purchase_cost * 0.01, 2)
        abc = abc_map.get(inv_type, "C")

        stmts.append(
            f"INSERT INTO products.product_costs (id, product_id, purchase_cost, selling_price, currency_id, msrp, markup_percentage, landed_cost, carrying_cost, abc_classification, depreciation_value, insurance_value, effective_date, created_date, updated_date) VALUES (\n"
            f"  '{cost_id}',\n"
            f"  '{prod_id}',\n"
            f"  {purchase_cost},\n"
            f"  {selling_price},\n"
            f"  (SELECT id FROM core.currencies WHERE code = 'USD'),\n"
            f"  {msrp},\n"
            f"  0.3,\n"
            f"  {landed_cost},\n"
            f"  {carrying_cost},\n"
            f"  {sql_str(abc)},\n"
            f"  0.10,\n"
            f"  {insurance_value},\n"
            f"  '{seed_date}',\n"
            f"  '{seed_date}', '{seed_date}'\n"
            f");\n"
        )

    write_sql_file("21_manitowoc_products.sql",
                   "Manitowoc products: contact_infos, brands, categories, products, UOMs, costs",
                   stmts)


def generate_employees(config, known_ids):
    """Generate 22_manitowoc_employees.sql — placeholder users."""
    stmts = []
    seed_date = config["seed_date"]
    seed_dt = datetime.fromisoformat(seed_date)
    employee_count = config["employee_count"]
    approved_status_id = known_ids["hr_user_approval_status"]["approved"]
    password_hash = "$2a$10$1ggfMVZV6Js0ybvJufLRUOWHS5f6KneuP0XwwHpJ8L8ipdry9f2/a"

    fake = Faker()
    Faker.seed(config["random_seed"])

    for i in range(employee_count):
        emp_id = det_uuid(f"employee:{i}")
        first_name = fake.first_name()
        last_name = fake.last_name()
        username = f"{first_name.lower()}_{last_name.lower()}"
        email = f"{username}@manitowoc-mfg.example.com"

        # 10% ADMIN, 90% no role
        roles = "'{ADMIN}'" if i < (employee_count // 10) else "'{}'"""

        # date_hired: spread over 2 years before seed_date, weighted toward earlier
        # Use exponential distribution: most hires are older (tenured workforce)
        rand_val = int(det_uuid(f"hire-seed:{i}").replace("-", ""), 16) % 10000
        # Exponential weighting: earlier hires more likely
        # Map 0..1 to 0..730 days, with bias toward higher values (further in past)
        fraction = rand_val / 10000
        days_before = int(730 * (1 - fraction ** 2))  # quadratic bias toward earlier
        date_hired = (seed_dt - timedelta(days=days_before)).strftime("%Y-%m-%d")

        stmts.append(
            f"INSERT INTO core.users (id, requested_by, approved_by, user_approval_status_id, "
            f"title_id, office_id, work_phone_id, cell_phone_id, "
            f"username, first_name, last_name, email, birthday, "
            f"roles, system_roles, password_hash, enabled, "
            f"date_hired, date_requested, date_approved, "
            f"created_date, updated_date) VALUES (\n"
            f"  '{emp_id}',\n"
            f"  NULL, NULL,\n"
            f"  '{approved_status_id}',\n"
            f"  NULL, NULL, NULL, NULL,\n"
            f"  {sql_str(username)},\n"
            f"  {sql_str(first_name)},\n"
            f"  {sql_str(last_name)},\n"
            f"  {sql_str(email)},\n"
            f"  NULL,\n"
            f"  {roles}, '{{}}',\n"
            f"  {sql_str(password_hash)},\n"
            f"  true,\n"
            f"  '{date_hired}',\n"
            f"  NULL, NULL,\n"
            f"  '{seed_date}', '{seed_date}'\n"
            f");\n"
        )

    write_sql_file("22_manitowoc_employees.sql",
                   "Manitowoc employees: placeholder users",
                   stmts)


def generate_inventory(config, products_data, warehouses, known_ids):
    """Generate 23_manitowoc_inventory.sql — items, transactions, transfers, adjustments."""
    stmts = []
    seed_date = config["seed_date"]
    seed_dt = datetime.fromisoformat(seed_date)
    history_months = config["history_months"]
    transfer_count = config["transfer_count"]
    adjustment_count = config["adjustment_count"]
    admin_id = known_ids["users"]["admin_gopher"]
    employee_count = config["employee_count"]

    # --- Build location mapping by inventory_type ---
    # Map inventory_type to a zone's first location key
    wh = warehouses["warehouses"][0]
    wh_code = wh["code"]

    # Build zone-to-locations mapping
    zone_locations = {}  # zone_name -> list of location keys
    for zone in wh.get("zones", []):
        locs = []
        for loc in zone.get("locations", []):
            loc_key = f"location:{wh_code}:{loc['aisle']}:{loc['rack']}:{loc['shelf']}:{loc['bin']}"
            locs.append(loc_key)
        zone_locations[zone["name"]] = locs

    # Map inventory_type to appropriate zone locations
    type_to_zone = {
        "raw_material":  "Raw Material Storage",
        "component":     "Plastics Storage",
        "wip":           "Coil Winding Floor",
        "finished_good": "Finished Goods",
        "consumable":    "Coil Winding Floor",
    }

    def get_location_id(inv_type, sku):
        """Get a deterministic location for a product based on type."""
        zone_name = type_to_zone.get(inv_type, "Raw Material Storage")
        locs = zone_locations.get(zone_name, [])
        if not locs:
            # Fallback to first location in first zone
            first_zone = list(zone_locations.values())[0]
            locs = first_zone
        # Pick location deterministically based on sku
        idx = int(det_uuid(f"loc-pick:{sku}").replace("-", ""), 16) % len(locs)
        return det_uuid(locs[idx])

    def get_employee_id(index):
        """Get a deterministic employee UUID."""
        return det_uuid(f"employee:{index % employee_count}")

    # --- 1. Inventory Items (one per product) ---
    all_products = products_data["products"]
    for prod in all_products:
        sku = prod["sku"]
        prod_id = det_uuid(f"product:{sku}")
        inv_type = prod["inventory_type"]
        loc_id = get_location_id(inv_type, sku)
        item_id = det_uuid(f"inv-item:{sku}")
        qty = prod["initial_qty"]

        # Stock management fields
        minimum_stock = max(1, int(qty * 0.1))
        maximum_stock = max(10, int(qty * 2.0))
        reorder_point = max(1, int(qty * 0.2))
        eoq = max(1, int(qty * 0.5))
        safety_stock = max(1, int(qty * 0.15))
        avg_daily_usage = round(max(0.1, qty / 180), 4)  # ~6 months

        stmts.append(
            f"INSERT INTO inventory.inventory_items (id, product_id, location_id, "
            f"quantity, reserved_quantity, allocated_quantity, "
            f"minimum_stock, maximum_stock, reorder_point, economic_order_quantity, "
            f"safety_stock, avg_daily_usage, created_date, updated_date) VALUES (\n"
            f"  '{item_id}',\n"
            f"  '{prod_id}',\n"
            f"  '{loc_id}',\n"
            f"  {qty}, 0, 0,\n"
            f"  {minimum_stock}, {maximum_stock}, {reorder_point}, {eoq},\n"
            f"  {safety_stock}, {avg_daily_usage},\n"
            f"  '{seed_date}', '{seed_date}'\n"
            f");\n"
        )

    # --- 2. Inventory Transactions (historical) ---
    txn_types = ["received", "shipped", "transferred", "adjusted"]
    history_start = seed_dt - timedelta(days=history_months * 30)

    for i in range(transfer_count):
        txn_id = det_uuid(f"inv-txn:{i}")
        # Exponential distribution: more recent = more activity
        rand_val = int(det_uuid(f"txn-time:{i}").replace("-", ""), 16) % 10000
        fraction = rand_val / 10000
        # Exponential: square the fraction so more cluster near seed_date
        days_offset = int((history_months * 30) * (1 - fraction ** 2))
        txn_date = (seed_dt - timedelta(days=days_offset))

        # Pick product deterministically
        prod_idx = int(det_uuid(f"txn-prod:{i}").replace("-", ""), 16) % len(all_products)
        prod = all_products[prod_idx]
        prod_id = det_uuid(f"product:{prod['sku']}")
        loc_id = get_location_id(prod["inventory_type"], prod["sku"])
        user_id = get_employee_id(i)

        # Pick txn type
        type_idx = int(det_uuid(f"txn-type:{i}").replace("-", ""), 16) % len(txn_types)
        txn_type = txn_types[type_idx]

        # Quantity: positive for received, variable for others
        qty_seed = int(det_uuid(f"txn-qty:{i}").replace("-", ""), 16) % 200 + 1
        if txn_type == "shipped":
            qty_seed = -qty_seed
        elif txn_type == "adjusted":
            qty_seed = qty_seed if (i % 3 == 0) else -qty_seed

        ref_num = f"TXN-{i:06d}"

        stmts.append(
            f"INSERT INTO inventory.inventory_transactions (id, product_id, location_id, "
            f"user_id, transaction_type, quantity, reference_number, transaction_date, "
            f"lot_id, created_date, updated_date) VALUES (\n"
            f"  '{txn_id}',\n"
            f"  '{prod_id}',\n"
            f"  '{loc_id}',\n"
            f"  '{user_id}',\n"
            f"  {sql_str(txn_type)},\n"
            f"  {qty_seed},\n"
            f"  {sql_str(ref_num)},\n"
            f"  {sql_timestamp(txn_date)},\n"
            f"  NULL,\n"
            f"  '{seed_date}', '{seed_date}'\n"
            f");\n"
        )

    # --- 3. Transfer Orders (manufacturing flow) ---
    # Flow zones for transfers
    flow_stages = [
        ("Receiving Dock", "Plastics Storage"),
        ("Receiving Dock", "Raw Material Storage"),
        ("Raw Material Storage", "Coil Winding Floor"),
        ("Plastics Storage", "Coil Winding Floor"),
        ("Coil Winding Floor", "Coil Riveting"),
        ("Coil Riveting", "Contact Riveting"),
        ("Contact Riveting", "Assembly Floor"),
        ("Assembly Floor", "Calibration Bench"),
        ("Calibration Bench", "QA Hold"),
        ("QA Hold", "Finished Goods"),
    ]

    for i in range(transfer_count):
        xfer_id = det_uuid(f"xfer:{i}")
        # Pick flow stage
        stage_idx = int(det_uuid(f"xfer-stage:{i}").replace("-", ""), 16) % len(flow_stages)
        from_zone, to_zone = flow_stages[stage_idx]

        from_locs = zone_locations.get(from_zone, [])
        to_locs = zone_locations.get(to_zone, [])
        if not from_locs or not to_locs:
            continue

        from_loc_id = det_uuid(from_locs[0])
        to_loc_id = det_uuid(to_locs[0])

        # Pick product
        prod_idx = int(det_uuid(f"xfer-prod:{i}").replace("-", ""), 16) % len(all_products)
        prod = all_products[prod_idx]
        prod_id = det_uuid(f"product:{prod['sku']}")

        requested_by = get_employee_id(i)
        approved_by = get_employee_id(i + 1)

        qty = int(det_uuid(f"xfer-qty:{i}").replace("-", ""), 16) % 500 + 10

        # Date with exponential distribution
        rand_val = int(det_uuid(f"xfer-time:{i}").replace("-", ""), 16) % 10000
        fraction = rand_val / 10000
        days_offset = int((history_months * 30) * (1 - fraction ** 2))
        xfer_date = seed_dt - timedelta(days=days_offset)

        # Status: recent transfers in_transit, older ones completed
        status = "in_transit" if days_offset < 7 else "completed"

        stmts.append(
            f"INSERT INTO inventory.transfer_orders (id, product_id, from_location_id, "
            f"to_location_id, requested_by, approved_by, quantity, status, "
            f"transfer_date, created_date, updated_date) VALUES (\n"
            f"  '{xfer_id}',\n"
            f"  '{prod_id}',\n"
            f"  '{from_loc_id}',\n"
            f"  '{to_loc_id}',\n"
            f"  '{requested_by}',\n"
            f"  '{approved_by}',\n"
            f"  {qty},\n"
            f"  {sql_str(status)},\n"
            f"  {sql_timestamp(xfer_date)},\n"
            f"  '{seed_date}', '{seed_date}'\n"
            f");\n"
        )

    # --- 4. Inventory Adjustments ---
    reason_codes = ["cycle_count", "shrinkage", "damage", "correction"]
    reason_notes = {
        "cycle_count": "Cycle count variance detected during scheduled audit",
        "shrinkage":   "Shrinkage identified during inventory reconciliation",
        "damage":      "Units damaged during handling, scrapped per SOP",
        "correction":  "Data entry correction to align physical and system counts",
    }

    for i in range(adjustment_count):
        adj_id = det_uuid(f"adj:{i}")

        # Pick product
        prod_idx = int(det_uuid(f"adj-prod:{i}").replace("-", ""), 16) % len(all_products)
        prod = all_products[prod_idx]
        prod_id = det_uuid(f"product:{prod['sku']}")
        loc_id = get_location_id(prod["inventory_type"], prod["sku"])

        adjusted_by = get_employee_id(i)
        approved_by = get_employee_id(i + 1)

        # Reason code
        rc_idx = int(det_uuid(f"adj-rc:{i}").replace("-", ""), 16) % len(reason_codes)
        reason_code = reason_codes[rc_idx]
        notes = reason_notes[reason_code]

        # Quantity change: small, mostly negative (-50 to +50)
        qty_seed = int(det_uuid(f"adj-qty:{i}").replace("-", ""), 16) % 100 - 50
        if qty_seed == 0:
            qty_seed = -1  # avoid zero adjustments

        # Date with clustering
        rand_val = int(det_uuid(f"adj-time:{i}").replace("-", ""), 16) % 10000
        fraction = rand_val / 10000
        days_offset = int((history_months * 30) * (1 - fraction ** 2))
        adj_date = seed_dt - timedelta(days=days_offset)

        stmts.append(
            f"INSERT INTO inventory.inventory_adjustments (id, product_id, location_id, "
            f"adjusted_by, approved_by, quantity_change, reason_code, notes, "
            f"adjustment_date, created_date, updated_date) VALUES (\n"
            f"  '{adj_id}',\n"
            f"  '{prod_id}',\n"
            f"  '{loc_id}',\n"
            f"  '{adjusted_by}',\n"
            f"  '{approved_by}',\n"
            f"  {qty_seed},\n"
            f"  {sql_str(reason_code)},\n"
            f"  {sql_str(notes)},\n"
            f"  {sql_timestamp(adj_date)},\n"
            f"  '{seed_date}', '{seed_date}'\n"
            f");\n"
        )

    write_sql_file("23_manitowoc_inventory.sql",
                   "Manitowoc inventory: items, transactions, transfers, adjustments",
                   stmts)


def generate_sales(config, products, known_ids):
    """Generate 24_manitowoc_sales.sql — customers, orders, line items."""
    pass


def generate_procurement(config, products, suppliers, known_ids):
    """Generate 25_manitowoc_procurement.sql — suppliers, POs, line items."""
    pass


def generate_workflows(config, known_ids):
    """Generate 26_manitowoc_workflows.sql — automation rules, edges."""
    pass


def generate_permissions(config, known_ids):
    """Generate 27_manitowoc_permissions.sql — role grants."""
    pass


def main():
    print("Loading YAML data...")
    config = load_yaml("config.yaml")
    known_ids = load_yaml("known_ids.yaml")
    warehouses = load_yaml("warehouses.yaml")
    products = load_yaml("products.yaml")
    suppliers = load_yaml("suppliers.yaml")

    # Seed RNG for deterministic output
    random.seed(config["random_seed"])
    fake = Faker()
    Faker.seed(config["random_seed"])

    print(f"Config: {config['history_months']} months history, "
          f"{config['employee_count']} employees, {config['order_count']} orders")
    print(f"Products: {len(products['products'])} items loaded")
    print(f"Warehouses: {len(warehouses['warehouses'])} warehouses loaded")

    # Validate zone stages
    valid_stages = {"inbound", "received", "processing", "assembly",
                    "calibration", "qa", "outbound"}
    for wh in warehouses["warehouses"]:
        for zone in wh.get("zones", []):
            stage = zone.get("stage")
            if stage and stage not in valid_stages:
                raise ValueError(
                    f"Invalid zone stage '{stage}' in zone '{zone['name']}'. "
                    f"Valid: {valid_stages}")

    print("\nGenerating SQL files...")
    generate_org(config, warehouses, known_ids)
    generate_products(config, products, known_ids)
    generate_employees(config, known_ids)
    generate_inventory(config, products, warehouses, known_ids)
    generate_sales(config, products, known_ids)
    generate_procurement(config, products, suppliers, known_ids)
    generate_workflows(config, known_ids)
    generate_permissions(config, known_ids)

    print("\nDone.")


if __name__ == "__main__":
    main()
